### ISSUE TITLE
Splitting Axisymmetric Body Geometry

### ISSUE THREAD

**Issue by soffalonsoo** [capytaine/capytaine#134]
I was wondering whether there is an easy way to divide the geometry of an axisymmetric body (i.e: 6 rectangles acting as pontoons arranged in an hexagon), run the simulation on that section of the body to speed up the simulation and then extrapolate results to the full body.

**Comment by mancellin** [comment]
There is a optimization of this kind for axisymmetric body already in Capytaine (although I admit it is not well documented).
It should be in use in the "axisymmetric body" example in the cookbook.
For some theoretical details, see https://ancell.in/pdf/2018_OMAE_AD_7b4c6cfcdb.pdf

**Comment by mancellin** [comment]
Closing this thread since there has not been any new activity for a while. Feel free to reopen if you have a follow-up question or an issue.
