### ISSUE TITLE
Rectangle's volume after keep_immersed_part

### ISSUE THREAD

**Issue by cmichelenstrofer** [capytaine/capytaine#182]
```python
rect = cpy.RectangularParallelepiped()
rect.volume == rect.keep_immersed_part().volume
```

The volume should be halved but it isn't. This is becuase the volume is calculated from `self.size` ([line 296 in capytaine/bodies/predefined/rectangles.py](https://github.com/capytaine/capytaine/blob/master/capytaine/bodies/predefined/rectangles.py#L296)). 

Maybe the fix is as simple as removing the specialized version o f the `volume` method. But I don't know enough about these classes to tell if something else should be changed.

**Comment by mancellin** [comment]
Indeed, the old `volume` method for rectangles is inconsistent with the new general `volume` method.
I believe the old one can be safely removed.

**Comment by cmichelenstrofer** [comment]
@mancellin OK I can do the PR if that's helpful. Just delete that method and  add a line in the changelog.

**Comment by cmichelenstrofer** [comment]
Removed the following:
- `Rectangle`: area
- `RectangularParallelepiped`: volume
- `HorizontalCylinder`: volume
