### ISSUE TITLE
TypeError when importing FloatingBody

### ISSUE THREAD

**Issue by gregvw** [capytaine/capytaine#185]
I am unable to import capytaine with Python v.3.8.2 and numpy v.1.20.1 (Linux kernel 3.10.0-1160.62.1.el7.x86_64).
There is a TypeError exception which looks like it is caused by FloatingBody inheriting from collections.abc.ABC, but not having dtype-like attributes required by numpy.

> $ python3 -c "import capytaine"
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> import capytaine
>   File "site-packages/capytaine-1.4-py3.8-linux-x86_64.egg/capytaine/__init__.py", line 15, in <module>
>     from capytaine.bodies.bodies import FloatingBody
>   File "site-packages/capytaine-1.4-py3.8-linux-x86_64.egg/capytaine/bodies/__init__.py", line 4, in <module>
>     from capytaine.bodies.bodies import FloatingBody
>   File "site-packages/capytaine-1.4-py3.8-linux-x86_64.egg/capytaine/bodies/bodies.py", line 14, in <module>
>     import xarray as xr
>   File "site-packages/xarray/__init__.py", line 1, in <module>
>     from . import testing, tutorial
>   File "site-packages/xarray/testing.py", line 9, in <module>
>     from xarray.core import duck_array_ops, formatting, utils
>   File "site-packages/xarray/core/duck_array_ops.py", line 26, in <module>
>     from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
>   File "site-packages/xarray/core/npcompat.py", line 72, in <module>
>     _SupportsDType[np.dtype],
>   File "/local/libtyping.py", line 261, in inner
>     return func(*args, **kwds)
>   File "/local/libtyping.py", line 894, in __class_getitem__
>     _check_generic(cls, params)
>   File "site-packages/typing_extensions.py", line 95, in _check_generic
>     raise TypeError(f"{cls} is not a generic class")
> TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class

Here are screen caps of potentially relevant portions of numpy/typing/_dtype_like.py and typing_extensions.py

<img width="691" alt="numpy_typing_dtype_like" src="https://user-images.githubusercontent.com/6218267/181636643-ea04cf18-5076-4f78-9b37-d79f3edc09c3.png">

<img width="708" alt="typing_extensions" src="https://user-images.githubusercontent.com/6218267/181636715-2cda2e63-cc11-4658-81ae-b9eafca568bb.png">

**Comment by mancellin** [comment]
From the traceback
```
File "site-packages/capytaine-1.4-py3.8-linux-x86_64.egg/capytaine/bodies/bodies.py", line 14, in
import xarray as xr
```
the issue seems to be with the `xarray` dependency of Capytaine.

It could be https://github.com/pydata/xarray/issues/6818

**Comment by mancellin** [comment]
Closing the thread since I believe the underlying issue to be solved.
Feel free to reopen if necessary.
