### ISSUE TITLE
Mesh loader not recognizing symmetry in gdf's

### ISSUE THREAD

**Issue by jtgrasb** [capytaine/capytaine#186]
I am loading gdf files into Capytaine, but having issues due to the symmetry as defined in the header of the gdf. An example header is shown below with the 1's for ISX and ISY indicating symmetry about the x and y axes. 
![image](https://user-images.githubusercontent.com/87095491/181823381-c99bedf9-0143-4ce4-9ee1-a442f1fb66f3.png)

The mesh_loaders.py script reads the flags for isx and isy in, but does not currently use the flags to reflect the mesh to create the full mesh.

**Comment by mancellin** [comment]
Indeed, the reflection symmetry does not save time when preprocessing the mesh: as you may have noticed, all the panels (including the reflected ones) are computed and stored. But this is not the costly part.

The gain is in the solver. The interaction matrices have a $\begin{pmatrix} A & B \\\\ B & A \end{pmatrix}$ structure that is used e.g. here
https://github.com/capytaine/capytaine/blob/1dd0d150cb2ca48add7c05ac763eb46d8dbbd0f1/capytaine/bem/engines.py#L104-L115

**Comment by jtgrasb** [comment]
Ahh okay, makes sense. Thank you!
