### ISSUE TITLE
Run hydrostatics for multiple bodies

### ISSUE THREAD

**Issue by kmruehl** [capytaine/capytaine#188]
This relates to https://github.com/WEC-Sim/WEC-Sim/pull/925. I'm working on updating the WEC-Sim BEMIO examples to Capytaine v1.4, and calculating hydrostatics  directly in Capytaine. It seems that the hydrostatics cannot be calculated for multiple bodies at once, and instead must be calculated separately. 

Here's an example. I get an error if I run `bodies.hydrostatic_stiffness = bodies.compute_hydrostatic_stiffness()` directly

``` python

body1 = cpt.FloatingBody.from_file('flap.gdf') # many file types supported
body2 = cpt.FloatingBody.from_file('flap.gdf') # many file types supported

body1.center_of_mass = (0,0,-3.9)
body2.center_of_mass = (-25,0,-3.9)

body1.keep_immersed_part()
body2.keep_immersed_part()
# bodies =body1+body2
# bodies.keep_immersed_part()

body1.add_all_rigid_body_dofs()
body2.add_all_rigid_body_dofs()
# bodies.add_all_rigid_body_dofs()

body1.hydrostatic_stiffness = body1.compute_hydrostatic_stiffness()
body2.hydrostatic_stiffness = body2.compute_hydrostatic_stiffness()
# bodies.hydrostatic_stiffness = bodies.compute_hydrostatic_stiffness()

hydrostatics1 = body1.compute_hydrostatics()
hydrostatics2 = body2.compute_hydrostatics()
# hydrostatics = bodies.compute_hydrostatics()
```

Calculating the hydrostatics separately is really not an issue, except that there's no easy way to store the data. `capyData = cpt.assemble_dataset(results,hydrostatics=True)` doesn't work because `bodies` does not contain `hydrostatic_stiffness`, so the data has to be manually added (which is not ideal). My request is either to allow hydrostatics to run for multiple bodies, or provide an easier way to include each `hydrostatic_stiffness` in the output.

**Comment by mancellin** [comment]
We are a bit limited by Capytaine's data model: Capytaine does not _really_ support multiple bodies.
As far as hydrodynamics is concerned, having two bodies with 6 rigid dofs each or having a single "body" with 12 generalized dofs is the same.
So `body1+body2` actually returns a single body with a larger mesh and generalized dofs.

It works well for hydrodynamics.

It works so-so for hydrostatics.

The 12-dof body can still give you a 12×12 matrix for the hydrostatic stiffness, in the following way
```python
import numpy as np
import capytaine as cpt

body1 = cpt.Sphere(center=(0, 0, 0))
body1.center_of_mass = (0, 0, -0.3)
body1.add_all_rigid_body_dofs()
body1.keep_immersed_part()

body2 = cpt.Sphere(center=(25, 0, 0))
body2.center_of_mass = (25, 0, -0.3)
body2.add_all_rigid_body_dofs()
body2.keep_immersed_part()

bodies = body1 + body2
bodies.hydrostatic_stiffness = bodies.compute_hydrostatic_stiffness()
```
But I would not recommend you to do so, because in this case we are using the formula for generalized dofs, which is not as accurate as the rigid body special case.

Information about the original rigid bodies is lost when they are combined.
For instance, there is no way for `bodies` to store two centers of mass and two centers of buoyancy.
We can think about adding a proper `MultiFloatingBody` class, but it would mean revising large portions of the code data model.

What can be done in the near future:
- Improve error messages. I got an obscure `TypeError: 'NoneType' object is not subscriptable` when preparing the above example because of a missing center of mass.
- Provide some helper functions. For instance, combining the two 6×6 hydrostatic stiffness to a 12×12 hydrostatic stiffness for storing in the dataset.

**Comment by cmichelenstrofer** [comment]
Improving this would be very helpful for [WecOptTool](https://github.com/SNL-WaterPower/WecOptTool).  We use generalized DOFs and for instance for the RM3 we would have 7 DOFs:  `float:Heave`, `spar:Heave`, `combined:Surge`, `combined:Sway`, `combined:Pitch`, `combined:Roll`, and `combined:Yaw`.  If we try to run hydrostatics on this Floating body we would 1-get the error message above, or 2-get less accurate results because of the use of the formula for generalized DOFs. @ryancoe FYI

**Comment by sdillenburg** [comment]
What about combining stiffness matrices of individual bodies (if they exist for all bodies) when merging separate bodies to a multibody configuration, i.e. `K_all[6*N:6*(N+1),6*N:6*(N+1)] = K_body_N` (with N = 0, 1 ...)?

**Comment by kmruehl** [comment]
@mancellin thanks for your clarification on the hydrostatic implementation. That makes a lot sense. Based on the responses to this issue, it looks like there are a two different use cases for multi-body hydrostatics that need to be considered:

1. Calculate hydrostatic stiffness, displaced volume, center of buoyancy for each rigid body. This requires a data structure containing these field for each Capytiane hydrobody, e.g. WEC-Sim
2.  Calculate hydrostatic stiffness for multiple bodies with generalized body modes (e.g. RM3 with 7 DOF), e.g. wecOptTool

I can work on addressing the first use case, and have already begun to do so in https://github.com/WEC-Sim/WEC-Sim/pull/925. I'll keep working on it in that PR, and then we can decide whether it makes sense to be a BEMIO post-processing step, or a Capytaine option. 

However, this doesn't resolve the other use case, for wecOptTool.

**Comment by mancellin** [comment]
> it looks like there are a two different use cases for multi-body hydrostatics that need to be considered:
> 
> 1. Calculate hydrostatic stiffness, displaced volume, center of buoyancy for each rigid body. This requires a data structure containing these field for each Capytiane hydrobody, e.g. WEC-Sim
> 
> 2. Calculate hydrostatic stiffness for multiple bodies with generalized body modes (e.g. RM3 with 7 DOF), e.g. wecOptTool

Completely fixing point 1 would require breaking and rethinking large sections of the code in `FloatingBody` and `assemble_dataset`. In the short term, I'd suggest you use your own ad-hoc solution to keep track of the displaced volumes and the centers of buoyancy.

For the hydrostatic stiffness, I'll be working in the near future on improvements of the computation and handling of the 12×12 (resp. 7×7 for RM3) matrix.

**Comment by ykshif** [comment]
Hi @mancellin 
I want to calculate RAO for  multi-floating body array. I generated a 4*4 floating array using Assemble_regular_array().
Now, I have a problems and  I don't know how to calculate the hydrostatic_stiffness and inertia_matrix.I don't know if the following method is correct for calculating hydrostatic stiffness.And,when I calculate the inertia_matrix, it need to provide the center of mass, is there any way to find the center of mass fo each floating body?

`rectangle1 = cpt.RectangularParallelepiped(size=(1.0, 1.0, 1.0), resolution=(10, 10, 10), center=(0, 0, 0), top=True, bottom=True, reflection_symmetry=False, translational_symmetry=True, name="body1Name")
rectangle1.add_all_rigid_body_dofs()
rectangle1.center_of_mass = (0,0,0)
all = rectangle1.assemble_regular_array(4,(4,4))
all.keep_immersed_part()
all.hydrostatic_stiffness=all.compute_hydrostatic_stiffness()`

Thanks.

**Comment by mancellin** [comment]
> I want to calculate RAO for multi-floating body array. I generated a 4*4 floating array using Assemble_regular_array().

`assemble_regular_array()` is basically `body + body.translated(...) + body.translated(...) + ...`, so the previous comments about the `+` operation in Capytaine apply. Your `all` object did not keep track of the fact that it is composed of several rigid bodies with each a center of mass, so the code does not know how to compute the inertia matrix of the whole (it can compute the hydrostatic stiffness but only with an approximate formula).

To define manually the inertia and stiffness, you can implement @sdillenburg's suggestion above using something like this:
```python
import capytaine as cpt

# Defining original body
body = cpt.Sphere()
body.keep_immersed_part()
body.add_all_rigid_body_dofs()
body.center_of_mass = (0, 0, -0.1)
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()

# Duplicate into an array
array_of_bodies = body.assemble_regular_array(4, (2, 2))

from scipy.linalg import block_diag
array_of_bodies.inertia_matrix = array_of_bodies.add_dofs_labels_to_matrix(
    block_diag(*[body.inertia_matrix for _ in range(4)])
    )
array_of_bodies.hydrostatic_stiffness = array_of_bodies.add_dofs_labels_to_matrix(
    block_diag(*[body.hydrostatic_stiffness for _ in range(4)])
    )
```
Here, I used the fact that all bodies in the array have the same inertia and stiffness matrices.

In the future, I'd like to make this automatic when users call `+` or `assemble_regular_array()`.

**Comment by sdillenburg** [comment]
@mancellin 
Are you sure this will work? The hydrodynamic data of all bodies will refer to the same point in the global coordinate system, right? If so, the mass (parallel axis theorem) and inertia ( $K_{34}$, $K_{35}$, $K_{45}$ ) matrices of the individual bodies would need to refer to the same point and thus they would vary.

Please correct me if I am wrong...

**Comment by mancellin** [comment]
The convention in Capytaine is that when you do an operation such as `body.translated(...)` (as in `assemble_regular_array()`), you translate the mesh and also the center of mass and the axes of the rotation dofs.
So `body` and `body.translated(...)` should have the same hydrostatic (and hydrodynamic) matrices.

**Comment by mancellin** [comment]
>  So body and body.translated(...) should have the same hydrostatic (and hydrodynamic) matrices.

NB: they don't in v1.4 as discussed in #178, but it is a bug.

**Comment by ykshif** [comment]
> Quote reply
So when I compute the inertia matrix before  calling `keep_immersed_part()`?Otherwise I can't get the inertia matrix for the whole rigid body.

**Comment by mancellin** [comment]
> So when I compute the inertia matrix before calling `keep_immersed_part()`?
> Otherwise I can't get the inertia matrix for the whole rigid body.

Good point. I believe it deserves it's own issue.

**Comment by ykshif** [comment]
>I want to calculate RAO for multi-floating body array. I generated a 4*4 floating array using Assemble_regular_array().
> ```python
> from scipy.linalg import block_diag
> array_of_bodies.inertia_matrix = array_of_bodies.add_dofs_labels_to_matrix(
>     block_diag(*[body.inertia_matrix for _ in range(4)])
>     )
> array_of_bodies.hydrostatic_stiffness = array_of_bodies.add_dofs_labels_to_matrix(
>     block_diag(*[body.hydrostatic_stiffness for _ in range(4)])
>     )
> ```
(S100S200S3).

**Comment by mancellin** [comment]
Nice catch.

It works for the `+` operator:
```python
pair = body + body.translated((1.0, 0.0, 0.0), name="other_sphere")
print(pair.dofs.keys())
```
```
dict_keys(['sphere_0__Surge', 'sphere_0__Sway', 'sphere_0__Heave', 'sphere_0__Roll', 'sphere_0__Pitch', 'sphere_0__Yaw', 'other_sphere__Surge', 'other_sphere__Sway', 'other _sphere__Heave', 'other_sphere__Roll', 'other_sphere__Pitch', 'other_sphere__Yaw'])
```

So I was wrong when I said that `assemble_regular_array()` was equivalent to `body + body.translated(...) + body.translated(...) + ...`. I guess we can see this as a bug.

**Comment by mancellin** [comment]
Current status:

PR #243 made hydrostatic stiffness and inertia matrix straightforward for multiple rigid bodies. Especially if the hydrostatics are computed at the initialization of the individual bodies once #214 is done.

For articulated bodies, such as the RM3, #215 should make hydrostatic stiffness more straightforward.

Regarding other properties, such as center of buoyancy or displaced volume, I have no plan on how to cleanly handle the multibody case.

**Comment by mancellin** [comment]
Update for the upcoming release v3: without any particular setup by the user, multibody cases will output a dataset with all the hydrostatics properties body-by-body (such as center of mass, center of buoyancy for each body) or dof-by-dof (for the hydrostatic stiffness matrix and the inertia matrix).

The only thing missing from this discussion is to improve the support for articulated bodies with e.g. dofs `float__Heave`, `spar__Heave`, `combined__Surge`, `combined__Sway`, `combined__Roll`, `combined__Pitch`, `combined__Yaw` for the RM3 (already doable but not user-friendly).
