### ISSUE TITLE
"TypeError" when using "sphere.compute_hydrostatics()"

### ISSUE THREAD

**Issue by hfpim** [capytaine/capytaine#204]
Hello everyone,
I'm new to Capytaine and I was following the basic tutorial on the Ancell webpage (https://ancell.in/capytaine/latest/user_manual/tutorial.html).
Everything was working fine until I tried to run the "sphere.compute_hydrostatics()" command. IPython returned several highlighted lines and an error message: "TypeError: only integer scalar arrays can be converted to a scalar index".

I don't know if I am doing something wrong or if there is something wrong in my setup.
Has anyone ever seen an error like that?

**Comment by mancellin** [comment]
It could be a bug. The hydrostatics methods still have plenty of teething problems.

Could you share a minimal reproducible example of the issue?
And precise which version you are using (`from capytaine import __version__; print(__version__)`)?

**Comment by mancellin** [comment]
I think I figured it out: the tutorial is missing the definition of the center of mass of the sphere...

**Comment by mancellin** [comment]
Actually, it might be something else, unrelated to hydrostatics.
The way the "Surge" dof is defined in the tutorial messes up the mesh cropping:
```python
import capytaine as cpt
sphere = cpt.Sphere()
sphere.dofs['Surge'] = [(1, 0, 0) for face in sphere.mesh.faces]
sphere.keep_immersed_part()
```
```
[...]
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by hfpim** [comment]
I'm using version 1.4 of Capytaine.
I tried `sphere.keep_immersed_part()` and I had the same issue.
When I defined surge using `sphere.add_translation_dof(name="Surge")` I didn't have any problems using `sphere.keep_immersed_part()`. However I got a different error message when using `hydrostatics = sphere.compute_hydrostatics()`: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by hfpim** [comment]
After defining heave and surge as previously mentioned, I tried the manual method for computing the hydrostatic parameters and when I typed the command `print(sphere.compute_rigid_body_inertia())` an error message showed up, which I believe it's related to the fact that I haven't defined a center of gravity for the sphere.
![image](https://user-images.githubusercontent.com/112897638/189540521-155e0873-1bd7-4798-8da7-c74b7fd0c04e.png)

**Comment by hfpim** [comment]
I defined the sphere's mass and center of mass and the hydrostatics worked fine.
I kept the dof definitions as I mentioned above.

**Comment by mancellin** [comment]
Thank you very much for your feedback. It allows me to fix bugs and improve error messages for the next version. Please let me know of any other issue!

**Comment by hfpim** [comment]
Thank you very much for the support, much appreciated. I will definitely let you know if I find other issues
