### ISSUE TITLE
Accuracy for thin plates

### ISSUE THREAD

**Issue by mancellin** [capytaine/capytaine#228]
This issue investigates the results of the paper by Wanan Sheng et al (Ocean Engineering 2022) https://www.sciencedirect.com/science/article/pii/S0029801822003183

In this paper, the authors compare the results of Wamit, Hams and Nemoh on several meshes, including a cylinder with a thin damping plate.

![Mesh](https://user-images.githubusercontent.com/31126826/195331045-60c4368f-1395-49a5-8f2f-cc63a167a974.png)

Nemoh is found to be unreliable in this case, as seen in the graph below:

![Plot of the added mass from the aforementioned paper](https://user-images.githubusercontent.com/31126826/195330260-31d89b26-9c36-454f-a6b6-05cff54445be.png)

I tried to reproduce the above result (added mass of a heaving cylinder with a damping plate) with Capytaine.

In the graph below, the output of Capytaine for this mesh can be compared to the output of HAMS for the same mesh. The result of Capytaine seems to be the same as the result of Nemoh presented in the paper.

![Plot of the added mass from Capytaine](https://user-images.githubusercontent.com/31126826/195330254-218785fb-8031-41c6-9f3e-e7666f7a25f9.png)

When trying to reproduce the result by using my own mesh of the same geometry, the results were much closer to the ones of Wamit and Hams. It is unclear why the result is so sensitive to the mesh.

**Comment by mancellin** [comment]
The paper implies that the inacurracy of Nemoh could be due to the use of a tabulation of the Green function. However, when disabling the tabulation in Capytaine (at the cost of a large increase of the computation time), no significant change is visible in the output.
![No tabulation](https://user-images.githubusercontent.com/31126826/195336753-57aebbf7-8292-4fee-bb9e-2673062578a0.png)

**Comment by mancellin** [comment]
A possible explanation for the discrepancy between Nemoh/Capytaine and HAMS/Wamit is that the former use the *indirect* boundary integral equations while the latter use the *direct* boundary integral equations.
I have not been able to implement and validate the direct method in Capytaine yet, so I'm not really able to test this hypothesis at the moment.

**Comment by mancellin** [comment]
This has mostly been fixed by #420 and #439. Detailed results are presented in an upcoming conference paper.

**Comment by akeeste** [comment]
@mancellin is this publication on thin bodies in Capytaine available? I'm running a similar open-cylinder case with thin walls but my added mass values are ~70% of WAMIT output even with the direct solver. I'm still increasing mesh resolution, but runs are getting pretty expensive.

Should I generally expect a body with both x and y symmetry or an axisymmetric body to run faster?

**Comment by jnvn7** [comment]
@akeeste The conference paper is available here https://asmedigitalcollection.asme.org/OMAE/proceedings-abstract/OMAE2024/87851/V007T09A076/1202771

**Comment by mancellin** [comment]
> @mancellin is this publication on thin bodies in Capytaine available? I'm running a similar open-cylinder case with thin walls but my added mass values are ~70% of WAMIT output even with the direct solver. I'm still increasing mesh resolution, but runs are getting pretty expensive.

There might be something else going on. I'd be interested in more details if you want to open a new issue.

> Should I generally expect a body with both x and y symmetry or an axisymmetric body to run faster?

It can be made faster but it's not automatic. The plane symmetries are kinda documented, but the axisymmetric one is more experimental. Again, feel free to open another issue to discuss this.
