### ISSUE TITLE
Enquires about capytaine capacity for carrying out hydroelasticity 

### ISSUE THREAD

**Issue by austinerees** [capytaine/capytaine#246]
Greetings.
I'd like to ask if capytaine could conduct linear hydroelasticity analysis. If yes where can one find turorials?
Thanks alot

**Comment by austinerees** [comment]
Okay thanks for the response.Just so If you come across any documentation about doing something like this with capytaine, I'd really need it it's part of my studies at the moment.
Regards

**Comment by mancellin** [comment]
An example has been added there: https://github.com/capytaine/capytaine/blob/5e922d49460495ac6999efad90d6655805de1a8e/docs/user_manual/examples/elasticity_of_beam.py (although for some reason it is missing from the cookbook in the documentation).

I'm closing this old issue, but feel free to reopen if you have follow-up question or new issue.
