### ISSUE TITLE
Importing Mesh from Salome

### ISSUE THREAD

**Issue by davidfdomingos** [capytaine/capytaine#247]
Hi!
I'm trying to import a mesh directly from salome to capytaine but I run into the following error:

```
Traceback (most recent call last):
  File "C:/Users/.../SalomeImportTest/SalomeImportTest.py", line 11, in <module>
    shape = cpt.FloatingBody.from_file(dir, file_format='med')  # gmsh file
  File "C:\Users\...\lib\site-packages\capytaine\bodies\bodies.py", line 121, in from_file
    mesh = load_mesh(filename, file_format, name=f"{name}_mesh")
  File "C:\Users\...\lib\site-packages\capytaine\io\mesh_loaders.py", line 58, in load_mesh
    return loader(filename, name)
  File "C:\Users\...\lib\site-packages\capytaine\io\mesh_loaders.py", line 899, in load_MED
    quadrangles = file.get(item).value.reshape((4, -1)).T - 1
AttributeError: 'Dataset' object has no attribute 'value'
```

The code is:

```
import capytaine as cpt
import logging


#Logging
logging.basicConfig(level=logging.INFO)  # Options: INFO, DEBUG, WARNING

# Load a mesh
dir = 'C:/Users/PATH/SalomeImportTest/cube.med'
shape = cpt.FloatingBody.from_file(dir, file_format='salome')  # gmsh file

shape.show()  # Plot mesh
```

I'm using a conda environment with python 3.8 running on a windows laptop. Below you can download a file with a test code and a a mesh from salome. It is a simple cube.

[https://we.tl/t-Yhn2HIS1Ql](url)

**Comment by mancellin** [comment]
Thanks, I can reproduce your issue, it might be a bug with the mesh reader. I'll investigate when I have more time.

@frongere, just FYI, it might also be an issue with meshmagick.

**Comment by mancellin** [comment]
The same error occur when using meshmagick on the `barge.med` example file in meshmagick's repository. Maybe a breaking change in the dependancy `h5py` that got undetected because of the lack of testing for this kind of mesh.
