### ISSUE TITLE
Outputs for Bemio and wecSim

### ISSUE THREAD

**Issue by MasoudMiM** [capytaine/capytaine#25]
Hi Matthieu,

I am working on a specific type of ocean wave energy technology. I came across, Capytaine, which is a great and very user-friendly package.

I am using the code to get some specific outputs to be used as inputs for a different code (wecSim: http://wec-sim.github.io/WEC-Sim/overview.html) to simulate an ocean wave energy harvester. When I use Nemoh, I can get those outputs which include:

1. Nemoh.cal
2. Mesh Files:
  - Hydrostatics.dat
  - KH.dat
3. Results:
  - ExcitationForce.tec         
  - RadiationCoefficients.tec

I figured how to use "write_dataset_as_tecplot_files" command to get the files in item 3, however, I still do not know how to get the files for items 1 and 2 using Capytaine. I was wondering if it is possible to get these files the way Nemoh provides those outputs ?

Further, is it also possible to save the mesh file, created in Capytaine, preferably as a dat file ?

**Comment by mancellin** [comment]
Hi Masoud,

Thank you for the kind words.

Below is a detailed answer to your questions. It would be nice if the use of Capytaine with WEC-SIM was easier. If you write some code to do that, feel free to submit it for integration in Capytaine.

**About Nemoh.cal**

It's complicated.

Problems defined with Capytaine can be more general than what can be defined in a Nemoh.cal file. (For instance Nemoh.cal can only define rigid body dofs and a linear range of frequencies.) So, not all dataset can be exported to a Nemoh.cal file.

There is a drafty method [`capytaine.io.legacy.export_as_Nemoh_directory`](https://github.com/mancellin/capytaine/blob/c62848fa4b07043ecf6f70ac2ab9d8f1577ba607/capytaine/io/legacy.py#L114) that tries to do that. It is very limited and not tested much, but maybe you can use it as a start to write one for your application.

It might be easier to do it the other way around: write a Nemoh.cal file and then import it to Capytaine with [`capytaine.io.legacy.import_cal_file`](https://github.com/mancellin/capytaine/blob/c62848fa4b07043ecf6f70ac2ab9d8f1577ba607/capytaine/io/legacy.py#L20). It is not complete (some lines from Nemoh.cal are ignored, [see the documentation](https://ancell.in/capytaine/1.1/user_manual/problem_setup.html#legacy-nemoh-cal-parameters-files)) but it is more reliable than `export_as_Nemoh_directory`.

**About Hydrostatics.dat and KH.dat**

No, there is no computation of hydrostatic properties in Capytaine at the moment.
The computation can be done with [meshmagick](https://github.com/lheea/meshmagick), but you'll need to format it in Nemoh's format yourself.

**About the mesh file**
Check the `io.mesh_writers` module. Something like:
```python
from capytaine.io.mesh_writers import write_mesh
write_mesh("mesh.dat", body.mesh.vertices, body.mesh.faces, "nemoh")
```
