### ISSUE TITLE
Negative Added Mass and Damping

### ISSUE THREAD

**Issue by davidfdomingos** [capytaine/capytaine#253]
Good morning,

I'm trying to assess the sway and roll characteristics of a squared semi-sub in beam seas. However, Capytaine outputs negative values of damping and added mass. No relevant warnings or errors are displayed during the simulation. Attached is the script, mesh file and plot of the results that I'm obtaining. Has this been reported before?  
[NegativeDamping.zip](https://github.com/capytaine/capytaine/files/10139879/NegativeDamping.zip)

Cheers,
David

**Comment by mancellin** [comment]
I believe negative added mass and damping have been reported in previous studies (such as https://link.springer.com/article/10.1007/BF00042895), so that might not be a bug in Capytaine. But I am not familiar enough about this question to comment about the validity of the results of your test case.

**Comment by davidfdomingos** [comment]
Thanks for providing this reference. Probably soon I will have a quick look at this issue, if I find something helpful I'll post here.

**Comment by RubendeBruin** [comment]
@davidfdomingos , can you provide a picture of the mesh?

**Comment by davidfdomingos** [comment]
![Picture1](https://user-images.githubusercontent.com/78164888/208872963-ba92c838-1b15-448b-8f7b-66f7724d2b79.png)
@RubendeBruin here it is!

**Comment by sdillenburg** [comment]
@davidfdomingos 

Reasons for negative damping / negative added mass can be: 
* bad / strange hull definition,
* faces with close proximity to the bottom / free 
surface,
* irregular frequencies.

Horizontal surfaces are close to the free surface can cause negative added mass.
Negative damping can be due to surfaces being close to the seafloor or a quay. The water gets "pushed" against the fixed surface. This "hydraulic spring" effect is captured in hydrodynamic data as negative damping.

Check if the hydrodynamic data plotted over wave frequencies is smooth. If not, you probably have irregular frequencies.

**Comment by RubendeBruin** [comment]
Hi @davidfdomingos , thanks for the mesh.

SSCVs with the top of the floaters "close" to the waterplane are known to be "difficult" for diffraction. Did a lot of work on that in the past but unable to share that.

Publicly available data: https://repository.tudelft.nl/islandora/object/uuid%3Addc6e19a-66f2-4dc1-bbfa-485c1c73e69f

**Comment by davidfdomingos** [comment]
Thanks a lot for the feedback @RubendeBruin and @sdillenburg! It helps to have references, @sdillenburg do you have any references that you could provide about the negative damping?

**Comment by accient** [comment]
@davidfdomingos
 Hello, it's seems that you can import .med mesh from salome successfully.When I do the same thing, I got an error like this
![image](https://user-images.githubusercontent.com/37647393/222626044-edc7c0a5-ca6d-4771-bdff-9e2726d9a122.png)
With the latest "h5py" ,'Dataset' object has no attribute 'value', Have you ever met this problem and how did you solve it?
Looking forward to your reply!

**Comment by mancellin** [comment]
> @davidfdomingos Hello, it's seems that you can import .med mesh from salome successfully.When I do the same thing, I got an error like this ![image](https://user-images.githubusercontent.com/37647393/222626044-edc7c0a5-ca6d-4771-bdff-9e2726d9a122.png) With the latest "h5py" ,'Dataset' object has no attribute 'value', Have you ever met this problem and how did you solve it? Looking forward to your reply!

Looks like issue #247, which should have been fixed in version 1.5
