### ISSUE TITLE
Geometry files too small for hydrodynamics calculation?

### ISSUE THREAD

**Issue by taylortka** [capytaine/capytaine#271]
Hiya,

I've been attempting to use Capytaine to generate the required hydrodynamic coefficients to use as an input into the WEC-Sim Matlab software, which I have successfully done when I supply Capytaine with geometry .stl mesh files that are big (i.e. similar to real life implementation of point-absorber wave energy converters (PA-WEC) in ocean waters). However, when I attempt to create a model of a prototype-size (smaller - less than a metre-cubed volume) PA-WEC, the radiation IRF and excitation IRF of the Capytaine hydrodynamic data does not settle and the hydrodynamic data cannot be used in WEC-Sim successfully. 

I am wondering if this is a limitation of Capytaine itself, or if there is a way to change my method/code for smaller device calculations, or even if other softwares such as Nemoh could work for this instead? I am new to WECs and Capytaine is the first BEM software I have tried.

The dimensions for my device are shown below, and this is how the geometry files look when I give them to my Capytaine code. It is a two-body PA-WEC. When I keep everything the same but make the geometry files bigger (by 10^3), the hydrodynamic data works in WEC-Sim. 

<img width="260" alt="rack dimensions" src="https://user-images.githubusercontent.com/119858271/208485156-99361e74-a3c2-4a9d-94d2-1ced46a95670.png">
<img width="470" alt="float dimensions" src="https://user-images.githubusercontent.com/119858271/208485161-fa3a59d3-b53e-4e87-b0cf-ebc74364363c.png">

Thanks for your time, let me know if I need to provide anything else for this issue!

Below is the code I am using to create the hydrodynamic data. I'm not sure if this needs to be included but I figured it might be helpful, I've tweaked the code given by a WEC-Sim example on creating hydrodynamic data with Capytaine for a point absorber WEC-Sim.
```

`# -*- coding: utf-8 -*-
"""
Created on Mon Nov  9 10:08:14 2020
Modified on Thu July 1 07:25:00 2021

@author: akeeste; Yi-Hsiang

Initial working script by David Ogden from:
https://github.com/mattEhall/FrequencyDomain/blob/b89dd4f4a732fbe4afde56efe2b52c3e32e22d53/FrequencyDomain.py#L842

"""
import os

from multiprocessing import Process
import numpy as np
import capytaine as cpt
import meshmagick.mesh as mmm
try:
    # latest version on github removed the previous 
    # meshmagick.hydrostatics.Hydrostatics() method. Use old module w/ new version
    import meshmagick.hydrostatics_old as mmhs
except ModuleNotFoundError:
    # older versions of meshmagick should have meshmagick.hydrostatics.Hydrostatics() method
    import meshmagick.hydrostatics as mmhs

import xarray as xr
import logging as LOG
from glob import glob
import xarray as xr
import shutil
import platform
import sys

# Set the affinity back on all the cores solving the single core issue.
#   0xf is essentially a hexadecimal bitmask, corresponding to 4 cores 
#   0xffffffffff is used here for a maximum of 40 cores.
#   This is only used for Linux machines
if platform == "linux" or platform == "linux2":
    os.system("taskset -p 0xffffffffff %d" % os.getpid())

def __init__(self):
    LOG.info("Capytaine imported.")
    

def hydrostatics(myBodies, savepath=''):
    '''
    use meshmagick functions to calculate and output the hydrostatic stiffness,
    interia, center of gravity, center of buoyancy and displaced volume of a 
    capytaine bodies. Output is saved to Hydrostatics.dat and KH.dat files in 
    the same manner as Nemoh
    
    Example of output format:
    Hydrostatics.dat:
         XF =   0.000 - XG =   0.000
         YF =   0.000 - YG =   0.000
         ZF =  -2.500 - ZG =  -2.500
         Displacement =  0.4999997E+03
         Waterplane area =  0.1000002E+03
         
    KH.dat:
        0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00
        0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00
        0.0000000E+00  0.0000000E+00  0.9810053E+06 -0.1464844E-01 -0.5859375E-02  0.0000000E+00
        0.0000000E+00  0.0000000E+00 -0.1464844E-01  0.8160803E+07  0.0000000E+00  0.0000000E+00
        0.0000000E+00  0.0000000E+00 -0.5859375E-02  0.0000000E+00  0.8160810E+07  0.0000000E+00
        0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00


    Parameters
    ----------
    myBodies : List
        A list of capytaine floating bodies.

    Returns
    -------
    None
    '''
    nbod = len(myBodies)
    
    for i,body in enumerate(myBodies):
        cg = body.center_of_mass
        
        # use meshmagick to compute hydrostatic stiffness matrix
        # NOTE: meshmagick currently has issue if a body is copmletely submerged (OSWEC base)
        # use try-except statement to catch this error use alternate function for cb/vo
        # if completely submerged, stiffness is 0?
        body_mesh = mmm.Mesh(body.mesh.vertices, body.mesh.faces, name= body.mesh.name)
        try:
            body_hs = mmhs.Hydrostatics(working_mesh=body_mesh,
                                        cog=body.center_of_mass,
                                        rho_water=1023.0,
                                        grav=9.81)
            vo = body_hs.displacement_volume
            cb = body_hs.buoyancy_center
            khs = body_hs.hydrostatic_stiffness_matrix
        except:
            # Exception if body is fully submerged
            vo = body_mesh.volume
            cb = cg
            khs = np.zeros((3,3))
        
        # set file index
        fileind = ''
        if nbod != 1:
            fileind = '_' + str(i)
        
        # Write hydrostatic stiffness to KH.dat file as 
        khs_full = np.zeros((6,6))
        khs_full[2:5, 2:5] += khs
        tmp = savepath + 'KH' + fileind +'.dat'
        np.savetxt(tmp, khs_full)
        
        # Write the other hydrostatics data to Hydrostatics.dat file
        tmp = savepath + 'Hydrostatics' + fileind + '.dat'
        # f = open(rf'{tmp}','w')
        f = open(tmp,'w')
        for j in [0,1,2]:
            line =  f'XF = {cb[j]:7.3f} - XG = {cg[j]:7.3f} \n'
            f.write(line)
        line = f'Displacement = {vo:E}'
        f.write(line)
        f.close()


def call_capy(meshFName, wCapy, CoG=([0,0,0],), headings=[0.0],ncFName=None, 
              wDes=None, body_name=('',), depth=np.infty, density=1025.0,
              additional_dofs_dir=None,num_threads=1):
    '''
    Setup the problem and call the capytine solver.

    Setup parallel computing for different frequencies and combine the data 
    after the parallel simulation is completed.
    
    May be called with multiple bodies (automatically implements B2B). 
    In this case, the meshFName, CoG, body_name should be a tuple of the
    values for each body.
    
    Also has the ability to add generalized body modes by inputting the path to
    a 'gbm_dofs.py' file (see RM3 example).
    
    Parameters
    ----------
    meshFName : tuple of strings
        Tuple containing a string for the path to each body's hydrodynamic mesh.
        mesh must be cropped at waterline (OXY plane) and have no lid
    wCapy: array
        array of frequency points to be computed by Capytaine
    CoG: tuple of lists
        tuple contains a 3x1 list of each body's CoG
    headings: list
        list of wave headings to compute
    saveNc: Bool
        save results to .nc file
    ncFName: str
        name of .nc file
    wDes: array
        array of desired frequency points
        (for interpolation of wCapy-based Capytaine data)
    body_name: tuple of strings
        Tuple containing strings. Strings are the names of each body. 
        Prevent the body name from being a long file path
    depth: float
        Water depth. Should be positive downwards. Use decimal value to prevent 
        Capytaine outputting int32 types. Default is -np.infty
    density: float
        Water density. Use decimal value to prevent Capytaine outputting int32 
        types. Default 1025.0
    additional_dofs: string
        path to a gbm_dofs.py file that returns GBM dofs to this function

    Returns
    -------
    capyData: xarray Dataset
        Hydrodynamic coefficients as computed
    problems: list
        capytaine Problems that were solved
    '''
        
    # check that old output is not being overwritten (runs take awhile)
    if os.path.isfile(ncFName):
        print(f'Output ({ncFName}) file already exists and will be overwritten. '
               'Do you wish to proceed? (y/n)')
        try:
            ans = input()
        except EOFError:
            # Catch error that occurs when this script is run in a 
            # non-interactive way ('python CASE.py' in run_cases.py, etc) and
            # default to overwriting the output file
            ans = 'y'
            pass
        if ans.lower() != 'y':
            print('\nEnding simulation. file not overwritten')
            sys.exit(0)

    bodies = []
    for i in np.arange(0, len(meshFName)):
        bodies.append(cpt.FloatingBody.from_file(meshFName[i]))
        bodies[i].center_of_mass = CoG[i]
        bodies[i].keep_immersed_part()
        if body_name[i] != '':
            bodies[i].name = body_name[i]
        bodies[i].add_all_rigid_body_dofs()
    
    # calculate hydrostatics and output to KH.dat and Hydrostatics.dat files
    path,tmp = os.path.split(ncFName)
    path += os.path.sep
    hydrostatics(bodies,path)
    
    # add gbm dofs
    # 1. pass gbm_dofs.py path to call_capy
    # 2. Here: pass mesh to a local gbm_dofs.py script
    # 3. in the gbm_dofs.py script, create dofs based on body mesh that is passed in
    # 4. pass dof dict back to call_capy and continue adding to body
    if additional_dofs_dir is not None:
        old_dir = os.getcwd()
        os.chdir(additional_dofs_dir)
        import gbm_dofs
        additional_dofs = gbm_dofs.new_dofs(bodies)
        
        for i in np.arange(0, len(meshFName)):
            if body_name[i] in additional_dofs:
                for k,v in additional_dofs[body_name[i]].items():
                    bodies[i].dofs[k] = v
        os.chdir(old_dir)
    
    # combine all bodies to account for B2B interactions
    combo = bodies[0]
    for i in np.arange(1,len(bodies),1):
        combo += bodies[i]
    
    # call Capytaine solver
    print(f'\n-------------------------------\n'
          f'Calling Capytaine BEM solver...\n'
          f'-------------------------------\n'
          f'mesh = {meshFName}\n'
          f'w range = {wCapy[0]:.3f} - {wCapy[-1]:.3f} rad/s\n'
          f'dw = {(wCapy[1]-wCapy[0]):.3f} rad/s\n'
          f'no of headings = {len(headings)}\n'
          f'no of radiation & diffraction problems = {len(wCapy)*(len(headings) + len(combo.dofs))}\n'
          f'-------------------------------\n')
    
    wCapy_threads = np.array_split(np.array(wCapy),num_threads)

    if num_threads != 1:
        try:
            shutil.rmtree('capyParallelFolder')
        except OSError as e:        
            pass

        os.mkdir('capyParallelFolder')

    # An array for the processes.
    processing_jobs = []

    for i in range(num_threads):
        if num_threads == 1:
            ncFName_each_thread = ncFName
        else:
            os.chdir("./capyParallelFolder")
            ncFName_each_thread = os.getcwd() + os.path.sep + "capyParallel_{}.nc".format(i+1)
            os.chdir("../")

        p = Process(target=capy_solver, args= (wCapy_threads[i], CoG, headings,ncFName_each_thread,wDes, body_name, depth, density,
                    combo,additional_dofs_dir))
        processing_jobs.append(p)
        p.start()

    # Wait for all processes to finish.
    for proc in processing_jobs:
        proc.join()

    if num_threads == 1:
        capyData = read_netcdfs(ncFName, dim='omega')
    else:
        os.chdir("./capyParallelFolder")
        ncFName_thread = os.getcwd() + os.path.sep + 'capyParallel_*.nc'
        os.chdir("../")
        capyData = read_netcdfs(ncFName_thread, dim='omega')
        print('\nCombine Capytaine data and saved to \n' + ncFName +'\n\n')        
        capyData.to_netcdf(ncFName)

        # Remove saved Capytaine data from each thread. 
        try:
            shutil.rmtree('capyParallelFolder')
        except OSError as e:        
            pass
    
    # Create a dataset of parameters. 
    #     'fill_dataset()' automatically creates problems and solves them.
    problems = xr.Dataset(coords={
        'omega': wCapy,
        'wave_direction': headings,
        'radiating_dof': list(combo.dofs),
        'water_depth': [depth],
        'rho': [density],
        })
    
    print('\nCapytaine call complete. \n\n')

    return capyData, problems

def read_netcdfs(files, dim):
    # glob expands paths with * to a list of files, like the unix shell
    paths = sorted(glob(files))
    datasets = [xr.open_dataset(p) for p in paths]
    combined = xr.concat(datasets, dim)
    return combined    
    
def capy_solver(wCapy, CoG, headings,ncFName,wDes, body_name, depth, density,
                combo,additional_dofs_dir):
    '''
    call Capytaine for a given mesh, frequency range and wave headings
    This function is modified from David Ogden's work 
    (see https://github.com/mattEhall/FrequencyDomain/blob/b89dd4f4a732fbe4afde56efe2b52c3e32e22d53/FrequencyDomain.py#L842 for the original function).
    
    save the results to a file in Network Common Data Form.

    Returns
    -------
    None
    '''
    problems = xr.Dataset(coords={
        'omega': wCapy,
        'wave_direction': headings,
        'radiating_dof': list(combo.dofs),
        'water_depth': [depth],
        'rho': [density],
        })
    
    solver = cpt.BEMSolver()
    capyData = solver.fill_dataset(problems, [combo], hydrostatics=False)
    
    # # add kochin diffraction results
    # kochin = cpt.io.xarray.kochin_data_array(results, headings)
    # capyData.update(kochin)

    # save to .nc file
    cpt.io.xarray.separate_complex_values(capyData).to_netcdf(ncFName, encoding={'radiating_dof': {'dtype': 'U'}, 'influenced_dof': {'dtype': 'U'}})

    print('\nCapytaine call complete. Data saved to \n' + ncFName +'\n\n')

    return


`


The above function is called in my main BEM code:

`# -*- coding: utf-8 -*-
"""
Created on Thu Nov  5 13:15:35 2020

@author: akeeste
This script recreates the RM3 model based on sample BEM 
parameters from WEC-Sim (frequency range, directions, etc)

"""

# setup environment
import numpy as np
import os
import sys
sys.path.insert(1,'C:/Users/akeeste/Documents/Software/GitHub/capytaine/my_cases')

import call_capytaine as cc


# Define RM3 parameters ------------------------------------------------------#

#bodyGeom1 = cpt.FloatingBody.from_file('float_0.15m_diameter_cogfix.stl')
#bodyGeom2 = cpt.FloatingBody.from_file('rack_0.15m_diameter_cogfix.stl')
#bodyGeom1 = bodyGeom1.keep_immersed_part(sea_bottom=-inf, inplace=True)
#bodyGeom2 = bodyGeom2.keep_immersed_part(sea_bottom=-inf, inplace=True)
#bodyGeom1 = cpt.FloatingBody.from_file('float_0.15m_diameter_cogfix.stl')

#rm3_file = (os.getcwd() + os.path.sep + 'float_0.15m_diameter_cogfix.stl',
#             os.getcwd() + os.path.sep + 'rack_0.15m_diameter_cogfix.stl') # mesh files, .dat nemoh, .gdf wamit

#rm3_file = (os.getcwd() + os.path.sep + 'float_0.15m_diameter_cogfix_mm.stl',
 #            os.getcwd() + os.path.sep + 'rack_0.15m_diameter_cogfix_mm.stl') # mesh files, .dat nemoh, .gdf wamit
rm3_file = (os.getcwd() + os.path.sep + 'float_flumesize_meters.stl',
             os.getcwd() + os.path.sep + 'rack_flumesize_meters_cogatorigin.stl') # mesh files, .dat nemoh, .gdf wamit


rm3_cg = ((0,0,0),
          (0,0,0))                              # centers of gravity
rm3_name = ('wec_float',
            'wec_rack')                              # body names

rm3_w = np.linspace(3, 9, 3)                    # wave frequencies. 260 for full run (in rad/s)
rm3_headings = np.linspace(0,0,1)                    # wave headings (wave direction = 0)
rm3_depth = np.infty                               # water depth (m)

rm3_ncFile = os.getcwd() + os.path.sep + 'BEM_flumesize_meters_highfreq.nc'   # path for output .nc file
# ----------------------------------------------------------------------------#

# check that old output is not being overwritten (runs take awhile)
if os.path.isfile(rm3_ncFile):
    print(f'Output ({rm3_ncFile}) file already exists and will be overwritten. '
          'Do you wish to proceed? (y/n)')
    ans = input()
    if ans.lower() != 'y':
        print('\nEnding simulation. file not overwritten')
        sys.exit(0)

# Run Capytaine
cd, p = cc.call_capy(meshFName = rm3_file,
              wCapy     = rm3_w,
              CoG       = rm3_cg,
              headings  = rm3_headings,
              ncFName   = rm3_ncFile,
              body_name = rm3_name,
              depth     = rm3_depth,
              density   = 1000.0)
`
```

**Comment by mancellin** [comment]
> the radiation IRF and excitation IRF of the Capytaine hydrodynamic data does not settle and the hydrodynamic data cannot be used in WEC-Sim successfully.

Could you clarify what you mean? Do you get an error message from either Capytaine or WEC-Sim? Or do you get a result but it seems unphysicall/meaningless?

**Comment by mancellin** [comment]
Pinging @akeeste and @dav-og, since they are more familiar than me with the Capytaine/WEC-SIM interface.

**Comment by dav-og** [comment]
Hi @taylortka! Great to see you using these tools together :) I hope I can help.

My initial thought is that the discretization of your meshes could be improved:

![image](https://user-images.githubusercontent.com/12831266/208901329-7f54f95b-35da-4885-899d-df8c09deb5b2.png)

For BEM codes, typically we want to avoid these long, thin panels that SolidWorks creates, and have a more even distribution of panels over the body's surfaces. _Ideally_ we want to have some refinement around features and edges - but there is a trade-off between accuracy and speed.

For your cylinder, you could try using Capytaine's mesher: https://github.com/capytaine/capytaine/blob/d43ee33c1ddd3e0cd03c094c8c9f7c1516865e2d/capytaine/bodies/predefined/cylinders.py#L112

The blue mesh is a little less straightforward, but it appears to be axisymmetric? If so then its not too bad. If you can define the edge profile (x, z points in 2D) then you can use the following functions to revolve those points around the vertical axis and save to a .nemoh format mesh for use with Capytaine:

```python
def create_3d_points(x, z, nTheta):
    '''Take x, z coordinates and revolve around z axis at 360/nTheta spacing'''
    d2r = math.pi/180
    theta = np.linspace(0, 360*d2r, nTheta)
    x3d = np.zeros(len(x)*nTheta)
    y3d = np.zeros(len(x)*nTheta)
    z3d = np.zeros(len(x)*nTheta)
    iPoint = 0

    for i in range(nTheta):
        for j in range(len(x)):
            x3d[iPoint] = x[j]*math.cos(theta[i])
            y3d[iPoint] = x[j]*math.sin(theta[i])
            z3d[iPoint] = z[j]
            iPoint = iPoint+1

    return x3d, y3d, z3d


def create_3d_panels(xLen, nTheta):
    '''create array of panel numbers'''
    panels = np.zeros((4, (xLen-1)*(nTheta-1)))
    iPanel = 0

    for i in range(xLen-1):
        for j in range(nTheta-1):
            panels[0, iPanel] = (i+1) + xLen*j
            panels[1, iPanel] = (i+1) + 1 + xLen*j
            panels[2, iPanel] = (i+1) + 1 + xLen*(j+1)
            panels[3, iPanel] = (i+1) + xLen*(j+1)
            iPanel = iPanel+1

    return panels


def save_to_nemoh_mesh(filename, x3d, y3d, z3d, panels):
    '''save mesh points and panels to nemoh format'''
    f = open(filename, "w")
    f.write('%i %i\n' % (len(panels[0,:]), len(x3d)))

    for i in range(len(x3d)):
        f.write('%i %E %E %E\n' % (i+1, x3d[i], y3d[i], z3d[i]))
    f.write('0 0 0 0\n')

    for i in range(len(panels[0,:])):
        f.write('%i %i %i %i\n' % (panels[0, i], panels[1, i], panels[2, i], panels[3, i]))
    f.write('0 0 0 0\n')

    return 0
```

On second glance, it looks like the blue mesh has a hole through its centre? (I assume the green mesh fits in there..) ... if so then you will need to define points along that 'inner edge' in the list of points [x, z] that you pass to the 'revolver' function...I think it should still work though.

Another issue could be the proximity of the 2 bodies - but lets cross that bridge if/when we come to it.

Cheers - let me know how you get on.
Dave

@mancellin, thanks for @ing me 👍

**Comment by taylortka** [comment]
Firstly, thanks so much for all this help on this matter, I've been struggling with gettimg my model to work for the last few weeks but I've now got one model (the bigger scaled one) working :)

Thanks to @dav-og's recommendation, I changed my meshes to have less long thin triangles and to have a more even distribution for both the float and the rack, and these meshes are shown below.

<img width="443" alt="float better mesh" src="https://user-images.githubusercontent.com/119858271/209127320-9eb85ffb-9d8c-46d9-9521-36e1d1c2dbf4.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/119858271/209127493-e5a7b2dd-9991-4495-b053-0ec229baf36e.png">

The BEM created from these meshes worked with my WEC-Sim model successfully.

I also tried creating a cylinder mesh using the in-built Capytaine function although I really seemed to not be able to with the following code where I tried to implement the function 'mesh_vertical_cylinder' from the Capytaine documentation, but got an error that the function doesn't exist no matter how I tried to access it.

```
`import logging
import numpy as np
from numpy import inf
import capytaine as cpt

# Set up logging
logging.basicConfig(level=logging.INFO,
                    format="%(levelname)s:\t%(message)s")

mesh=cpt.mesh_vertical_cylinder(
            length=18, radius=0.9,
            center=(0, 0, 0),
            resolution=(1, 6, 8)
            )
`
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 10>()
      6 # Set up logging
      7 logging.basicConfig(level=logging.INFO,
      8                     format="%(levelname)s:\t%(message)s")
---> 10 mesh=cpt.mesh_vertical_cylinder(
     11             length=18, radius=0.9,
     12             center=(0, 0, 0),
     13             resolution=(1, 6, 8)
     14             )

AttributeError: module 'capytaine' has no attribute 'mesh_vertical_cylinder'`


I created these better meshes for my smaller scale model too, shown below.
<img width="342" alt="image" src="https://user-images.githubusercontent.com/119858271/209130880-4fb7ce55-cd43-4bc2-ab10-ce13f3fae6de.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/119858271/209130927-34d1ddfc-7cf4-4da1-b6a9-b1ea43a547c3.png">

However, the WEC-Sim model doesn't work with the hydrodynamic data from these meshes (the pictures shown below from the BEMIO script are generated from these smaller meshes). I did notice the BEM was far quicker to run with these meshes compared to the meshes of the bigger scale model, so tonight I will try a small scale BEM with a mesh with more triangles in it and see if that helps.

```
Replying to @mancellin, when I said that the hydrodynamic data "doesn't settle", I mean the impulse response function doesn't tend towards a certain value within the frequency range. The below pictures show this result for my smaller-scale geometry BEM, created by the BEMIO function in WEC-Sim that plots the hydrodynamic data.

![NRD](https://user-images.githubusercontent.com/119858271/209129657-d57f844d-aec9-4d24-beef-828fd9e071f0.jpg)
![NAM](https://user-images.githubusercontent.com/119858271/209129658-4d773967-563f-4336-a9bc-938a3766f38f.jpg)

Just having the bigger scale model working is okay for my group project, so I'm very happy and grateful for such helpful and quick responses from you all, so thanks again!



I have a couple notes on small additions to the documentation that would've saved me (and possibly others) some time, if that's alright:

I wonder if its worth putting a note about the type of meshes that are recommended to use as inputs to Capytaine BEM somewhere in the documentation for Meshes and Floating Bodies, since as a beginner to BEM and WECs I was unsure where to start. Maybe a note if you are using a mesh from a file, that the mesh file should be in meters, as I was unsure on that too. In fact, in the 'Conventions and differences to other codes' section of the documentation, it would be great if you could provide the unit convention for Capytaine as I don't know that Nemoh and WAMIT's convention are so that section wasn't helpful to me personally.

**Comment by dav-og** [comment]
@taylortka glad to hear that helped! A couple of other things that jump out:

- the resolution of your hydrodynamic coefficients looks quite coarse (i.e. the 'frequency step' probably needs reducing) - this can lead to errors when you convert the radiation damping coefficients to RIRFs (as you are integrating over the radiation damping coefficients).

- it looks like there could be some 'irregular frequencies' in the results. These can also lead to RIRFs not "settling" as integrating over the spike creates some abnormal high frequency content in the RIRF. Unfortunately Capytaine doesn't have the ability to remove these irregular frequencies yet but watch this space - I'm sure @mancellin will figure that out soon 😉

![image](https://user-images.githubusercontent.com/12831266/209153838-e4cff362-dd46-4a38-b7a7-15d3912ae0c5.png)

- probably a bigger issue in your results is the range of frequencies - as note 1 on your screen shot says - the coefficients should converge within your frequency range, but A11 only just seems to peak with the frequency range. Usually for a "full size" WEC we see convergence within 6 rad/s. Hence, 12 rad/s is already high...but its because your system is so small - its more sensitive to the higher frequency content. You may need to go up to 20 rad/s or even higher to see convergence. In reality, your system will probably never experience these frequencies, but it should help to get convergence in the coefficients and help to produce more accurage AMinf/RIRF values.

![image](https://user-images.githubusercontent.com/12831266/209154717-2643250c-1430-47b2-8f02-21668a5c6240.png)

Hope that makes sense - if you can improve points 1 and 2 then I think your .h5 file will work much better in WEC-Sim. I will close out this issue for now as the problem is really manifesting on the time-domain side. Hence, if you have any more Qs then drop us a line on the [WEC-Sim GH issues board](https://github.com/WEC-Sim/WEC-Sim/issues)

**Comment by dav-og** [comment]
>>  I will close out this issue for now as the problem is really manifesting on the time-domain side

@mancellin, I can't actually do that from my side 😅

**Comment by mancellin** [comment]
> I also tried creating a cylinder mesh using the in-built Capytaine function although I really seemed to not be able to with the following code where I tried to implement the function 'mesh_vertical_cylinder' from the Capytaine documentation, but got an error that the function doesn't exist no matter how I tried to access it.

This was added in version 1.5 which was released a few days ago. You might have an earlier version, which has only `cpt.VerticalCylinder()`. (The documentation of previous versions should still be available at https://ancell.in/capytaine/1.4.2/ or whatever version you are using.)

> Replying to @mancellin, when I said that the hydrodynamic data "doesn't settle", I mean the impulse response function doesn't tend towards a certain value within the frequency range. The below pictures show this result for my smaller-scale geometry BEM, created by the BEMIO function in WEC-Sim that plots the hydrodynamic data.

Did you use the same range of frequencies for the large scale model and the small scale model? The range of frequencies might be more adapted to one than the other: smaller body would respond to smaller wavelengths. Scaling the size of the body AND the wavelength (AND the water depth if not infinite) by the same factor should give you identical results.

> I wonder if its worth putting a note about the type of meshes that are recommended to use as inputs to Capytaine BEM somewhere in the documentation for Meshes and Floating Bodies, since as a beginner to BEM and WECs I was unsure where to start. Maybe a note if you are using a mesh from a file, that the mesh file should be in meters, as I was unsure on that too. In fact, in the 'Conventions and differences to other codes' section of the documentation, it would be great if you could provide the unit convention for Capytaine as I don't know that Nemoh and WAMIT's convention are so that section wasn't helpful to me personally.

Thank you for the feedback! Indeed the "convention" section of the documentation is really lacking.
