### ISSUE TITLE
Undefined f2py symbol when using Pip installation of Capytaine

### ISSUE THREAD

**Issue by michaelcdevin** [capytaine/capytaine#279]
Our software CI fails while building its Sphinx documentation site (GitHub Action workflow [here](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/workflows/release.yml#L42-L75)) with the following error:

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/runner/work/WecOptTool/WecOptTool/docs/source/conf.py", line 7, in <module>
    from wecopttool import __version__, __version_info__
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/wecopttool/__init__.py", line 32, in <module>
    from wecopttool.core import *
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/wecopttool/core.py", line 68, in <module>
    import capytaine as cpy
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/capytaine/__init__.py", line 26, in <module>
    from capytaine.bem.solver import Nemoh, BEMSolver
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/capytaine/bem/solver.py", line 31, in <module>
    class BEMSolver:
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/capytaine/bem/solver.py", line 48, in BEMSolver
    def __init__(self, *, green_function=Delhommeau(), engine=BasicMatrixEngine()):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/capytaine/green_functions/delhommeau.py", line 63, in __init__
    self.fortran_core = import_module(f"capytaine.green_functions.libs.{self.fortran_core_basename}_{floating_point_precision}")
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/capytaine/green_functions/libs/Delhommeau_float64.cpython-310-x86_64-linux-gnu.so: undefined symbol: f2py_size
```

This workflow uses Capytaine installed from `pip`; other CI workflows use the `conda` install without issue.

Mentioned and potentially related to #273, though the comment [here](https://github.com/capytaine/capytaine/issues/273#issuecomment-1376062215) was using Capytaine v1.4.2 instead of v1.5. The stacktrace posted above is using v1.5 (and with the cache reset, just to be sure).

**Comment by mancellin** [comment]
Interestingly the error does not seem to happen when installing Capytaine, but when running Sphinx to build your doc (either in `make linkcheck` or `make html`).

Could you test whether the same error occur when calling
```
python -c 'import capytaine'
```
outside of Sphinx?

**Comment by michaelcdevin** [comment]
I added `python -c 'import capytaine` line immediately before `make linkcheck`, and the same error occurs. The stacktrace is the same as above from the `capytaine/__init__.py` line onward.

**Comment by michaelcdevin** [comment]
@mancellin any ideas on this? I will take a look to see if I can fix this if you don't have time to at the moment.

**Comment by mancellin** [comment]
No, I have no clue and I did not manage to reproduce the error locally. I'm stuck, feel free to take a look yourself...

**Comment by michaelcdevin** [comment]
I've identified and resolve the problem (**tl;dr, adding `pip3 install wheel` before pip installing Capytaine resolves the issue**)

The issue here is two-fold: `wheel` was not installed in my environment, and my environment was downgrading NumPy to v1.23.5 due to another package dependency requiring `numpy<1.24`, which I didn't notice initially.

Since Capytaine does not have a `pyproject.toml` file, the following warning was thrown immediately before installing `capytaine`:
```
DEPRECATION: capytaine is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
And since NumPy was not previously installed, the `setup.py` file builds Capytaine using the most recent version of NumPy (I believe with [this line](https://github.com/capytaine/capytaine/blob/master/setup.py#L7)?), which conflicts with the top-level dependency resolution with the NumPy v1.23.5 install. I'm guessing the `f2py_size` symbol was added with the new F2PY functionality in NumPy [v1.24.0](https://github.com/numpy/numpy/releases/tag/v1.24.0), which explains the exception thrown.

I was able to replicate the issue in an isolated environment (even with `wheel` installed) with:
```
pip install charset-normalizer
pip install numpy==1.23.5 capytaine --no-binary capytaine #can remove the "--no-binary capytaine" if wheel is not installed
python -c 'import capytaine'
```
Note that replacing the second line with `pip install numpy==1.23.5; pip install capytaine --no-binary capytaine` does not cause the issue since Capytaine uses the local NumPy 1.23.5 that was installed in the previous step.

In my case, installing `wheel` in the GitHub Action workflow before installing my local package was the easy fix for this issue, since Capytaine then uses the NumPy `.whl` downloaded in the same installation step. Installing `pip3 install 'numpy<1.24'` would also work, but limited the NumPy version is less preferable.

**Comment by michaelcdevin** [comment]
Yes, when `wheel` is installed, pip builds using `setup.py bdist_wheel`. If not, pip simply calls `setup.py install`. I don't entirely comprehend everything `bdist_wheel` does, but to my understanding it includes some dependency resolution at build time, *then* it runs `setup.py install`. See https://pip.pypa.io/en/stable/reference/build-system/setup-py/
