### ISSUE TITLE
Mermaid diagram in docs is broken

### ISSUE THREAD

**Issue by mancellin** [capytaine/capytaine#311]
The diagram [there](https://ancell.in/capytaine/latest/theory_manual/theory.html#id21) is not rendered. Is it a general issue or is it just my browser?

**Comment by nhu-vnguyen** [comment]
@mancellin is this the figure you referred to? It seems to display fine on my end. 

![image](https://user-images.githubusercontent.com/67285162/228331557-544e738c-97d8-4cfa-92ce-5a0cf6c6be3c.png)

**Comment by mancellin** [comment]
Yes, I mean this figure.

That is weird. All I have is the raw source code on both Firefox and Chrome.

![Capture d’écran du 2023-03-28 21-17-16](https://user-images.githubusercontent.com/31126826/228344344-95a75449-2204-4d28-a687-5044289110e5.png)

**Comment by mancellin** [comment]
Seems to be working again. Not sure what happened...
