### ISSUE TITLE
Velocity field

### ISSUE THREAD

**Issue by freakingwave** [capytaine/capytaine#33]
Hi,

Thanks for the efforts on capytaine.
Im working on evaluating the wave velocity field affected by a large floating body.
Since the velocity field is the gradient of potential. Any ideas or insights could you offer to calculate the gradient? 

Thanks.

**Comment by mancellin** [comment]
The easiest way might be to call [`solver.get_potential_on_mesh`](https://ancell.in/capytaine/1.2/developer_manual/api/capytaine.bem.solver.html#capytaine.bem.solver.BEMSolver.get_potential_on_mesh) to retrieve the value of the potential field on a grid of points and then deduce the velocity field by finite differences.

If you are familiar with the BEM, there might be a better way by computing it directly from the interaction matrices (check the source code of `solver.get_potential_on_mesh` and adapt it to the velocity).

Anyway, a better interface to access the potential and velocity at any given point would be a nice addition to the code.

**Comment by freakingwave** [comment]
Mancellin,

Thanks for reply.

I prefer the second idea to compute from the interaction matrices which sounds more sensible and elegant. I know a little bit about BEM but still have no clue. Since  Φ=Sσ. It seems if I want the derivation of phi, I have to know the derivation of Green function in S. Do I have to modify the F90 code in the Green function? I still dont understand the code in F90 since the original paper is written in French. 
Can you give me some hints?

**Comment by mancellin** [comment]
No, the computation of the derivative of the Green function is already implemented in the main resolution.

The computation of the potential in the bulk is based on the left part of equation (36) in [the theory manual](https://ancell.in/capytaine/1.2/theory_manual/theory.html#equation-discrete-bem-problem). The right part might be used to recover the velocity. However, it is derived at the boundary and I don't remember if it is valid also in the bulk domain. This formula is not specific to linear potential flow, you should be able to check it in most BEM textbooks.

Then, look at [this example in the cookbook](https://ancell.in/capytaine/1.2/user_manual/cookbook.html#plot-the-influence-matrix) on how to compute the interaction matrices (here, K = V + I/2 with the notation of the theory manual).

**Comment by freakingwave** [comment]
Hi Mancellin,

Thanks for your detailed comments.

If my memory is right, in the fluid domain there is no I/2 in K=V+I/2. That means K=V. Is the V here stands for velocity? It seems in Eq(35) there is an additional n. Without n, I think V is the velocity. Is this n the normal vector of the receiving mesh?

**Comment by mancellin** [comment]
> If my memory is right, in the fluid domain there is no I/2 

Yes, something like that.

> That means K=V.

The code will still return the same K = V + I/2, so you will need to compute something like u = (K - I/2) σ.

> u is exactly the velocity I need

Almost.
K is computed as the interaction between the mesh of your floating body and some given mesh in the bulk domain (could be a single panel) and the velocity you will obtain is the normal velocity on this mesh in the bulk domain. You might need several calls to have a complete velocity vector field.

**Comment by freakingwave** [comment]
Many thanks.
I will find time to resolve this problem and update to you.

**Comment by mancellin** [comment]
The computation of the velocity field in post-processing has been implemented on the master branch and will be available in the next release.
