### ISSUE TITLE
Problem installing from pip

### ISSUE THREAD

**Issue by salicto** [capytaine/capytaine#349]
Hello everyone,

I'm new to Python and VS, so I'm not very familiar with this environment. I want to use the Capytaine code, but I'm getting this error. You'll find the terminal output after 'pip install capytaine'. If you happen to have the answer to this problem, that would be really awesome! 

Thanks in advance."
[Output_error.txt](https://github.com/capytaine/capytaine/files/11723168/Output_error.txt)

**Comment by mancellin** [comment]
The most important line in the error message is
```
error: extension 'capytaine.green_functions.libs.Delhommeau_float32' has Fortran sources but no Fortran compiler found
```

Indeed, the `pip` package currently does not include precompiled binaries for the Fortran core of Capytaine.

Your options:
- Use the `conda` package that includes precompiled binaries.
- Wait a little bit, as the next release (coming before the end of the month) should include precompiled binaries in the `pip` packages.
- Set up a Fortran compiler (can be cumbersome on Windows).

**Comment by salicto** [comment]
Hello @mancellin, 

Thank you for your response, I will wait for the next release. It will be easier.

**Comment by mancellin** [comment]
The new version is available on `pip`. Please reopen the thread if there is any problem with it.
