### ISSUE TITLE
Unexpected error while computing mesh connectivities

### ISSUE THREAD

**Issue by salicto** [capytaine/capytaine#373]
Hello everyone,

I'm trying to import a mesh created with gmsh. The function `cpt.load_mesh` correctly imports the mesh in .stl format. However, when I load the mesh file using the `cpt.FloatingBody(mesh=mesh)` method, I encounter the error "_Unexpected error while computing mesh connectivities._" Have any of you encountered this type of error before?

Thanks 

You will find attached the STL file.
[mesh_RAO.zip](https://github.com/capytaine/capytaine/files/12144062/mesh_RAO.zip)

**Comment by mancellin** [comment]
Thank you for your message.

The error message you encountered was raised in the `heal_mesh()` routines that come from meshmagick. (They are not strictly necessary for Capytaine, but can avoid some issues such as #46.)
This error in particular comes when the code is trying to check that all the normal vectors are in the same direction (the outside).
By looking at your mesh, I found that there is some kind of intermediate deck inside, which could be confusing for the code when trying to figure out the topology of the mesh.
![Screenshot of the mesh](https://github.com/capytaine/capytaine/assets/31126826/70317055-e668-4fa5-8c42-614ff80583f1)

Indeed, if I clip the mesh at the free surface before defining the body,
```python
mesh = cpt.load_mesh("Prototype_gmsh.stl",file_format="stl")
mesh = mesh.immersed_part()
body = cpt.FloatingBody(mesh=mesh)
```
then there is no error, as the topology check is only done on the lower part of the hull.

**Comment by mancellin** [comment]
Unrelated to your issue, but I can make a few comments about the code you shared:

- the call to `cpt.post_pro.free_surfaces.FreeSurface` is not necessary. This class was used in previous versions only to compute the free surface elevation at post-processing. In the latest version, there is a simpler way to do it, so  `cpt.post_pro.free_surfaces.FreeSurface` is left mostly for compatibility with older versions.

- you might want to replace `cpt.BasicMatrixEngine(linear_solver='direct')` by `cpt.BasicMatrixEngine(linear_solver='lu_decomposition')` which is faster while being as robust. The latter is also the default, so just calling `cpt.BEMSolver()` without argument should give you the optimal choice.

- What you print as RAO at the end is not the Response Amplitude Operator but the radiation damping.

**Comment by salicto** [comment]
Thank you very much for @mancellin improving the code. I modified the mesh by removing internal surfaces. I also switched to a mesh with quad elements instead of triangles. The viewer only displays triangle elements. Could it be an issue with the viewer? Anyway, I'm getting the same error as before...
P.S: On the meshMagick's meshViewer window, how did you manage to do clipping?"
[Prototype_gmsh_quad.zip](https://github.com/capytaine/capytaine/files/12159386/Prototype_gmsh_quad.zip)

**Comment by salicto** [comment]
Indeed, there is a surface within the mesh. Despite my attempts to remove it using a script, I have been unsuccessful. Consequently, I resorted to manual modification of the mesh. However, the script now throws an error when I try to utilize it.
 : `WARNING : The mesh of the body Prototype_gmsh_quad.stl is not inside the domain.
Check the position of the free_surface and the water_depth
or use body.keep_immersed_part() to clip the mesh.
INFO    : Solve RadiationProblem(body=Prototype_gmsh_quad.stl, omega=0.100, water_depth=inf, radiating_dof='Surge').
 Error: Impossible to compute the wave part of the Green function due to panels on the free surface (z=0) or above.
ERROR STOP 
 Error: Impossible to compute the wave part of the Green function due to panels on the free surface (z=0) or above.`
How can i resolve the problem ?  Should I translate the mesh in the Z-axis?

**Comment by mancellin** [comment]
Do you still call `immersed_part()` or `keep_immersed_part()` at some point?

Actually, you can work with your mesh file since the section of the mesh causing the issue is above the free surface, it will be thrown away when keeping the `immersed_part()` for the BEM.
Something like
```python
full_mesh = cpt.load_mesh("Prototype_gmsh_quad.stl")
mesh = full_mesh.immersed_part()
body = cpt.FloatingBody(mesh=mesh)
```
should work.

**Comment by salicto** [comment]
ok it's work thank you @mancellin
