### ISSUE TITLE
Bug in Example Problem: `get_velocity` not found

### ISSUE THREAD

**Issue by SoundsSerious** [capytaine/capytaine#387]
Great job with this library! Making life much easier :)

I found a minor bug in an example problem, I'm not sure if this is related to version changes 2.0 but [`plot_velocity_in_domain.py`](https://github.com/capytaine/capytaine/blob/v2.0/docs/user_manual/examples/plot_velocity_in_domain.py) appears to have an incorrect function name.

This code 
```python
# Compute the velocity field for each of the result object, that is each of the radiating dof
velocities = {}
for res in results:
    velocities[res.radiating_dof] = solver.get_velocity(res, points)
```

Should replace `get_velocity` with `compute_velocity` I think.
```python
# Compute the velocity field for each of the result object, that is each of the radiating dof
velocities = {}
for res in results:
    velocities[res.radiating_dof] = solver.compute_velocity( points,res)
```

**Comment by mancellin** [comment]
Good catch, thank you.

`get_velocity(res, points)` was the work-in-progress syntax, I forgot to update this example when harmonizing to `compute_velocity(points, res)`.

Would you like to submit a PR?

**Comment by SoundsSerious** [comment]
Give me a few days and I think i can take care of this.

**Comment by SoundsSerious** [comment]
@mancellin this has been addressed in #388

**Comment by mancellin** [comment]
Thank you for the fix.

However, when I try to run the example case, the result is wrong. There might be another issue with this example.

**Comment by mancellin** [comment]
So #348 added a multiplication by the complex unit $i$ to uniformize the conventions between radiation and diffraction  problems.
So what used to be the real part of the velocity is now the imaginary part.

The example looks better when taking the imaginary part instead of the real part.
I'm puzzled by the profile of the other component of the solution...

**Comment by SoundsSerious** [comment]
Sure thing, happy to help however its a pretty minor fix :)

That does confuse me as well, however I only have surface level knowledge. I wonder if perhaps this is due to some kind of transfer function derivative effect where `omega*j` is applied the the input and not removed?

**Comment by mancellin** [comment]
Closing the issue since the initial issue has been fixed.
There might be some remaining work to be done to validate the output of the computed velocity, but it is out of the scope of this issue.
