### ISSUE TITLE
Progress bar for BEM resolution

### ISSUE THREAD

**Issue by ldouteau** [capytaine/capytaine#403]
Hi Matthieu. Thank for the great work with Capytaine, very nice BEM solver !

When running BEM using the `fill_dataset` method the number of `LinearPotentialFlowProblem` to solve can be very big. It would be nice to have a progress bar displayed to keep track of the progress of the resolutions. That could be done using tqdm for example. I don't know if you have interest in that, in case here are some suggestions

Issue is, with the current recursive implementation of `solve_all` i'm not sure how that could be implemented. Here are some suggestions, that i didn't test
* A first step could be to use the verbose parameter from joblib's `Parallel`
* The fix provided in https://github.com/joblib/joblib/issues/972 would provide neater output, but still only compatible with parallel mode
* A workaround could be to add a parameter to `solve_all` denoting if the function if called from outside (sequential) or from within the function (parallel). A bit hacky, would add some code, but should do the job

**Comment by mancellin** [comment]
Thank you for the kind feedback!

I had started drafting something of this kind for sequential resolution with rich in #382.
The link you provided might give the missing joblib feature I need to extend it to parallel resolution, I need to check that.

**Comment by mancellin** [comment]
#382 has been merged, including a progress bar for serial and parallel resolutions.
