### ISSUE TITLE
Error when calling FloatingBody.disp_mass() with multiple bodies

### ISSUE THREAD

**Issue by jtgrasb** [capytaine/capytaine#413]
When computing the hydrostatics, the function calls self.disp_mass(). This leads to the following error when using it with multiple bodies.
<img width="484" alt="image" src="https://github.com/capytaine/capytaine/assets/87095491/e59d9913-a0ce-4596-934a-39c6de8a2261">
The issue seems to be resolved by setting rho = rho when calling the disp_mass() function.

**Comment by mancellin** [comment]
Never mind, I figured it out, you specified a mass (non-neutrally buoyant bodies).

Indeed, there are several issues with these lines: https://github.com/capytaine/capytaine/blob/8f295822e99261ebe4d5927d925a19c9385f422a/capytaine/bodies/bodies.py#L445-L450

**Comment by mancellin** [comment]
The error has been fixed, but your code might still not work: multiple non-neutrally-buoyant bodies are unfortunately not currently handled by Capytaine. If you did not meant to model non-neutrally-buoyant bodies, you can just ignore the `mass` parameter as the displaced mass is used by default.

**Comment by jtgrasb** [comment]
Thanks @mancellin. Yes, we are modeling multiple non-neutrally-buoyant bodies. The plan is to define the inertia manually, then use the compute_hydrostatic_stiffness function to get the hydrostatic stiffness, then solve the BEM problem. Is this an accurate way to run it?

**Comment by mancellin** [comment]
You might workaround the limitations of Capytaine for hydrostatics of multiple body by computing the hydrostatics of the individual bodies. When combining them, the previously computed hydrostatic stiffness will be used.
```python
import capytaine as cpt

c1 = (0, 0, 0)
mesh1 = cpt.mesh_sphere(center=c1)
body1 = cpt.FloatingBody(mesh1, cpt.rigid_body_dofs(rotation_center=c1), center_of_mass=c1, mass=1000.0)
body1.compute_hydrostatics()

c2 = (0, 3, 0)
mesh2 = cpt.mesh_sphere(center=c2)
body2 = cpt.FloatingBody(mesh2, cpt.rigid_body_dofs(rotation_center=c2), center_of_mass=c2, mass=1000.0)
body2.compute_hydrostatics()

both_bodies = body1 + body2
print(both_bodies.hydrostatic_stiffness)

# both_bodies.compute_hydrostatics()  # Fails because the code has lost track of the single rigid bodies and does not know how to handle non-single-rigid-body dofs.
```

**Comment by jtgrasb** [comment]
We have a WEC with two floating bodies (similar to RM3) and 4 dofs (float heave, spar heave, both surge, both pitch). We are defining the individual mass of the bodies and defining the inertia manually, then trying to use the compute_hydrostatic_stiffness() function to calculate the stiffness. Is it possible to get rid of the error for a case such as this?

**Comment by jtgrasb** [comment]
Thanks for the info. Another option I am considering is to compute the hydrostatic stiffness, then override the inertia matrix afterwards to the non-neutrally-buoyant values (which we use to solve the hydrodynamic equations of motion).
