### ISSUE TITLE
Time domain implementation

### ISSUE THREAD

**Issue by ykshif** [capytaine/capytaine#425]
Hello mancellin,

I have been working on the hydroelasticity of floating photovoltaic structures and have calculated the frequency domain hydrodynamic coefficients using capytaine with very good results. Now I expect to extend my hydroelastic model in time domain, so I may need to implement Cummins equation or state space equation, so I would like to ask capytaine if there is any plan to develop a time domain model.

The flexibility of capytaine has become an important component under my hydroelastic framework.

Thank you very much for your work and I look forward to hearing from you.

Regards.

**Comment by mancellin** [comment]
Thank you for your nice feedback.

No, there is no plan to add time domain model to Capytaine and there probably never will. I need to draw a line somewhere to avoid Capytaine's scope becoming too broad, and I think  "frequency domain only" (with some rare exceptions such as the stale PR #123) is the right scope to keep things manageable.

But one of the goals of Capytaine is to compose well with other tools, so let me know if there is anything I can do to help interface Capytaine with other software doing the time domain modelling.

**Comment by mancellin** [comment]
Closing the issue. Feel free to reopen if you have another question on this topic.
