### ISSUE TITLE
Issue with radiation wave elevation (probably related to phases)

### ISSUE THREAD

**Issue by sdillenburg** [capytaine/capytaine#431]
Dear all,

I have a question regarding the free surface elevation of radiated waves. I computed them based on the cookbook examples using the new `compute_free_surface_elevation` in version 2.0 (source: [here](https://github.com/capytaine/capytaine/blob/v2.0/capytaine/bem/solver.py#L253)) and `get_free_surface_elevation` in version 1.5 and 2.0 (source: [here](https://github.com/capytaine/capytaine/blob/v1.5/capytaine/bem/solver.py#L220) and [here](https://github.com/capytaine/capytaine/blob/v2.0/capytaine/bem/solver.py#L338))

Each function yields different wave elevations (code to generate the plots is at the end of this issue):

1.
![free_surface_dir_90__version_1 5](https://github.com/capytaine/capytaine/assets/45045610/793d5285-934c-4191-b97d-aa2afd0e80d9)
2.
![free_surface_dir_90__version_2 0](https://github.com/capytaine/capytaine/assets/45045610/c92738e1-85ae-4bb9-8513-208949ae7e89)
3.
![free_surface_version_dir_90_2 0_new_functions](https://github.com/capytaine/capytaine/assets/45045610/42cefb29-9048-4703-b4a9-9b42f35dfc27)
4.
![free_surface_dir_270__version_1 5](https://github.com/capytaine/capytaine/assets/45045610/65ef5d1a-582e-43f4-88b1-d7f410206471)
5.
![free_surface_dir_270__version_2 0](https://github.com/capytaine/capytaine/assets/45045610/7ee24aae-585c-45ab-91b2-36761998c249)
6.
![free_surface_version_dir_270_2 0_new_functions](https://github.com/capytaine/capytaine/assets/45045610/8b635a01-a4a2-4185-8be9-203ae3f7de57)

The results of `get_free_surface_elevation` (plots 1. and 2. as well as plots 4. and 5.) seem to differ in phase only. The results of `compute_free_surface_elevation` look very different. ~~With motion RAOs for a wave direction equal `pi/2`, I would consider the results of the new function in 2.0 (plot 3.) to be correct, since the radiation should be in both directions. But~~ _edit: Since the radiated waves due to roll and sway cannot be symmetrical (opposite phases on port and starboard side) for a given time instant, the total radiated wave pattern for a certain time instant cannot be symmetrical either. Only heave radiated waves are symmetric to the x axis. This can be seen in the plots 7., 8. and 9. For 90°, roll and sway contributions are cancelled out by the heave contribution on the side where x is positive._

I would expect plot 6. (motion RAOs for 270° wave direction) to be symmetric to plot 3. (90°).

7.
![Sway_free_surface_dir_90__version_1 5](https://github.com/capytaine/capytaine/assets/45045610/535f1391-cfea-4cbe-b75d-4e45aee4eeb3)
8.
![Heave_free_surface_dir_90__version_1 5](https://github.com/capytaine/capytaine/assets/45045610/8376aaa9-7bdd-4190-ba5a-f0caeca4ebd8)
9.
![Roll_free_surface_dir_90__version_1 5](https://github.com/capytaine/capytaine/assets/45045610/aeac212a-f986-40da-bffd-40368b28b188)

Additionally, results obtained with version 1.5 show a better agreement with tank tests (really small 1:144 model in a narrow tank, so I consider the agreement acceptable) compared to  `compute_free_surface_elevation` results (plots consider incident, radiated and diffracted waves):

![reduction_l100 8_b50 4_t6 3](https://github.com/capytaine/capytaine/assets/45045610/30df72d2-fbc9-4cba-b518-b14370f36369)
![reduction_l100 8_b50 4_t6 3](https://github.com/capytaine/capytaine/assets/45045610/c34a68f8-97e5-49e2-9049-5b7ae7ab63c8)

Here's the code to produce the first six plots in this issue

```
import capytaine as cpt
import logging
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

logging.basicConfig(level=logging.INFO, format='%(levelname)-8s: %(message)s')

version = float(cpt.__version__)

# Environment variables
directions = [90, 270]
omega = 1.0
water_depth = np.inf

# Free surface
xmin = -150
xmax = 150
ymin = -150
ymax = 150
nx = 60
ny = 60
x = np.linspace(xmin, xmax, nx, endpoint=True)
y = np.linspace(ymin, ymax, ny, endpoint=True)
fs = cpt.FreeSurface(x_range=(xmin, xmax), y_range=(ymin, ymax), nx=nx, ny=ny)

# Define box shaped body
length = 90  # m
beam = 30  # m
draft = 6 # m
zcg = 3

body = cpt.RectangularParallelepiped(size=(length, beam, draft), resolution=(int(length/2), int(beam/2), max(int(draft),5)),
                                           center=(0, 0, -0.5*draft), top=False, name='box')

body.add_all_rigid_body_dofs()
body.center_of_mass = (0, 0, zcg)
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()

# Solver
bem_solver = cpt.BEMSolver()

for direction in directions:
    # Problem setup and solve
    if version < 2:
        problems = [cpt.RadiationProblem(omega=omega, body=body, sea_bottom=-water_depth, radiating_dof=dof) for dof in body.dofs]
        problems.append(cpt.DiffractionProblem(omega=omega, body=body, sea_bottom=-water_depth, wave_direction=np.radians(direction)))
    elif version >= 2:
        problems = [cpt.RadiationProblem(omega=omega, body=body, water_depth=water_depth, radiating_dof=dof) for dof in body.dofs]
        problems.append(cpt.DiffractionProblem(omega=omega, body=body, water_depth=water_depth, wave_direction=np.radians(direction)))
    
    results = bem_solver.solve_all(problems)
    *radiation_results, diffraction_result = results
    
    dataset = cpt.assemble_dataset(results) 
    
    # Postprocessing   
    rao = cpt.post_pro.rao(dataset, wave_direction=np.radians(direction))

    print(direction, rao)
            
    radiation_elevations_per_dof = {res.radiating_dof: (-1j*omega)*bem_solver.get_free_surface_elevation(res, fs) for res in radiation_results}
    radiation_elevation = sum(rao.sel(omega=omega, radiating_dof=dof).data * radiation_elevations_per_dof[dof] for dof in body.dofs)
    
    def plot_free_surface_elevation(free_surface_elevation, filename):
        fig, ax = plt.subplots(figsize=(12, 9))
    
        ax.set_title(filename)
        ax.set_aspect('equal', 'box')
        ax.set_xlabel('x [m]')
        ax.set_ylabel('y [m]')
        
        
        fs_elevation = np.abs(free_surface_elevation)*np.sin(np.angle(free_surface_elevation))
        fs_elevation = fs_elevation.reshape((nx, ny)).T
        
        h = ax.contourf(x, y, fs_elevation, levels=np.linspace(-1.,1.,9),extend='both')
        
        box = patches.Rectangle((-length/2, -beam/2), length, beam, linewidth=1, edgecolor='k', facecolor='gray')
        ax.add_patch(box)
        
        plt.colorbar(h, ax=ax, aspect=30, orientation='horizontal', label='Wave elevation [m]')
    
        plt.savefig(filename)
    
        
    plot_free_surface_elevation(radiation_elevation, 'free_surface_dir_{}__version_{}.svg'.format(direction, version))
    
    if version >= 2:
        # Postprocessing using new free surface elevation functions
        radiation_elevations_per_dof = {res.radiating_dof: bem_solver.compute_free_surface_elevation(fs.mesh, diffraction_result) for res in radiation_results}
        radiation_elevation = sum(rao.sel(omega=omega, radiating_dof=dof).data * radiation_elevations_per_dof[dof] for dof in body.dofs)
        
        plot_free_surface_elevation(radiation_elevation, 'free_surface_version_dir_{}_{}_new_functions.svg'.format(direction, version))

```

Summarizing my questions: 
1. Which approach is the correct one?
2. Although `get_free_surface_elevation` is deprecated in 2.0, the results should be that same in 1.5 and 2.0, shouldn't they?
3. Why do the radiated waves computed with `compute_free_surface_elevation` differ for 90° and 270°? This is not due to the instant of time, see following plots which show the absolute values: 

![free_surface_version_dir_90_2 0_new_functions](https://github.com/capytaine/capytaine/assets/45045610/a5b07bed-80c8-447d-9c6d-4b0f44526897)
![free_surface_version_dir_270_2 0_new_functions](https://github.com/capytaine/capytaine/assets/45045610/20484b7f-f8e4-4a11-82cd-923e90fe50a0)

Any hint for further investigation is appreciated!

**Comment by mancellin** [comment]
Thank you for reporting this.

I don't have the time to look in depth into it right now, but here are some comments:

- the result is expected to be different by a factor of $-j \omega$ between v1.5 and v2.0. Some background and motivation can be found in #173. Radiation problems (and not diffraction problems) used to need a manual correction of their output. That is the `(-1j*omega)` term in the following line, that is only required in v1.5 and should be removed in v2.0[^1].
```
radiation_elevations_per_dof = {res.radiating_dof: (-1j*omega)*bem_solver.get_free_surface_elevation(res, fs) for res in radiation_results}
```

- in v2.0, `compute_free_surface_elevation` and `get_free_surface_elevation` should give the same result. The former just has a different call signature that is meant to be the same in all of Capytaine (e.g. the same as `airy_wave_free_surface_elevation`).

- in one of the last lines of your code, you are iterating other the radiation results but use the diffraction result to compute the free surface elevation:
```
radiation_elevations_per_dof = {res.radiating_dof: bem_solver.compute_free_surface_elevation(fs.mesh, diffraction_result) for res in radiation_results}
```

But there has been some reports of suspicious results (such as #191 and #387) so there might be a bug somewhere in there.

[^1]: In retrospect, I could have made the change only in `compute_free_surface_elevation` and kept the old convention in the legacy `get_free_surface_elevation`. These were two different changes and I did not think of that in time.

**Comment by sdillenburg** [comment]
@mancellin 

Your comments solved the entire issue ;)
Many thanks!!

Your last comment is a copy & paste error from here: https://github.com/capytaine/capytaine/blob/v2.0/docs/user_manual/examples/boat_animation.py#L44 

So the example should be corrected.

For the sake of completeness, here's the adjusted code:

```
import capytaine as cpt
import logging
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

logging.basicConfig(level=logging.INFO, format='%(levelname)-8s: %(message)s')

version = float(cpt.__version__)

# Environment variables
directions = [90, 270]
omega = 1.0
water_depth = np.inf

# Free surface
xmin = -150
xmax = 150
ymin = -150
ymax = 150
nx = 60
ny = 60
x = np.linspace(xmin, xmax, nx, endpoint=True)
y = np.linspace(ymin, ymax, ny, endpoint=True)
fs = cpt.FreeSurface(x_range=(xmin, xmax), y_range=(ymin, ymax), nx=nx, ny=ny)

# Define box shaped body
length = 90  # m
beam = 30  # m
draft = 6 # m
zcg = 3

body = cpt.RectangularParallelepiped(size=(length, beam, draft), resolution=(int(length/2), int(beam/2), max(int(draft),5)),
                                           center=(0, 0, -0.5*draft), top=False, name='box')

body.add_all_rigid_body_dofs()
body.center_of_mass = (0, 0, zcg)
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()

# Solver
bem_solver = cpt.BEMSolver()

for direction in directions:
    # Problem setup and solve
    if version < 2:
        radiation_problems = [cpt.RadiationProblem(omega=omega, body=body, sea_bottom=-water_depth, radiating_dof=dof) for dof in body.dofs]
        diffraction_problem  = cpt.DiffractionProblem(omega=omega, body=body, sea_bottom=-water_depth, wave_direction=np.radians(direction))
    elif version >= 2:
        radiation_problems = [cpt.RadiationProblem(omega=omega, body=body, water_depth=water_depth, radiating_dof=dof) for dof in body.dofs]
        diffraction_problem  = cpt.DiffractionProblem(omega=omega, body=body, water_depth=water_depth, wave_direction=np.radians(direction))
    
    radiation_results = bem_solver.solve_all(radiation_problems)
    diffraction_result = bem_solver.solve(diffraction_problem)
    
    results = radiation_results + [diffraction_result]
    
    dataset = cpt.assemble_dataset(results) 
    
    # Postprocessing   
    rao = cpt.post_pro.rao(dataset, wave_direction=np.radians(direction))
    
    if version < 2:    
        radiation_elevations_per_dof = {res.radiating_dof: (-1j*omega)*bem_solver.get_free_surface_elevation(res, fs) for res in radiation_results}
    elif version >= 2:
        radiation_elevations_per_dof = {res.radiating_dof: bem_solver.get_free_surface_elevation(res, fs) for res in radiation_results}
        
    radiation_elevation = sum(rao.sel(omega=omega, radiating_dof=dof).data * radiation_elevations_per_dof[dof] for dof in body.dofs)
    
    def plot_free_surface_elevation(free_surface_elevation, filename):
        fig, ax = plt.subplots(figsize=(12, 9))
    
        ax.set_title(filename)
        ax.set_aspect('equal', 'box')
        ax.set_xlabel('x [m]')
        ax.set_ylabel('y [m]')
        
        
        fs_elevation = np.abs(free_surface_elevation)*np.sin(np.angle(free_surface_elevation))
        fs_elevation = fs_elevation.reshape((nx, ny)).T
        
        h = ax.contourf(x, y, fs_elevation, levels=np.linspace(-1.,1.,9),extend='both')
        
        box = patches.Rectangle((-length/2, -beam/2), length, beam, linewidth=1, edgecolor='k', facecolor='gray')
        ax.add_patch(box)
        
        plt.colorbar(h, ax=ax, aspect=30, orientation='horizontal', label='Wave elevation [m]')
    
        plt.savefig(filename)
    
        
    plot_free_surface_elevation(radiation_elevation, 'free_surface_dir_{}__version_{}_w_get_free_surface_elevation.svg'.format(direction, version))
    
    if version >= 2:
        # Postprocessing using new free surface elevation functions
        radiation_elevations_per_dof = {res.radiating_dof: bem_solver.compute_free_surface_elevation(fs.mesh, res) for res in radiation_results}
        radiation_elevation = sum(rao.sel(omega=omega, radiating_dof=dof).data * radiation_elevations_per_dof[dof] for dof in body.dofs)
        
        plot_free_surface_elevation(radiation_elevation, 'free_surface_dir_{}__version_{}_w_compute_free_surface_elevation.svg'.format(direction, version))
```

**Comment by mancellin** [comment]
> Your last comment is a copy & paste error from here: https://github.com/capytaine/capytaine/blob/v2.0/docs/user_manual/examples/boat_animation.py#L44

Ah, yes indeed. Would you like to submit a PR with the correction?

**Comment by sdillenburg** [comment]
Yes, will do (I have not done this befoe, so I probably need some time to dig in the github details  ;))
