### ISSUE TITLE
Trying to export DAT. file and nc. file

### ISSUE THREAD

**Issue by Wilton3737** [capytaine/capytaine#433]
Hi,

I am trying to learn capytaine. Now, I have run the tutorial and managed to complete all the steps.
then, I tried to export the file so that I could put it in Bemio to generate h5 file.

Problem 1:
I am having trouble to export the dat. file 
![image](https://github.com/capytaine/capytaine/assets/149406844/5a7ed223-7fc3-4696-853e-484598f6d273)
it keeps stating Bodies is not defined while I just follow the step on the website 

Problem 2:
Meanwhile, I would like to confirm if i am doing it correctly to get the .nc file
here is the code I wrote
![image](https://github.com/capytaine/capytaine/assets/149406844/190e99c6-0da7-47cd-86e6-13fba9386102)
here is the result
![image](https://github.com/capytaine/capytaine/assets/149406844/41028e27-f69d-452c-866a-311fe59e8d46)
kinda sus as it only has 3KB

Next, in BEMIO examples, there are so many files required to generate h5 file
![image](https://github.com/capytaine/capytaine/assets/149406844/9cebd716-ec2b-4594-90e9-08e6a7fa8cca)
How could i use capytaine to generate other files for example, cylinder.dat and cylinder.gdf

Thank you in advance for solving my questions.

**Comment by mancellin** [comment]
Thank you for your questions.

> Problem 1:

It is a bit difficult to help without more context. Do you have a full self-contained Python script that you could share?
Note that the example in the documentation spells `bodies` with a lowercase `b`. But you could have named your own variable differently.

> Problem 2:

Looks good, but since I don't know how many frequencies/dofs/wave directions were in your dataset, I can't really tell if it makes sense to have 3kb of data.

> How could i use capytaine to generate other files for example, cylinder.dat and cylinder.gdf

They are mesh files, so for most real use case you'll prepare them with a dedicated software before providing them to both Capytaine and WEC-SIM. But if you need to export a mesh from Capytaine there are some functions for that purpose in [`capytaine.io.mesh_writers`](https://github.com/capytaine/capytaine/blob/26926f1cfa6dfefc5613883bfaf8a58f5587ae64/capytaine/io/mesh_writers.py)

**Comment by Wilton3737** [comment]
Problem 1:
i guess the body refers to sphere in the tutorial, this is what i do:
![image](https://github.com/capytaine/capytaine/assets/149406844/1c1722c7-db77-45c9-9fb1-b98adaad8cf8)
however, it still needs a "mesh" thing, how could i solve this?

i guess this "mesh" thing is referring to [capytaine.io.mesh_writers](https://github.com/capytaine/capytaine/blob/26926f1cfa6dfefc5613883bfaf8a58f5587ae64/capytaine/io/mesh_writers.py)
so i just follow the step to create mesh and i will be able to out put all the files needed for BEMIO, am i correct?

this zip file has my coding
[code.zip](https://github.com/capytaine/capytaine/files/13334092/code.zip)

**Comment by mancellin** [comment]
Thank you for sharing the code.

In the examples from the documentation, `list_of_results` and `bodies` are placeholder variable names that are meant to be replaced by the one you actually use in your code.

- In the tutorial example, there is a single `FloatingBody` object defined as a Python variable called `body`. So to export its hydrostatic data, you could call something like
```python
export_hydrostatics("./", body)
```
which should write two files called `KH.dat` and `Hydrostatics.dat` in the current working directory.

- Similarly, in the tutorial there is a list of results called `all_radiation_results`. So the following code
```python
dataset = cpt.assemble_dataset(all_radiation_results)
dataset.to_netcdf("dataset.nc")
```
should export this data to a file. Since only few problems are solved in the tutorial example, it makes sense for the resulting file to be very small (basically two 7×7 matrices plus metadata).

- For the `ValueError: NetCDF 3 does not support type complex128`, check [that section of the documentation](https://capytaine.github.io/stable/user_manual/outputs.html#complex-numbers).

- Finally about meshes: the section of the documentation in your screenshot is about loading a mesh into Capytaine, not exporting it from Capytaine to a file.
If your goal is to reproduce the BEMIO example, I would suggest to load with Capytaine the same mesh file they are using. Something like the following:
```python
import capytaine as cpt
mesh = cpt.load_mesh("cylinder.gdf")
body = cpt.FloatingBody(mesh=mesh, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)))
...
```

**Comment by Wilton3737** [comment]
Hi @mancellin ,
thanks for your help. I have successfully exported the hydrostatic.dat and KH.dat file

however, when i tried to put it in BEMIO to produce an h5 file, It stated that I was missing the following
![image](https://github.com/capytaine/capytaine/assets/149406844/925f5f87-ac68-40ab-824c-1731bf341deb)
how could I define all these 

I would like to clarify my goal is to design a new part that could be imported into wecSim to get a power output profile. 
in order to do this, i need capytaine to produce BEM code for bemio to read, then initiate wecSIm to use the BEMIO to produce power output profile. For now, i have successfully done the tutorial, i will proceed to try my own file.

I hope you can assist me along the way.
Thank you.

**Comment by mancellin** [comment]
> however, when i tried to put it in BEMIO to produce an h5 file, > It stated that I was missing the following
> how could I define all these

My bad, my example of a "list of results" above was a bit short, as there were only the radiation results. WEC-SIM need some information about the excitation forces, which are computed in Capytaine by solving diffraction problems.

>  Here how do I limit the degree of freedom to only heave motion?

One possible way:
```python
body = cpt.FloatingBody(mesh=mesh, center_of_mass=(0, -10.57, 0))
body.add_translation_dof(name="Heave")
```

**Comment by Wilton3737** [comment]
Hi @mancellin,
Noted. So my list of result should contain both diffraction result and radiation result like this 
![image](https://github.com/capytaine/capytaine/assets/149406844/7016f37d-5416-40c8-bc20-8edaa65f4daf)

After i adding the diffraction result, i couldnot export .nc as complex number problem shows
![image](https://github.com/capytaine/capytaine/assets/149406844/ddc04e5b-62c8-4d2e-b4f4-fa136770a408)

but i have alr followed the section u mentioned last time to separate the complex number 
![image](https://github.com/capytaine/capytaine/assets/149406844/44a8fc07-d6ec-4a9b-aed4-c73ccb0f90ad)
 could you give a me a clearer guidance on this?

Thank you very much.
below attached is my code file.
[code 2.zip](https://github.com/capytaine/capytaine/files/13366078/code.2.zip)

**Comment by mancellin** [comment]
I took a look at your code.

One error message is because you need to explicitly import the library `xarray` to read the dataset:
```python
import xarray as xr
from capytaine.io.xarray import merge_complex_values
dataset = merge_complex_values(xr.open_dataset("datatest.nc"))
```
It should be added to the example in the documentation.

Specifying the encoding is usually not required, but if you have some issues, you should try the following to do both the complex value fix and the encoding fix:
```python
separate_complex_values(dataset).to_netcdf("dataset.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
```

**Comment by Wilton3737** [comment]
HI @mancellin 
I have successfully exported the .nc and hydrostatic and KH.dat
![image](https://github.com/capytaine/capytaine/assets/149406844/2884bef1-4649-4a66-9344-e72212dc8982)

However, when i tried to run bemio with it, it does not work
![image](https://github.com/capytaine/capytaine/assets/149406844/cd977535-2ca3-4e1d-8f19-a8baee1dc10e)

this is my source code
[code 2.zip](https://github.com/capytaine/capytaine/files/13441200/code.2.zip)

Pls guide me on this. thank you very much

**Comment by mancellin** [comment]
Most likely you need to have several frequencies in your dataset.
Check the examples in Capytaine's cookbook on how to solve problems for several frequencies.

**Comment by Wilton3737** [comment]
Hi @mancellin 

Noted and i am trying to run this cylinder example 
![image](https://github.com/capytaine/capytaine/assets/149406844/fc2ae035-d0a1-44eb-8364-0682d6e73366)

I am facing the 'body' issue again
![image](https://github.com/capytaine/capytaine/assets/149406844/80d96098-15c8-4728-adc5-ebd36c02427e)
how do i fix this?
this is my source code
[code 3.zip](https://github.com/capytaine/capytaine/files/13442587/code.3.zip)

I am not sure if i am going to the right path. I am just trying to export something to be used in bemio. Please guide me.
Your help is much appreciated

**Comment by mancellin** [comment]
In the tutorial, a problem looking like this is defined:
```python
cpt.DiffractionProblem(body=body, wave_direction=np.pi/2, omega=1.0)
```
Here the frequency of the waves is set to $\omega = 1.0$ rad/s.

To study the behavior of your floating body at sea, you need to solve the problem for all the wave frequencies that your body might encounter at sea.


One way to do that in Capytaine, [adapted from this example in the cookbook](https://capytaine.github.io/v2.0/user_manual/cookbook.html#added-mass-of-a-rigid-body), is about doing a `for` loop in Python:
```python
list_of_problems = [
    cpt.RadiationProblem(body=cylinder, radiating_dof=dof, omega=omega)
    for dof in cylinder.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=cylinder, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
data = cpt.assemble_dataset(list_of_results)
```

**Comment by Wilton3737** [comment]
Hi @mancellin,

i met this problem when trying to solve list_of_result
![image](https://github.com/capytaine/capytaine/assets/149406844/591b7434-02d4-4ec2-bc70-c28fe5b94384)
this time, i have imported my stl file into and might this be the source of problem?
check out my zip file for the code and stl file
[buoy.zip](https://github.com/capytaine/capytaine/files/13478652/buoy.zip)

Please guide me to solve this issue
thank you.

**Comment by mancellin** [comment]
Might be an issue with the mesh having panels outside the domain, as suggested by the warning you received a few cells earlier:
```
WARNING:capytaine.bem.problems_and_results:The mesh of the body buoy.stl is not inside the domain
Check the position of the free_surface and the water_depth
or use body.keep_immersed_part() to clip the mesh.
```
I'm working on replacing this crash of the kernel by a proper error message (#418).


The mesh you shared is completely out of the water ($z>0$). Also the axis seems to be horizontal, I don't know if it is on purpose. You can do [some basic editing of the mesh from within Capytaine](https://capytaine.github.io/stable/user_manual/mesh.html#geometric-transformations) and use the following code the display it (after installing the matplotlib package).
```python
import matplotlib.pyplot as plt
mesh.show_matplotlib()
```

**Comment by mancellin** [comment]
The free surface is always at $z=0$ and the sea bottom at $z=-d$, where $d$ is the depth you provide to the code, so the domain for the $z$-coordinate is $z \in [-d, 0]$.
You can use the `translated_z` method to move your mesh vertically and `immersed_part` to remove the part out of the water.
Beware that the code currently does not support horizontal panels on the free surface.

**Comment by Wilton3737** [comment]
Hi @mancellin 
![image](https://github.com/capytaine/capytaine/assets/149406844/53c71c81-a909-4a25-825e-ae5599033c47)
i have inserted the translation but my mesh is not translated
May i know what have gone wrong here?

[code.zip](https://github.com/capytaine/capytaine/files/13509980/code.zip)

thank you

**Comment by mancellin** [comment]
Try out
```
mesh = mesh.translated_z(-60.0)
```
such that the variable named `mesh` now denoted the translated object.

**Comment by mancellin** [comment]
If your mesh was completely above the free surface when running `immersed_part()`, then it would have removed every panel in the mesh. Could it be the case?

**Comment by Wilton3737** [comment]
Hi @mancellin,
i  do not think so i have placed my part under the free surface where z=0
![image](https://github.com/capytaine/capytaine/assets/149406844/62172b1c-9044-4e80-860a-0767a74c4120)
as you can see in this image my part is partly submerged in the medium.
please guide me to fix this issue 

thank you 
regards 
Wilton

**Comment by mancellin** [comment]
Hum, that is weird. I can't reproduce your error with the code your shared yesterday, would you mind updating it?

By the way, it would be slightly more convenient for me to get your code directly in Github's text box rather than in an attached Jupyter notebook. Could you copy the whole failing code (without outputs) as in the example below
````
```python
import capytaine as cpt
mesh = cpt.load_mesh("buoy.STL")
body = cpt.FloatingBody(mesh=mesh, dofs=cpt.rigid_body_dofs(rotation_center=(0, -10.57, 0)), center_of_mass=(0, -10.57, 0))
# etc.
```
````
which appears on Github once published as

```python
import capytaine as cpt
mesh = cpt.load_mesh("buoy.STL")
body = cpt.FloatingBody(mesh=mesh, dofs=cpt.rigid_body_dofs(rotation_center=(0, -10.57, 0)), center_of_mass=(0, -10.57, 0))
# etc.
```

**Comment by Wilton3737** [comment]
Hi @mancellin 
below attached is my code and my stl
[buoy.zip](https://github.com/capytaine/capytaine/files/13561045/buoy.zip)

thanks 

```python
import capytaine as cpt
import logging
logging.basicConfig(level=logging.INFO)
mesh = cpt.load_mesh("buoy.stl")
body = cpt.FloatingBody(mesh=mesh, center_of_mass=(0, 0, 0))
body.mesh.heal_mesh()
body.add_translation_dof(name="Heave")
mesh = mesh.translated_z(-60.0)
body = body.immersed_part()
import matplotlib.pyplot as plt
mesh.show_matplotlib()
import numpy as np
import xarray as xr
from numpy import infty
omega_range = np.linspace(0.1, 6.0, 20)
list_of_problems = [
    cpt.RadiationProblem(body=body, radiating_dof=dof, omega=omega)
    for dof in body.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=body, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
from capytaine import assemble_dataset
from capytaine.io.xarray import separate_complex_values
separate_complex_values(dataset).to_netcdf("dataset.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
from capytaine.io.legacy import export_hydrostatics
export_hydrostatics("test.dat", body)
```

**Comment by mancellin** [comment]
Oh, I see, the issue is that there
```python
body = cpt.FloatingBody(mesh=mesh, center_of_mass=(0, 0, 0))
# [...]
mesh = mesh.translated_z(-60.0)
```
you are are creating a new translated mesh, but the former one is still used for the `FloatingBody` that you defined earlier.

I would recommend to do the mesh translation before creating the `FloatingBody`, or alternatively translate the newly created body with 
```python
body = body.translated_z(-60.0)
```

**Comment by Wilton3737** [comment]
Hi @mancellin,
Thanks for fixing the issue..
Now when i am trying to create the list of problem
it stated that my mesh has no dof
![image](https://github.com/capytaine/capytaine/assets/149406844/cfd8766d-5981-4297-9423-287a86a20d3c)
how can i address this?

thanks for guiding

```python
import capytaine as cpt
import logging
logging.basicConfig(level=logging.INFO)
mesh = cpt.load_mesh("buoy.stl")
body = cpt.FloatingBody(mesh=mesh, center_of_mass=(0, 0, 0))
body.mesh.heal_mesh()
body.add_translation_dof(name="Heave")
body = mesh.translated_z(-160.0)
body = body.immersed_part()
import matplotlib.pyplot as plt
body.show_matplotlib()
import numpy as np
import xarray as xr
from numpy import infty
omega_range = np.linspace(0.1, 6.0, 20)
list_of_problems = [
    cpt.RadiationProblem(body=body, radiating_dof=dof, omega=omega)
    for dof in body.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=body, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
from capytaine import assemble_dataset
from capytaine.io.xarray import separate_complex_values
separate_complex_values(dataset).to_netcdf("dataset.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
from capytaine.io.legacy import export_hydrostatics
export_hydrostatics("test.dat", body)
```

**Comment by mancellin** [comment]
You replaced your `FloatingBody` by a `Mesh` when you did
```python
body = mesh.translated_z(-160.0)
```

**Comment by Wilton3737** [comment]
hi  @mancellin 
good  day to u
i have solved the issue above, thanks for your help 
but when i am trying to compute the hydrostatics, it shows that i need to include this hydrodrostatics_stiffness
![image](https://github.com/capytaine/capytaine/assets/149406844/680841c0-ae34-414b-b7d6-979e3bff76ab)

this is the part that i added but it is showing errors on the last line in this image below
![image](https://github.com/capytaine/capytaine/assets/149406844/3aa3a77b-0e3c-4d55-8743-4e392525d806)

it stated that the matrix array is not matching i guess
how do i find out my matrix size
![image](https://github.com/capytaine/capytaine/assets/149406844/161840ad-1864-4d62-b5dd-b9a5b70028b0)

Please help me to solve this issue, thank you
below attached is my stl file and my code 
thank you 

Best regards,
Wilton

Stl file:
[buoy.zip](https://github.com/capytaine/capytaine/files/13996961/buoy.zip)

```python
import capytaine as cpt
import logging
logging.basicConfig(level=logging.INFO)
mesh = cpt.load_mesh("buoy.stl"
body = cpt.FloatingBody(mesh=mesh, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
body.mesh.heal_mesh()
body.add_translation_dof(name="Heave")
body = body.translated_z(-160.0)
body.dofs["elongate_in_z"] = np.array([(0, 0, z) for (x, y, z) in body.mesh.faces_centers])
dofs_divergence = {"elongate_in_z": np.ones(body.mesh.nb_faces)}
density = 1000.0
gravity = 9.81
elongate_in_z_hs = body.compute_hydrostatic_stiffness(divergence=dofs_divergence, rho=density, g=gravity)
analytical_hs = - density * gravity * (4 * body.volume * body.center_of_buoyancy[2])
print(np.isclose(elongate_in_z_hs.values[0, 0], analytical_hs))
body.inertia_matrix = body.compute_rigid_body_inertia()
body.inertia_matrix = body.add_dofs_labels_to_matrix(np.array([[1000.0]]))
body = body.immersed_part()
import matplotlib.pyplot as plt
body.show_matplotlib()
import numpy as np
import xarray as xr
from numpy import infty
omega_range = np.linspace(0.1, 6.0, 20)
list_of_problems = [
    cpt.RadiationProblem(body=body, radiating_dof=dof,  omega=omega)
    for dof in body.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=body, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
from capytaine import assemble_dataset
dataset = cpt.assemble_dataset(list_of_results)
from capytaine.io.xarray import separate_complex_values
separate_complex_values(dataset).to_netcdf("dataset.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
from capytaine.io.legacy import export_hydrostatics
export_hydrostatics("test.dat", body)
```

**Comment by mancellin** [comment]
Regarding the `AttributeError: FloatingBody has no hydrostatic_stiffness`, you could just replace the line
```python
elongate_in_z_hs = body.compute_hydrostatic_stiffness(divergence=dofs_divergence, rho=density, g=gravity)
```
by
```python
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness(divergence=dofs_divergence, rho=density, g=gravity)
```
Because the `export_hyrostatics` function is looking for an attribute named `body.hydrostatic_stiffness` and cannot guess that you've named your hydrostatic stiffness matrix in another way.

---

Regarding the `ValueError: conflicting sizes ...`: the error is raised because you are trying to replace the 7×7 inertia matrix by a 1×1 matrix (with value 1000.0).
If you `print(body.inertia_matrix.values)`, you'll see the 7×7 matrix computed at the previous line by `compute_rigid_body_inertia`.

Note the `NaN` in the line and columns corresponding to the elastic dof: the hydrostatics methods of Capytaine are not able to guess the inertia corresponding to such a dof. If you want to fill in manually these values, you can do something like the following (assuming the `NaN`s are in the 7th line and column):
```
body.inertia_matrix.values[:, 6] = 0.0
body.inertia_matrix.values[6, :] = 0.0
body.inertia_matrix.values[6, 6] = 1000.0
```

**Comment by Wilton3737** [comment]
Hi @mancellin,
thanks for your help.
i am now  able to generate result from capytaine and use it in wecsim bemio.
thank you  very much and really do appreciate your help along the way.
Have a good day.

**Comment by Wilton3737** [comment]
Hi @mancellin,
I have another problem now,,haha
I am trying to add multibodies in a single capytaine code to produce one capytaine result file.
not sure how to do it, could you give some advise?

![image](https://github.com/capytaine/capytaine/assets/149406844/ce4ec0ee-80f5-454b-a26e-8cf76f228fcd)
![image](https://github.com/capytaine/capytaine/assets/149406844/0659b897-243f-4706-8a60-a8d5ed583cd1)
i am having problem with this line
please advice how to solve this issue
```python
import capytaine as cpt
import numpy as np
import logging
logging.basicConfig(level=logging.INFO)
mesh1 = cpt.load_mesh("buoy.stl")
mesh2 = cpt.load_mesh("plate.stl")
body1 = cpt.FloatingBody( mesh=mesh1, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, -400)),
                        center_of_mass=(0, 0, 0))
body2 = cpt.FloatingBody(mesh=mesh2, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
body1.mesh.heal_mesh()
body2.mesh.heal_mesh()
bodies = body1 + body2
bodies = cpt.FloatingBody( dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
bodies.add_translation_dof(name="Heave")
bodies = bodies.translated_z(-450)
bodies.dofs["elongate_in_z"] = np.array([(0, 0, z) for (x, y, z) in bodies.mesh.faces_centers])
dofs_divergence = {"elongate_in_z": np.ones(bodies.mesh.nb_faces)}
density = 1000.0
gravity = 9.81
bodies.hydrostatic_stiffness = bodies.compute_hydrostatic_stiffness(divergence=dofs_divergence, rho=density, g=gravity)
elongate_in_z_hs = bodies.hydrostatic_stiffness
analytical_hs = - density * gravity * (4 * bodies.volume * bodies.center_of_buoyancy[2])
print(np.isclose(elongate_in_z_hs.values[0, 0], analytical_hs))
bodies.inertia_matrix = bodies.compute_rigid_body_inertia()
bodies.inertia_matrix.values[:, 6] = 0.0
bodies.inertia_matrix.values[6, :] = 0.0
bodies.inertia_matrix.values[6, 6] = 1000.0
bodies = bodies.immersed_part()
import matplotlib.pyplot as plt
bodies.show_matplotlib()
import xarray as xr
from numpy import infty
omega_range = np.linspace(0.1, 6.0, 20)
list_of_problems = [
    cpt.RadiationProblem(body=bodies, radiating_dof=dof,  omega=omega)
    for dof in bodies.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=bodies, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
from capytaine import assemble_dataset
databuoy = cpt.assemble_dataset(list_of_results)
from capytaine.io.xarray import separate_complex_values
separate_complex_values(databuoy).to_netcdf("databuoy.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
from capytaine.io.legacy import export_hydrostatics
export_hydrostatics("testbuoy.dat", body)
```
below are my stl file
[stl.zip](https://github.com/capytaine/capytaine/files/14227950/stl.zip)

Thanks 
Regards
Wilton

**Comment by mancellin** [comment]
At the line
```python
bodies = body1 + body2
bodies = cpt.FloatingBody( dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
```
The object created by `cpt.FloatingBody(...)` is a mesh-less body which is replacing and erasing the object (the sum of two bodies) created by the line above.

Also beware that some lines such as
```python
bodies.inertia_matrix.values[:, 6] = 0.0
```
might not be fitting anymore if you have a system with 12 (or 13?, or 14?) dofs.

**Comment by Wilton3737** [comment]
Hi @mancellin 
thanks for noting me. 
However, i still could not compute the inertia matrix as there are two bodies
![image](https://github.com/capytaine/capytaine/assets/149406844/e7618a21-de14-4c6a-921f-21641cd3cc5f)
how do i solve this 

```python
import capytaine as cpt
import numpy as np
import logging
logging.basicConfig(level=logging.INFO)
import matplotlib.pyplot as plt
mesh1 = cpt.load_mesh("buoy.stl")
mesh2 = cpt.load_mesh("plate.stl")
body1 = cpt.FloatingBody( mesh=mesh1, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, -400)),
                        center_of_mass=(0, 0, 0))
body2 = cpt.FloatingBody(mesh=mesh2, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
body1.mesh.heal_mesh()
body2.mesh.heal_mesh()
body1 = body1.translated_z(-200)
bodies = body1 + body2
bodies.rotation_center=(0, 0, 0)
bodies.center_of_mass=(0, 0, 0)
bodies = bodies.translated_z(-300)
bodies.dofs["elongate_in_z"] = np.array([(0, 0, z) for (x, y, z) in bodies.mesh.faces_centers])
dofs_divergence = {"elongate_in_z": np.ones(bodies.mesh.nb_faces)}
density = 1000.0
gravity = 9.81
bodies.hydrostatic_stiffness = bodies.compute_hydrostatic_stiffness(divergence=dofs_divergence, rho=density, g=gravity)
elongate_in_z_hs = bodies.hydrostatic_stiffness
analytical_hs = - density * gravity * (4 * bodies.volume * bodies.center_of_buoyancy[2])
print(np.isclose(elongate_in_z_hs.values[0, 0], analytical_hs))
bodies.inertia_matrix = bodies.compute_rigid_body_inertia()
print(bodies.inertia_matrix.values)
bodies.inertia_matrix.values[:, 12] = 0.0
bodies.inertia_matrix.values[12, :] = 0.0
bodies.inertia_matrix.values[12, 12] = 1000.0
bodies = bodies.immersed_part()
bodies.show_matplotlib()
import xarray as xr
from numpy import infty
omega_range = np.linspace(0.1, 6.0, 20)
list_of_problems = [
    cpt.RadiationProblem(body=bodies, radiating_dof=dof,  omega=omega)
    for dof in bodies.dofs
    for omega in omega_range
]
list_of_problems = list_of_problems + [
    cpt.DiffractionProblem(body=bodies, wave_direction=0.0, omega=omega)
    for omega in omega_range
]
solver = cpt.BEMSolver()
list_of_results = solver.solve_all(list_of_problems)
from capytaine import assemble_dataset
databuoy = cpt.assemble_dataset(list_of_results)
from capytaine.io.xarray import separate_complex_values
separate_complex_values(databuoy).to_netcdf("databuoy.nc",encoding={'radiating_dof': {'dtype': 'U'},'influenced_dof': {'dtype': 'U'}})
from capytaine.io.legacy import export_hydrostatics
export_hydrostatics("testbuoy.dat", body)

```

**Comment by mancellin** [comment]
Sorry the late answer.

At least one issue is a bug in `translated_z`:
```python
bodies.rotation_center=(0, 0, 0)
bodies = bodies.translated_z(-300)
print(bodies.rotation_center)  # (0, 0, 0, 0.0, 0.0, -300), but you should have (0, 0, -300).
```
That is the "6" causing the error you saw.

But the core issue is that hydrostatics for multiple bodies are poorly supported by Capytaine.
In general, the least worse solution is to compute the hydrostatics of each body individually before adding them together:

```python
mesh1 = cpt.load_mesh("buoy.STL")
body1 = cpt.FloatingBody(mesh=mesh1, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, -400)),
                        center_of_mass=(0, 0, 0))
body1.mesh.heal_mesh()
body1 = body1.translated_z(-200)
body1.inertia_matrix = body1.compute_rigid_body_inertia()
body1.hydrostatic_stiffness = body1.compute_hydrostatic_stiffness()

mesh2 = cpt.load_mesh("plate.STL")
body2 = cpt.FloatingBody(mesh=mesh2, dofs=cpt.rigid_body_dofs(rotation_center=(0, 0, 0)),
                        center_of_mass=(0, 0, 0))
body2.mesh.heal_mesh()
body2.inertia_matrix = body2.compute_rigid_body_inertia()
body2.hydrostatic_stiffness = body2.compute_hydrostatic_stiffness()

bodies = body1 + body2
bodies = bodies.translated_z(-300)

print(bodies.inertia_matrix.values)
print(bodies.hydrostatic_stiffness.values)
```

But in your case with a supplementary non-rigid dof, there is no straightforward way to do that.
Even if you do, I'm not sure it will be supported by `export_hydrostatics`.

**Comment by mancellin** [comment]
Also double check your mesh, because when I try to run your code it looks like this:
```python
bodies.show_matplotlib()
```
![Capture d’écran_2024-03-08_13-36-01](https://github.com/capytaine/capytaine/assets/31126826/c2dd830c-1670-4d63-ac9a-a0c2fd5fae1f)

**Comment by Wilton3737** [comment]
Hi @mancellin,
thanks for your reply. I have found a code by wecSim which is ready made and i am currently using it for my project. I am not writing my code for the moment. I will do it if i have time. so feel free to close this issue now. I will open a new one when i have time to write my own. thanks.
