### ISSUE TITLE
Simulation of 6-DOF Floating Body in a Wave Tank with 0-DOF Walls

### ISSUE THREAD

**Issue by doganbil** [capytaine/capytaine#435]
I will soon be conducting model tests in a towing tank, in order to investigate the wave diffracting characteristics of a typical sea barge. In preparation, I want to simulate my model test cases with Capytaine. The wave tank is 80 meters long, 5 meters wide, and has a water depth of approximately 2.3 meters. The model barge is located 10 meters away from the wave generator. The relevant wave field for my investigation extends approximately 5 meters behind the model barge. The model scale is 1:64. 

For this purpose, I have modeled my barge, which has 6 degrees of freedom (6-DOF), and the tank walls surrounding it, which have 0 degrees of freedom (0-DOF), in full scale, using Rhino and loaded them into Capytaine as .gdf files. I have modeled the walls so that the they extend down to the tank floor and represented the tank floor with 'water_depth' parameter when setting up radiation and diffraction problems. (It may well be that my approach of modelling the tank walls is fundamentally not accurate. In that case, I would also appreciate feedback.) After making the necessary adjustments, I combine the bodies following common Capytaine practice: all_bodies = barge + walls. 

The issue arises when Capytaine attempts to compute the radiation elevation. It requires the Response Amplitude Operator (RAO), which cannot be computed for the body wall since it doesn't have inertia and stiffness matrices in the hydrodynamical dataset.

I have considered calculating the diffraction potential of the walls and the radiation and diffraction potential of the barge separately, and superimposing them subsequently to achieve the complete wave field. However, this approach neglects the interaction between the model barge and the tank walls, specifically the diffraction of radiated waves by the model barge.

I would be grateful for any suggestions or possible solutions to this issue

Below are the (VTK) image of my model and my script:

<img width="1229" alt="Model_Barge_and_Walls" src="https://github.com/capytaine/capytaine/assets/116027509/5a7caac8-0a8f-4adb-a266-647e91a8d02b">

```python
########################################################################
# Import Packages & Functions
########################################################################
import os
import time
import logging
import numpy as np
import xarray as xr
import capytaine as cpt
from   capytaine.io.xarray import separate_complex_values,merge_complex_values
from   capytaine.bem.airy_waves import airy_waves_free_surface_elevation

# Info for running calculation steps
logging.basicConfig(level=logging.INFO, format='%(levelname)-8s: %(message)s')
start = time.time()

# Wave and free surface Parameters
xmin = -160
xmax = 160
ymin = -100
ymax = 350
nx   = 150
ny   = 228
rho  = 1000    # kg/m^3
wdepth = 150   # m
wave_direction = np.pi / 2
periods = np.linspace(3,16,27)  
omega = (2 * np.pi) / periods[9] # 8sec

# Free surface mesh
x  = np.linspace(xmin, xmax, nx, endpoint=True)
y  = np.linspace(ymin, ymax, ny, endpoint=True)
fs = cpt.FreeSurface(x_range=(xmin, xmax), y_range=(ymin, ymax), nx=nx, ny=ny, name = 'free_surface')

# Barge Parameters
lcg  = 1.025   # m
tcg  = 0       # m
vcg  = 8.6367  # m
L    = 122     # m 
B    = 32      # m 
D    = 17.6    # m
T    = 6       # m draft 
m    = 21183800  # kg  
Awl  = 3867.64   # m^2
GMT  = 7.585     # m 
GML  = 204       # m
x_wp = 60.17135  # -0.563784058
Rx   = 14.05     # np.sqrt((B**2 + D**2)/12)
Ry   = 35        # np.sqrt((L**2 + D**2)/12)
Rz   = 40        # np.sqrt((L**2 + B**2)/12) 
radii = np.array([Rx,Ry,Rz])

# Load Barge 
barge = cpt.FloatingBody.from_file("barge_mesh_6m.gdf", file_format="wamit", name="barge")
barge.keep_immersed_part()
barge.add_all_rigid_body_dofs()
barge.center_of_mass = (lcg,tcg,vcg-T)

# Load tank walls 
walls = cpt.FloatingBody.from_file("walls.gdf", file_format="wamit", name="walls")
walls.keep_immersed_part()
walls.center_of_mass = (0,0,0)
# walls.hydrostatic_stiffness = walls.compute_hydrostatic_stiffness(rho=rho)
# walls.inertia_matrix        = walls.compute_rigid_body_inertia(rho=rho)

# Modify mass and inertia matrices
def stiffness_matrix(m,GMT,GML,A_wp,x_wp=0.,y_wp=0.,rho=1000.,g=9.81):
    return np.array([[0., 0.,  0.,               0.,                    0.,                   0.],
                    [0., 0.,  0.,               0.,                    0.,                   0.],
                    [0., 0.,  rho*g*A_wp,       rho*g*A_wp*y_wp,      -rho*g*A_wp*x_wp,      0.],
                    [0., 0.,  rho*g*A_wp*y_wp,  m*g*GMT,              -rho*g*A_wp*x_wp*y_wp, 0.],
                    [0., 0., -rho*g*A_wp*x_wp, -rho*g*A_wp*x_wp*y_wp,  m*g*GML,              0.],
                    [0., 0.,  0.,               0.,                    0.,                   0.]])

def mass_matrix(m,radii,x=0.,y=0.):
    M = np.eye(6)*m
    M[3:,3:] *= radii**2
    
    # Rotation about global origin. Adjust mass matrix accordingly:
    M[3,3] += m*x**2 
    M[4,4] += m*y**2 
    
    return M

K = stiffness_matrix(m,GMT,GML,Awl,x_wp=x_wp)
M = mass_matrix(m,radii) 

barge.hydrostatic_stiffness = xr.DataArray(K, dims=['influenced_dof', 'radiating_dof'],
                                                coords={'influenced_dof': list(barge.dofs),'radiating_dof': list(barge.dofs)},
                                                name='hydrostatic_stiffness_matrix')

barge.inertia_matrix = xr.DataArray(M, dims=['influenced_dof', 'radiating_dof'],
                                        coords={'influenced_dof': list(barge.dofs),'radiating_dof': list(barge.dofs)},
                                        name='inertia_matrix')

# Join bodies
all_bodies = barge + walls

# Solver 
bem_solver = cpt.BEMSolver()

# Problem Setup
radiation_problems = [cpt.RadiationProblem(omega=omega, body=all_bodies, water_depth=wdepth,radiating_dof=dof) for dof in all_bodies.dofs]
diffraction_problem = cpt.DiffractionProblem(omega=omega, body=all_bodies, water_depth=wdepth, wave_direction=wave_direction)     

# Solve Problem
radiation_results = bem_solver.solve_all(radiation_problems)
diffraction_result = bem_solver.solve(diffraction_problem)

# Postprocessing
dataset = cpt.assemble_dataset(radiation_results + [diffraction_result])
rao = cpt.post_pro.rao(dataset, wave_direction=wave_direction)

# Compute individual wave patterns:
incoming_waves_elevation = airy_waves_free_surface_elevation(fs.mesh,diffraction_result) 
diffraction_elevation = bem_solver.compute_free_surface_elevation(fs.mesh,diffraction_result) 
radiation_elevations_per_dof = {res.radiating_dof: bem_solver.compute_free_surface_elevation(fs.mesh, res) for res in radiation_results}
radiation_elevation = sum(rao.sel(omega=omega, radiating_dof=dof).data * radiation_elevations_per_dof[dof] for dof in all_bodies.dofs)

# Superpositioned complete wave field
wave_field_unit_amplitude = incoming_waves_elevation + diffraction_elevation + radiation_elevation
wave_field = wave_field_unit_amplitude.reshape((nx, ny)).T

np.savetxt('incoming_T8sec.txt',incoming_waves_elevation, delimiter=',')
np.savetxt('diffraction_T8sec.txt',diffraction_elevation, delimiter=',')
np.savetxt('radiation_T8sec.txt',radiation_elevation,     delimiter=',') 

end = time.time()
print('Elapsed time to calculate hydrodynamical dataset is:', (end - start) / 60, 'minutes')
```

**Comment by mancellin** [comment]
> (It may well be that my approach of modelling the tank walls is fundamentally not accurate. In that case, I would also appreciate feedback.)

I have no experience simulating this kind of problem, nor comparing them with experimental data, but your approach seems reasonable to me.

> The issue arises when Capytaine attempts to compute the radiation elevation. It requires the Response Amplitude Operator (RAO), which cannot be computed for the body wall since it doesn't have inertia and stiffness matrices in the hydrodynamical dataset.

Your whole system has six degrees of freedom and you should be able to compute the RAO for each of them. The fact that your mesh has some extra distant non-moving parts will affect the added mass, radiation damping and excitation force for each of the six dofs, that's all. There is no RAO for other degrees of freedom that would be related to the walls, but you know how they move already (they don't).
