### ISSUE TITLE
Zero Stiffness in RM5 hydrostatics computation

### ISSUE THREAD

**Issue by oliviavitale35** [capytaine/capytaine#437]
Hi Matthieu,

I am trying to model RM5 (as a simple flap) using 
meshes.predefined.rectangles.mesh_parallelepiped
when I am computing my hydrostatics, i get zero or very close to zero values for my hydrostatic stiffness. This is how I am defining my mesh:

```python
# defining mesh
body = cpt.FloatingBody(cpt.meshes.predefined.rectangles.mesh_parallelepiped(size=(wi, th, h), resolution=(nw, nt, nh), center=(x, y, z), name='rect'))
body.keep_immersed_part()
body.center_of_mass=(0,0,cog)
dofs = body.add_all_rigid_body_dofs()
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()
```

with the following input parameters:

```python
# initializing parameters
wi = 25         # width of flap [m]
th = 1          # thickness of flap [m]
h = 19          # height of flap [m], draft = 16 m
x = 0
y = 0
z = -16         # draft [m]
cog = -11.4     # center of gravity [m]
nw = 40         # number of panels along width (x)
nt = 10          # number of panels along thickness (y)
nh = 40         # number of panels along height (z)
```

I tried adjusting the thickness and number of panels, but that didn't seem to help. I haven't had this problem when modeling cylinders and spheres, so I wonder if I'm missing something in my body definition.

thanks,
olivia

**Comment by mancellin** [comment]
I don't see anything wrong with your code.
Indeed most of your stiffness coefficients are zero, except for roll-roll and pitch-pitch.

I don't have in mind the theory behind these coefficients right now, it might be the expected result for this geometry.

**Comment by marcogambarini** [comment]
Hi, sorry for chiming in, could the reason be that the body is completely immersed?

**Comment by sdillenburg** [comment]
> Hi, sorry for chiming in, could the reason be that the body is completely immersed?

Your are completely right. 

For 16 m draft, z shoule be `z = -8`

**Comment by oliviavitale35** [comment]
actually, the height of the body is set to 19 m with a submerged portion of 16 m, so about 3 m is above the still water level. perhaps since it is almost completely submerged, the values are small?

**Comment by sdillenburg** [comment]
Your code yields:

![image](https://github.com/capytaine/capytaine/assets/45045610/3abe1234-5f09-435a-991d-c9e502a0e9ae)


I guess you want this:

![image](https://github.com/capytaine/capytaine/assets/45045610/542704c0-2352-41f3-af04-11e945f53732)

As mentioned above, you mixed up the basis of the box with its center.

```
import capytaine as cpt

wi = 25 # width of flap [m]
th = 1 # thickness of flap [m]
h = 19 # height of flap [m], draft = 16 m
x = 0
y = 0
z = -6.5 # box center [m]
cog = -11.4 # center of gravity above still water line [m]
nw = 40 # number of panels along width (x)
nt = 10 # number of panels along thickness (y)
nh = 40 # number of panels along height (z)

body = cpt.FloatingBody(cpt.meshes.predefined.rectangles.mesh_parallelepiped(size=(wi, th, h), resolution=(nw, nt, nh), center=(x, y, z), name='rect'))
body.keep_immersed_part()
body.center_of_mass=(0,0,cog)
dofs = body.add_all_rigid_body_dofs()
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()

body.show()
```

Btw, I guess you could reduce the mesh refinement in y direction. The resulting panels in the xy- and yz-plane are relatively long...

**Comment by oliviavitale35** [comment]
oh, sweet, this is super helpful. thank you all for your help and input :)
