### ISSUE TITLE
Multibody problem - how to get the added mass and radiation damping matrices right

### ISSUE THREAD

**Issue by arredondo-galeana** [capytaine/capytaine#438]
Dear Capytaine team,

I am trying to solve the hydrodynamic problem for a multi-body barge type structure. The barge is divided into 6 modules which I concatenate together through the join bodies command. When I try to save the added mass and radiation damping matrices, I expect a 36 x 36 dataset, but somehow I end up with a 42 x 42 dataset.

I attach a screenshot of the geometry and the txt code that I am using to solve the hydrodynamic problem.

Do you spot anything wrong in my lines of code?

Thanks and regards,

Abel

Code:
[Code_multibody_Abel.txt](https://github.com/capytaine/capytaine/files/13514993/Code_multibody_Abel.txt)

Geometry:
![Screenshot 2023-11-30 at 15 54 07](https://github.com/capytaine/capytaine/assets/69305363/4323316a-0676-4edf-8422-07ba43e45009)

**Comment by arredondo-galeana** [comment]
Thanks for having a look at this Matthieu. I think the code is very relevant for what I am trying to do. 
I'll reach out to you again if I get stuck.

Kind regards,

Abel

**Comment by arredondo-galeana** [comment]
Hi Matthieu,

I've been testing the hinge barge code for a bit now. I happen to have an old version of Capytaine installed so I managed to run the code quickly. Although I will attempt to get the code running in the latest version of captain soon.

I would like to generate a power matrix for the device using your code, but I have a few questions that I would be grateful if you could have a look at. Here they are:

1) In the power computation equation P=0.5*Kpto*| i*\omega X(\omega) |^2, how can I incorporate the effect of the width of the platform? Is it reasonable to normalise P with the width of the simulation , i.e. P / 0.4 m ? and then use this normalised value to compute P for a width of 58 m?
2) In the equation above, are the units of P in Watts or in Joules? What are the units of Kpto?
3) How can I determine Kpto? Is there any useful reference to determine this value? 
4) Do you have a published citable reference for the work you did on hinged rafts? or Should I cite your GitHub repository directly?

Thanks for your help,

Abel

**Comment by mancellin** [comment]
The initial motivation for this code was a collaboration that gave rise to the following paper:
https://www.sciencedirect.com/science/article/pii/S0960148121003049
https://www.mdpi.com/1996-1073/13/19/5129

My own contribution was never published (unless you consider Capytaine itself, which is a kind of side-product of that work). The consequence of that is that this bit of code is poorly documented and barely validated.

The notations are likely the same as in the paper above and the reference therein (such as https://ieeexplore.ieee.org/document/7514964), but I don't have the time right now to delve more into this to answer your questions.

**Comment by arredondo-galeana** [comment]
Thanks for the useful references Matthieu.

I'll keep working with these references and the code you shared with me. I am also trying to go from the frequency domain to time domain to solve the equation of motion of the hinged raft converter. Hopefully, I can reach out to you sometime next year in case there are some other Capytaine related questions.

Kind regards and happy holidays,

Abel

**Comment by arredondo-galeana** [comment]
Dear Matthieu,

I am trying to reproduce some multi-body results I obtained with Capytaine 1.3 some time ago, now with version Capytaine 2.2 but I am running into some trouble. 

So I decided to simplify the problem to one barge as a first step. If I run the same code (below of this paragraph) in both versions of Capytaine, my total excitation forces, added mass and radiation damping matrices seem to be different. The only warning I get in Capytaine 2.2, which I did not use to get before is: “WARNING The rotation dof Roll has been initialized around the origin of the domain (0, 0, 0).” 

#Capytaine 1.3 (Code also run in Capytaine 2.2)
length_m = 14.5;
center = 7.25;
gap = .01;

# Define the first body 
block1 = cpt.RectangularParallelepiped(    
    size=(length_m, 58, 5.2),resolution=(20, 40, 10),  # Dimensions
    center=(7.25, 29, 1.6),#=6
    top=True, bottom=True,
    reflection_symmetry=False,
    translational_symmetry=False,
)
block1.add_all_rigid_body_dofs()

So, after getting the previous warning, I tried in Capytaine 2.2 changing the center of the barge and using mesh_parallelepiped, as follows:

#Capytaine 2.2
total_length = 174;
number_panels = 12;
length_panel = total_length/number_panels;
center = length_panel/2;
shift = .01

# Define the first body
pontoon1 = cpt.mesh_parallelepiped(
        size=(length_panel, 58, 5.2), center=(7.25, 29, 1.6), 
        resolution=(40, 20, 10),  
        reflection_symmetry=False,
        translation_symmetry=False,
    )
block1 = cpt.FloatingBody(mesh=pontoon1,dofs=cpt.rigid_body_dofs(rotation_center=(7.25, 29, 1.6)),center_of_mass=(7.25, 29, 1.6)).immersed_part()
block1.add_all_rigid_body_dofs() 

When I run the BEM solver to generate the total forces through **data['Froude_Krylov_force']+data ['diffraction_force']** I seem to get different results. 

1)	Is there anything obvious that I might be doing wrong in Capytaine 2.2?
2)	Why does Capytaine 1.3 yields different results than Capytaine 2.2 when I use the same code that I had in Capytaine 1.3? For my multibody problem Capytaine 1.3 seemed to be working ok. I suspect this is all to do with frame of references, but I do not understand the problem at the moment.
3)	I am also trying to benchmark my data with solver Sesam for the multibody setup, but would like to get the single body setup running fine first. Any tip/suggestion is greatly appreciated.

Thanks and regards,

Abel

**Comment by mancellin** [comment]
The main difference that comes to my mind between 1.3 and 2.2 is the accuracy of the Green function.
If the 2.2 results look like the mesh-converged results of 1.3, it is all normal.

I'll investigate this a bit more when I have some time (the changes in Python packaging ecosystem make 1.3 surprisingly difficult to install on a recent Python version).

**Comment by mancellin** [comment]
I might have figured it out.

In older version of Capytaine, 
```python
body = cpt.RectangularParallelepiped(center=(...), ...)
body.add_all_rigid_body_dofs()
```
would use the center of the geometrical shape for the definition of the rotation dofs.

I'm trying to move away from this kind of barely-documented implicit behavior and I'm now suggesting a more explicit formulation in the documentation, in which the `center` of the mesh is not silently reused later:
```python
mesh = cpt.mesh_parallelepiped(center=(...))
body = cpt.FloatingBody(mesh, dofs=cpt.rigid_body_dofs(rotation_center=(...))
```

While doing so, I must have inadvertently broken the old implicit behavior, hence the `WARNING The rotation dof Roll has been initialized around the origin of the domain (0, 0, 0).`
You can fix it by explicitly defining the `rotation_center` as in the example below.

So
```python
import capytaine as cpt
import xarray as xr

body = cpt.RectangularParallelepiped(
    size=(14.5, 58, 5.2),
    resolution=(20, 40, 10),
    center=(7.25, 29, 1.6),
    top=True,
    bottom=True,
    reflection_symmetry=False,
    translational_symmetry=False,
)
body.rotation_center = (7.25, 29, 1.6)
body.add_all_rigid_body_dofs()
body.keep_immersed_part()

test_matrix = xr.Dataset(coords={"omega": [2.0], "wave_direction": [0.0]})
ds = cpt.BEMSolver().fill_dataset(test_matrix, [body])
print(ds.diffraction_force.values)
```

gives on 2.2

```
[[[ 8.34441560e+05-4.37281610e+05j -4.84751245e-06-7.09835779e-07j
    2.39099726e+06-4.01537208e+05j -3.22377309e-04-1.24563463e-04j
    2.47371991e+06-1.44358983e+07j -1.28549291e-04+6.12894394e-04j]]]
```
and on 1.3
```
[[[ 8.39880670e+05-4.34931020e+05j -4.07776806e-01+4.73079133e-01j
    2.38820405e+06-3.87381850e+05j -5.81550097e+01-7.07052848e+01j
    2.45692563e+06-1.43894274e+07j  6.27054574e-04-1.57715755e-03j]]]
```

while the newer formulation
```python
import capytaine as cpt
import xarray as xr

mesh = cpt.mesh_parallelepiped(
    size=(14.5, 58, 5.2),
    resolution=(20, 40, 10),
    center=(7.25, 29, 1.6),
)
body = cpt.FloatingBody(
  mesh.immersed_part(),
  dofs=cpt.rigid_body_dofs(rotation_center=(7.25, 29, 1.6))
)

test_matrix = xr.Dataset(coords={"omega": [2.0], "wave_direction": [0.0]})
ds = cpt.BEMSolver().fill_dataset(test_matrix, [body])
print(ds.diffraction_force.values)
```
gives the same thing on 2.2:
```
[[[ 8.34441560e+05-4.37281610e+05j -4.84716502e-06-7.09770636e-07j
    2.39099726e+06-4.01537208e+05j -3.22498381e-04-1.24257524e-04j
    2.48279865e+06-1.44406213e+07j -1.28526008e-04+6.13015000e-04j]]]
```

**Comment by mancellin** [comment]
That is a bug in recent versions of `RectangularParallelepiped` (not in the other predefined shapes as it seems). That will be easy to fix for the next version, so you old code can still run the same. For new projects, consider the newer user interface.

**Comment by arredondo-galeana** [comment]
Hi Matthew thanks for clarifying something I was suspecting between version 1.3 and 2.2
I suppose now my question is:
1) Although forces 1,3, and 5 are similar between Capytaine 1.3 and 2.2, why are the forces computed for 2,4 and 6 so different? What could be the source of this discrepancy, provided that the rotation centre is now the same in 1.3 and 2.2?

Furthermore, I am looking at the added mass, radiation damping and total forces for the simple barge case in both Capytaine 1.3 and 2.2, even after adjusting the centre of rotation in Capytaine 2.2 as per your suggestion, the results that I get between the two versions of the software are significantly different. Even though I would like to upgrade to Capytaine 2.2, this discrepancy is making me stick to Capytaine 1.3, because it gives me better agreement in comparison to other potential flow solvers.
Thanks again for your time,
Abel

**Comment by mancellin** [comment]
In the results above, forces 2, 4 and 6 are $10^5$ to $10^10$ smaller than the other forces. They are basically zero with some noise, and the noise is different between 1.3 and 2.2.

If you have reference results from other solver that show a decrease in accuracy between 1.3 and 2.2, I'd be very interested in more details.

**Comment by arredondo-galeana** [comment]
Hi Matthieu,

I have rechecked my codes and I had an error in the dimensions of my barge. So it seems now that both versions of Capytaine (1.3 and 2.2) agree well when I redefine my rotational centre in Capytaine 2.2. So this is great news! I will now move to the multi-body problem and try to use Capytaine 2.2.

Thanks for your help, 

Abel
