### ISSUE TITLE
Irregular frequencies

### ISSUE THREAD

**Issue by gpfilip** [capytaine/capytaine#44]
Hello, 
I read through the previous discussion about merging in the irregular frequency removal technique from Nemoh and am wondering if there is anything that can be done to help remove these spikes from the Capytaine results. Below is a comparison of two different resolutions of a sphere floating at the equator compared to published WAMIT results. I've been experimenting with different resolutions, frequency increments, Green function solvers, but so far no major improvements. I'd appreciate any hints, thanks! 
![image](https://user-images.githubusercontent.com/41333830/94840115-ecca3100-03e5-11eb-92e0-f82686378711.png)

**Comment by dav-og** [comment]
Hello @gpfilip 

You can find some description of the theory (and associated references) in the WAMIT manual here:

http://www.wamit.com/manualv7.3/wamit_v73manualch15.html#x20-12900015.5

As you probably gathered from the other thread, this functionality has been implemented in the latest version of NEMOH - see @izabala123 's fork:

https://github.com/izabala123/Nemoh/tree/master/Solver/Core
I can't tell you where exactly that feature is included - @mancellin might be able to point you to it.

OpenWARP also implemented irregular frequency removal functionality:

https://github.com/NREL/OpenWARP/blob/ca49c4cbde17e0cead69bd9e55a81d5c0fafe4df/source/NemohImproved/Nemoh/Solver/Core/SOLVE_BEM_IRREGULAR.f90

AFAIK Capytaine doesn't (yet!) have this functionality. But here ^ is the theory and some working examples if you want to try implementing it yourself :) ... if you need some results sooner then sometimes people apply a simple smoothing function/filter in their post-processing to 'iron out' the irregular frequencies - it only gives an approximation of the solution, but might be appropriate for your needs? Other than that, I would try using @izabala123 's NEMOH fork.

Bear in mind that your mesh needs to have a 'lid' at the waterline in order to use this feature :)

**Comment by gpfilip** [comment]
Hello @dav-og 

Thank you very much such a detailed response, this is extremely helpful! Agreed about the frequency range being quite high, this is just for stress testing at this point. The issue frequencies that I've been running into are typically in the range 2<omega<5 rad/s and the really high frequency ones are essentially neglected. 

Thanks again

**Comment by mancellin** [comment]
The only thing I can add to @dav-og's answer is that several methods have been proposed in the literature to avoid irregular frequencies. The method described in WAMIT's theory manual might not be the same as the one implemented in Nemoh or OpenWARP. Some literature review would be needed to figure out the best method to implement in Capytaine.

**Comment by YingyiLiu** [comment]
Hi guys, I happened to find this page, capytaine is a really great work!

As for the removal of irregular frequencies, modifying the Nemoh code might be a little bit difficult as it is written in an old Fortran format. Recently I just released a BEM code (HAMS) which I have been working on for a decade. In HAMS, irregular frequencies are removed with just a few discrete points on the waterplane. You may find the information here:

https://github.com/YingyiLiu/HAMS
https://www.researchgate.net/publication/341104060_HAMS_A_Frequency-Domain_Preprocessor_for_Wave-Structure_Interactions-Theory_Development_and_Application

**Comment by mancellin** [comment]
Hi @YingyiLiu 

Thank you for your message! I wish I had known about your work earlier, it looks great !

The method to remove irregular frequencies that you describe in your paper could actually be implemented in Capytaine without too much difficulties. I'll give it a try some day.

**Comment by YingyiLiu** [comment]
Hi Matthieu,

Thanks for your feedback. This actually not your mistake since I have just
released the code last October, and I guess that you started the capytaine
project much earlier.

Looking forward to your future updates! Certainly if someday you have got
time to build a python wrapper for HAMS, I will be very happy. ^ ^

Matthieu Ancellin <notifications@github.com> 于2021年2月25日周四 下午9:22写道：

**Comment by mancellin** [comment]
A quick experiment of irregular frequency removal in Capytaine, comparing `cpt` the current Capytaine result, `direct` the direct BEM solver as described in @YingyiLiu's paper and `direct_without_irr_freq` the direct solver with the irregular frequency removal.

![Figure_1](https://user-images.githubusercontent.com/31126826/110803880-f3f04780-827f-11eb-80c7-0bf6fb2a5ccb.png)

There is a small discrepancy between Capytaine indirect solver and the direct resolution around `omega=3`. I still need to figure out the relationship between the two formulations of the boundary integral problem...

Feel free to try to adapt the code below if you need irregular frequency removal in Capytaine.
Please share your results afterwards: more validation examples are needed before considering an implementation in the package.

Source code:
```python
import numpy as np
import capytaine as cpt


engine = cpt.BasicMatrixEngine()
green_function = cpt.Delhommeau()
capy_solver = cpt.BEMSolver(engine=engine, green_function=green_function)

def force(body, phi):
    # Integrate potential over body to get force
    displacement = np.sum(body.dofs["Heave"] * body.mesh.faces_normals, axis=1)
    return 1000.0 * np.sum(phi * displacement * body.mesh.faces_areas)

class PointsOnFreeSurface():
    # Points on the free surface, inside the body, to avoid irregular frequencies.
    # Saved as "faces_centers" to behave like a mesh for the Green function computation.
    def __init__(self, points):
        points = np.array(points)
        nb_points = points.shape[0]
        self.faces_centers = np.concatenate([points, np.zeros((nb_points, 1))], axis=1)
        self.faces_normals = -np.concatenate([np.zeros((nb_points, 2)), np.ones((nb_points, 1))], axis=1)


def solve_with_several_methods(body, omega, points_on_surface):
    # Capytaine
    problem = cpt.RadiationProblem(body=body, omega=omega, sea_bottom=-np.infty, radiating_dof="Heave")
    result = capy_solver.solve(problem)

    # Direct solver
    settings = dict(free_surface=0.0, sea_bottom=-np.infty, wavenumber=problem.wavenumber, green_function=green_function)
    S, K = engine.build_matrices(body.mesh, body.mesh, **settings)
    phi = np.linalg.solve(K, S @ problem.boundary_condition)
    added_mass = - np.real(force(body, phi))

    # Direct solver with overdetermined system
    S_2, K_2 = engine.build_matrices(points_on_surface, body.mesh, **settings)
    phi_2 = np.linalg.lstsq(np.vstack([K, K_2]), np.vstack([S, S_2]) @ problem.boundary_condition)[0]
    added_mass_2 = - np.real(force(body, phi_2))

    return {'cpt': result.added_masses["Heave"], 'direct': added_mass, 'direct_without_irr_freq': added_mass_2}


# Test for a floatting sphere
body = cpt.Sphere(radius=1.0, ntheta=50, nphi=50)
body.add_translation_dof(name="Heave")
body = body.keep_immersed_part()

omega_range = np.linspace(0.1, 8.0, 300)
points_on_surface = PointsOnFreeSurface(np.random.rand(100, 2) - 0.5)
data = [solve_with_several_methods(body, omega, points_on_surface) for omega in omega_range]

import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame(data)

plt.figure()
plt.plot(omega_range, df["cpt"], label="cpt")
plt.plot(omega_range, df["direct"], label="direct")
plt.plot(omega_range, df["direct_without_irr_freq"], label="direct_without_irr_freq")
plt.legend()
plt.show()

```

**Comment by YingyiLiu** [comment]
Dear Matthieu,

First congratulations on your new improvements. I can see that the green
line completely removes the irregular frequencies.

Unfortunately, it seems that the overdetermined method described in my JMSE
paper (https://www.mdpi.com/2077-1312/7/3/81) only works for the direct
method (I have tested this in my past experience). Therefore, as for the
removal of irregular frequencies in the indirect method, I recommend you
apply the "rigid lid" method described in the WAMIT theory manual:
https://www.wamit.com/Publications/tmanual.pdf. This will work fine for the
indirect method, but will introduce the additional work on evaluating
analytically the logarithmic singularity at the waterplane:
https://link.springer.com/article/10.1007/s40722-017-0080-z

Regarding the discrepancy around omega=3, I suggest you run also another
soft, e.g., HAMS (https://github.com/YingyiLiu/HAMS) for the same case, in
order to check whether the numerical results of the direct method is the
same or not.

Best regards,
Yingyi


Matthieu Ancellin ***@***.***> 于2021年3月12日周五 上午12:07写道：

**Comment by YingyiLiu** [comment]
Dear Matthieu,

I just hanging out here and found my posts regarding irregular frequencies. My last post on Mar. 12, 2021 may not be clear and I want to add a supplement here. By saying "direct method" I meant the hybrid source & dipole boundary integral equation method, and by saying "indirect method" I meant the source-only boundary integral equation method. The over-determined boundary integral equation & least-squares method described in my JMSE paper for removing irregular frequencies only works well for the "direct method".

If you are applying the "indirect method",  a good way (probably the only effective one at the moment) is to use the "rigid lid method", also named as "extended boundary integral equation method", as included in WAMIT.

Best regards,
Yingyi

**Comment by mancellin** [comment]
Dear Yingyi,

Thank you for your message. I'm starting to actively develop Capytaine again, so the day I'll be tackling irregular frequencies is getting close. Your pointers will be very useful.

Just for clarification on the definition of direct and indirect solver: in my understanding the main difference is that in one case (direct as in HAMS) we solve something like
```
potential = K^{-1} * S * velocity_boundary_condition
```
while in the other case (indirect as in Nemoh and Capytaine), we solve something like
```
potential = S * K^{-1} * velocity_boundary_condition
```
where `S` is a matrix of integrals of the Green function and `K` a matrix of integrals of the derivative of the Green function (+ identity).
It has consequences on how to model dipole, but I wouldn't make that the main distinction between the two.
Would you agree with that?

Cheers,
Matthieu

**Comment by mancellin** [comment]
Actually, the code sample I posted above might be wrong, as well as some of my comments.
The matrices of the 'direct' method are actually not exactly the same as the one of the 'indirect' method. I'll come back and fix that example code when my understanding of the subtlety is better.

**Comment by SoundsSerious** [comment]
Hello, I am running a test case (RM3) and having trouble with both irregular frequencies and matching the added mass / damping results. I am quite new to this field of study but it seems this is quite a common issue amongst different BEM tools.

This test case (RM3) seems to be quite prevalent in the community and I think could be a good way standardize the results across different tools, also providing a basis of comparison as how to actually achieve the result wrt things like mesh quality, inputs ect.

I see NEHMO struggles a bit with this, there has been some discussion in WEC-SIM as to how to align results 
https://github.com/WEC-Sim/WEC-Sim/issues/330
https://github.com/WEC-Sim/WEC-Sim/files/4073845/NEMOH.Issue330.pdf

My own attempts to recreate this added mass distribution look nothing like the heave added mass from this issue. I am still trying to rule out my own stupidity but I've varied a number of things like mesh quality and library inputs however that didn't really alter the results significantly.

![IssueWithCapytaineIrregularFrequency](https://github.com/capytaine/capytaine/assets/10334493/f0dc86f6-d220-48b1-aa56-557dae86fe8f)

**Comment by SoundsSerious** [comment]
Looking through the examples again and some of the literature regarding `lid` based irregular frequency removal I thought it would be a good idea to use the `immersed_part()` vs simply only modeling below the water line (as above). I didn't realize this function had any substantial purpose other than simulating `in-domain` it seems this is a critical feature for near cross boundary-surface interaction. Perhaps it should always be run?

This seems to have generally improved the answer to seem reminiscent on the shape and order of magnitude toward the consensus `RM3` result. However i do still see plenty of irregular frequencies here, as per the WecSim issue 330 I think it may due to my mesh which is tri based (from wec-sim repo) however the mesh they show is quad. 

![IssueWithCapytaineIrregularFrequency](https://github.com/capytaine/capytaine/assets/10334493/b629e7c0-c648-40d4-b880-6921d5aed3a5)

**Comment by mancellin** [comment]
Irregular frequencies are high on my todo-list and should be addressed in the upcoming months.

Beside irregular frequencies, I expect Capytaine and Nemoh to struggle with the thin plate as discussed in [Sheng et al.](https://www.sciencedirect.com/science/article/pii/S0029801822003183)

> I thought it would be a good idea to use the immersed_part() vs simply only modeling below the water line (as above)
> [...]
> This seems to have generally improved the answer to seem reminiscent on the shape and order of magnitude toward the consensus RM3 result.

That is unexpected. `immersed_part()` should just clip the mesh at $z=0$. So if your mesh was already in the $z < 0$ domain, it should not have any effect.

**Comment by SoundsSerious** [comment]
Thanks that is great info. I think my understanding from that paper is that some of the Green Function lookups are faster but can cause accuracy issue in cases like this  with high discontinuity, or high interaction as in close-in interactions. I could be wrong on this since I think I need alot more experience to really understand this.

Regarding my mesh, my code translated the top surface to exactly z=0 so maybe this is an edge case. When I clip the mesh with `immersed_part()` and render via `show()` this is what my mesh look like. I did find that if z is positive and close to zero the clipping with `immersed_part()` doesn't fully work however I think its a better practice to full model out of the water and use clipping as nessicary.
![image](https://github.com/capytaine/capytaine/assets/10334493/e502fb73-8f15-49cd-95cc-ade62cba5028)

**Comment by mancellin** [comment]
> I think my understanding from that paper is that some of the Green Function lookups are faster but can cause accuracy issue in cases like this with high discontinuity, or high interaction as in close-in interactions

This is the hypothesis of the paper, but I'm not so sure. See also #228.

> this is what my mesh look like if clipping is applied, clearly removing the lid

Ok, you had a lid on the free surface. Currently, the solver cannot handle lids at $z=0$. Although if I did everything right, you should get a clear error message in this case.

> From the issue on wec-sim repo #330, they posted a NEHMO fortran tool to remove irregular frequencies using the top-clipped mesh

If you refer to OpenWARP, it is a fork of Nemoh that indeed had some supplementary features. But since that 2020 WEC-SIM issue, irregular frequencies removal has been implemented in the new version of Nemoh (version 3, released December 2022).

Otherwise, see also [Kelly et al.](https://mural.maynoothuniversity.ie/16316/).

> With regard to the above example results showing direct_without_irr_freq I am having trouble understanding what this code snippet does differently?

That would be a bit long to fully explain. Basically I tried to replicate the irregular frequency removal technique implemented in HAMS, but did a few things wrong.

**Comment by SoundsSerious** [comment]
I see, I suppose I am not surprised this a deep / complex issue as all numeric problems tend to end up there.

Thank you for your in-depth response, one thing that encourages me is that these effects mostly occur at practically high frequencies, large powerful waves usually occur nearer to 5-20s periods which is far below the observed `irregular frequencies` which seem to occur at 2-3 rad/s

I think perhaps with some smart filtering (as per your link) of the higher frequency result I can use these results, now accurate sans-lid, for my WEC optimization.

**Comment by SoundsSerious** [comment]
@mancellin based on the paper you've provided I have come up with an irregular frequency removal function that i hope is flexible enough to solve most irregular frequency problems with some fine tuning. I hope this is useful for anyone encountering this problem.

There is also functionality to create such plots as below, and to also add irregular freuencies (for testing!)
![RM3IrregularFrequencies_Corrected](https://github.com/capytaine/capytaine/assets/10334493/cbe38abb-cbb5-4eb0-a4b4-22f4622cb104)

```python
import random
import numpy as np
from matplotlib.pylab import *

def correct_irregular_freq(omg:np.ndarray,am:np.ndarray,doplot=False,Px = 5,DX=10,SLV=1000,SDDEV=2,add_irr_test=False,minlim=None):
    """Remove irregular frequencies and fill in gaps with a 2nd order Least Squares Fit in each gap 

    :param omega: the angular frequency or other basis dimension to organize the correction of the `am` values
    :param am: the values that potentially contain irregular frequencies to remove, the same base data is returned when `add_irr_test` is false and if the maximum absolute value of `d(am)/d(omg)` is less than the maximum of [ minlim (if input), avg(am)+STDDEV*std(am)]
    :param doplot: plot the results ad operations graphically
    :param Px: the number of points forward and back to provide an 2nd order polynomial fit through the irregular frequency gaps  
    :param SDDEV: the standard deviation to flag irregular frequencies centers
    :param SLV: a value to compare against `(d(am)/d(omg))^2` to provide a region of valid removal
    :param DX: the number of points forward and backward of an irregular frequency to remove 
    :param Px: the number of points forward and backward of a data gap to fit with Least Squares 2nd order fit.
    :param minlim: used to provide an early exit option asside from the std-deviation approch for value differences
    :param add_irr_test: will add between 1-3 irregular frequencies above omg>2 for removal testing
    """

    am2 = am.copy() 
    if add_irr_test:
        #add random irradds for testing
        vmv = am.mean()
        vst = am.std()
        ommn = omg.min()
        ommx = omg.max()
        for i in range(random.randint(1,3)):
            cp = 2+(random.random()*(ommx-2-1))
            cpix = np.argmin(abs(omg - cp))
            Ns = 21+random.choice([0,4,8,12])
            mag = (vmv+vst*random.random())/cp
            xb = np.linspace(0,3.1415/2,Ns)
            Yfb = np.tan(xb)
            Yf = (Yfb/abs(Yfb).max())**0.5
            dy = mag * Yf

            #add the data modififcation!
            am2[cpix-Ns:cpix] += dy
            am2[cpix+1:cpix+Ns+1] -= dy[::-1]


    dfam = abs(np.diff(am2))
    #2sigma outlier detection
    MV = dfam.mean()
    ST = dfam.std()
    LIM = MV+ST*SDDEV

    #Apply floor for difference checking
    if minlim is not None:
        LIM = max(minlim,LIM)


    #Rebase Diff Fwd+Bck
    ddx = np.array([0]+dfam.tolist())*0.5+np.array(dfam.tolist()+[0])*0.5
    FiltCrit = ddx**2
    idx = ddx >= LIM #boolean greater than man
    if not any(idx):
        return am2

    #make indexs
    idxx = np.argwhere(idx).flatten()
    idxdif = np.array(np.diff(idxx).tolist())
    idxgroup = np.array([0]+np.argwhere(idxdif > 1).flatten().tolist()+[idxx.size-1])
    irr_groups = [(f,l) for f,l in zip(idxgroup[:-1],idxgroup[1:]) if not abs(f-l)==1]


    if doplot:
        fig,ax = subplots()
        print(idxx)
        print(idxdif)
        print(irr_groups)        
        ax.plot(omg,am,'k--')
        ax.plot(omg,am2)

    am_new = am2.copy()
    rmv = np.zeros(am2.shape)
    groups={}
    for i,(irdxf,irdxl) in enumerate(irr_groups):

        idme = idxx[irdxf+1:irdxl]

        if doplot:
            print(irdxf,irdxl)
            plot(omg[idme],am2[idme])

        plausable = np.arange(max(min(idme)-DX,0),min(max(idme)+DX,len(am_new)))
        high_diff = np.argwhere(FiltCrit>SLV).flatten()

        xrmvinx = np.array(sorted(set.intersection(set(plausable),set(high_diff.tolist()))))
        xrmvinx = np.arange(xrmvinx.min()-DX,xrmvinx.max()+DX)

        if doplot:
            print(f'{min(idme)}->{max(idme)} nan: {min(xrmvinx)} -> {max(xrmvinx)}')
        am_new[xrmvinx] = np.nan
        rmv[xrmvinx] = 1.

        groups[i] = {'idb':idme,'xfinal':xrmvinx}

    amfix = am_new.copy()
    fixinx = np.argwhere(np.isnan(amfix)).flatten()
    fixsplt = np.argwhere(diff(fixinx)> 1).flatten().tolist()
    fixgrp = np.array([0]+[b+i for b in fixsplt for i in [0,1]]+[len(fixinx)-1])
    fix_groups = [(fixinx[f],fixinx[l]) for f,l in zip(fixgrp[:-1],fixgrp[1:]) if not abs(f-l)==1]

    Nl = len(amfix)-1
    for fm,fx in fix_groups:

        inx = np.arange(max(fm-Px,0),min(fx+Px,Nl)+0.1,1)
        inxfil = np.arange(max(fm,0),min(fx,Nl)+0.1,1,dtype=int)

        xb = omg[inx]
        yb = am_new[inx]

        interval = ~np.isnan(yb)
        x = xb[interval]
        y = yb[interval]

        z = np.polyfit(x,y,2)
        p = np.poly1d(z)

        xfill = xb[~interval]
        #dxdif =np.diff(xfill)
        # assert len(set(dxdif))==1,f'bad diff: {set(dxdif)}'
        yfill = p(xfill)

        if doplot:
            ax.scatter(x,y,alpha=0.1)
            ax.plot(xfill,yfill)

        amfix[inxfil] = yfill

    if doplot:
        ax.plot(omg,am_new,alpha=0.2,label='irr removed')
        ax.plot(omg,am2,alpha=0.1,label='base data')
        ax.plot(omg,amfix,'k--',label='corrected')
        ax.plot(omg,rmv*1000,label='rmv')
        ax.plot(omg,(FiltCrit>SLV)*1000,label='crit')
        ax.legend()

    return amfix

```
