### ISSUE TITLE
Free Surface Panel Modeling for Irregular Frequencies / Resonance | NEHMO's Commit 103 

### ISSUE THREAD

**Issue by SoundsSerious** [capytaine/capytaine#449]
I currently have a case where I am studying a body that is designed to be fairly reactive at the water line for wave energy capture in a study with varying water line depth.

I am trying to isolate the issues that I am seeing in the results, with fairly severe oscillations some of which I believe to be internal resonance and some of which I believe to be irregular frequencies. I am wondering if these are physical or not. 

Refering to #20 pulling in Nehmo 103 to model free surface cells, this seems somewhat doable, and seems like it would be well worth it to remove internal resonance. is this on Capytaine's radar?
https://github.com/LHEEA/Nemoh/compare/master...irregular_frequencies

As far as my particular case I am attaching a couple PDF's of results with my attempts to filter the results. The `raw` is the direct result for the `Heave radiating-dof` against multiple `influenced-dofs`. 
[DetailedRes_added_mass.pdf](https://github.com/capytaine/capytaine/files/13812875/DetailedRes_added_mass.pdf)
[DetailedRes_diffraction_force.pdf](https://github.com/capytaine/capytaine/files/13812876/DetailedRes_diffraction_force.pdf)
[DetailedRes_Froude_Krylov_force.pdf](https://github.com/capytaine/capytaine/files/13812877/DetailedRes_Froude_Krylov_force.pdf)
[DetailedRes_radiation_damping.pdf](https://github.com/capytaine/capytaine/files/13812879/DetailedRes_radiation_damping.pdf)

**Comment by SoundsSerious** [comment]
And likewise here is the mesh, Z=0 means the bottom-most surface is on the waterline
![Pasted image 20231228204816](https://github.com/capytaine/capytaine/assets/10334493/010572df-2f5d-4df5-be00-6a88906996c3)

**Comment by mancellin** [comment]
> is this on Capytaine's radar?

Yes, very much. It is actually the point of the WIP PR #419 to support panels on the free surface for irregular frequencies removal. I'm trying to have a slightly more elegant and robust implementation than Nemoh, while keeping Nemoh's implementation as plan B. The target is to have irregular frequencies removal before the end of February.

> And likewise here is the mesh, Z=0 means the bottom-most surface is on the waterline

I'm struggling to understand your mesh and your results.
Is the filtering related to the algorithm you posted in https://github.com/capytaine/capytaine/issues/44#issuecomment-1714854805?
An half-ellipsoid should not have such messy results.
Are you sure the mesh is only a 2D surface mesh and not a 3D volume mesh?

**Comment by SoundsSerious** [comment]
Ah that is great,  hopefully I can be one of the first to test it!

Regarding the mesh I believe it is surface only, I am showing this cross section result from gmsh because its a picture I had on hand. The mesh used directly was surface only, as shown here with the Immersed Body in use at z=-4.5m.
![image](https://github.com/capytaine/capytaine/assets/10334493/76b10ffc-5dcd-4f6b-90cb-fc045bd6373b)


The filtering algorithm works well for more typical irregular frequency issues, large spikes around the mean value but I am not sure what to make of the oscillations in the results.

I've specifically designed this body to be resonant with various wave periods so I am wondering if that is the cause of the large oscillations around 0. I'm attaching a condensed report which shows some trends better but can still look confusing. One thing that makes me think the results are generally valid is that there is a large drop in added mass and damping at certain frequencies in the Heave-Heave case as designed. 
[z_lvl_report.pdf](https://github.com/capytaine/capytaine/files/13822595/z_lvl_report.pdf)


The possible hypotheses would be:
1. BEM is said to not be well suited for highly reactive bodies or large motion, and thus these results are a non physical symptom of using a tool outside its domain.
2. Irregular frequencies are causing issues with the more individual spikes
3. Internal resonance of the body causes extra noise without internal damping structure, ie resonating internally.
4. Results are valid and parameters oscillations are real due to external resonance (minus some irregular frequencies)

I think 1 is probably likely, but I don't think it would completely invalidate results, perhaps it is aggravating issues.
2/3 I'm not sure of the distinction however Would love to test #419 as a use case here! I can only support 4 by testing 2&3 I suppose.

Thanks for your time and consideration in helping me debug this! I was expecting the results to be relatively straightforward since  I was able to match the `Reference Model 3` results with captaine as per #44

**Comment by SoundsSerious** [comment]
Thats interesting, thanks for explaining a bit more about typical BEM behavior.

Yes your description is accurate, The geometry is designed to resonate with small high frequency waves or large waves by adjusting the water line and thus natural frequency while optimizing spar-bouy stability, thus the wacky shape with the hole in the center.

I performed quite a few mesh studies but found my results to be nearly identical, although the sudden spikes in the signals adjusted which I would attribute to irregular frequencies. In general the finer the mesh the better the result as one would expect.

I didn't observe the large oscillations from positive to negative to be abated with mesh size, so I'm thinking that could be internal resonance, perhaps this is exacerbated by the focused shape.

I'd love to test the new build when you think its ready!

**Comment by SoundsSerious** [comment]
@mancellin congrats of the release of Capytaine 2.2. Its working well for me and is helping with the above issues.

The data I'm getting with this case seems far more reliable now. Here i'm showing medium+ resolution lid cases with dots, lower resolution lifestyles represent lower mesh quality.
![Bouy1_capytain2 2_test](https://github.com/user-attachments/assets/78b6aed9-b4b4-491e-8664-bcb5c073ac0f)

There's still a few jumps and bumps but It seems promising! 

We just got ran through our first test regime on our new [open-source wave tank] (https://github.com/neptunyalabs/wavetankOS/tree/pre-public-release) build. This should let us know how closely we match up to what Capytaine thinks is right. 

Thanks again for all your help!
