### ISSUE TITLE
Accuracy of radiation results for a range of sphere waterlines

### ISSUE THREAD

**Issue by gpfilip** [capytaine/capytaine#45]
Hello again, 

I'm trying to determine how accurate the radiation problem results are for a sphere of R=1m that is translated up (+z) and down (-z) to change its waterline. The radiation damping as a function of z/R between 0.3 and 0.8 is shown below for a series of sphere refinement levels and frequency range refinements. In this z/R range, the waterline is above the sphere's equator. 

0 < omega < 16 with 100 increments:
![image](https://user-images.githubusercontent.com/41333830/95335222-22a36580-087d-11eb-83ae-74328edb34e5.png)

0 < omega < 10 with 200 increments:
![image](https://user-images.githubusercontent.com/41333830/95336378-9e51e200-087e-11eb-9b5f-d29241177f8a.png)

0 < omega < 16 with 100 increments, double the ntheta and nphi refinement: 
![image](https://user-images.githubusercontent.com/41333830/95335692-b412d780-087d-11eb-89c2-75f9a7a33a6b.png)

0 < omega < 16 with 100 increments, double the ntheta and nphi refinement again: 
![image](https://user-images.githubusercontent.com/41333830/95336972-52ec0380-087f-11eb-8a7b-9ffdba189ff1.png)

Overall, the solution doesn't seem to change much with the omega and paneling refinement. 

One of my concerns is the double-peaked damping in particular for z/R=0.4 to 0.7. Are the secondary peaks at omegas around 4.5 expected? It is strange to me that the damping would have a first peak at lower frequencies followed by zero damping at some higher non-zero frequency which are then followed by higher damping at higher frequencies. It seems that the secondary peaks are affected by the panel resolution much more than the primary low frequency peaks which leads me to believe that the secondary peaks are a numerical issue, but that may not be true especially since as the waterline moves up higher (z/R=0.8 for example), the first peaks at low frequencies disappear and the higher frequency response dominates without any secondary peaks present (ignoring the irregular frequencies). 

When the waterline is lowered below the equator (negative z/R), the damping change seems more consistent (again ignoring the irregular frequencies and perhaps z/R=-0.9):

coarse resolution:
![image](https://user-images.githubusercontent.com/41333830/95339793-749aba00-0882-11eb-8bed-7df3070a29cc.png)

twice refined ntheta and nphi:
![image](https://user-images.githubusercontent.com/41333830/95339850-854b3000-0882-11eb-8d61-306db3172b91.png)

The solution at the equator (z/R=0) validates very well with published WAMIT results, but I haven't been able to find a published result for various waterlines. If anyone is aware of such data, please let me know. I'd appreciate any hints, thanks!

**Comment by mancellin** [comment]
Thank you for sharing your progress in testing Capytaine's accuracy.
The solution with two maxima does not look absurd to me, but I don't have any reference solution to validate this.

@ffrancesco You mentioned in another thread that you were working on some code comparison. Can you maybe help?

**Comment by dav-og** [comment]
@gpfilip I can't point you to any published results but I could run this in WAMIT for comparison if that helps? I'd need some additional information - sphere's CoG, rho...? Maybe you could share your Capytaine model?

**Comment by gpfilip** [comment]
@dav-og that would be very helpful, thank you! i won't be able to get to the capytaine model until monday but i will be sure to share then.

**Comment by gpfilip** [comment]
hi @dav-og here is the simple capytaine setup used to generate the plots: 

[added_mass_damping_sphere_vary_depth.py.gz](https://github.com/mancellin/capytaine/files/5366758/added_mass_damping_sphere_vary_depth.py.gz)

**Comment by mancellin** [comment]
@dav-og @gpfilip Has there been any follow-up on this?
