### ISSUE TITLE
Issue with added mass and radiation damping matrices for arrays of bodies

### ISSUE THREAD

**Issue by degoeden** [capytaine/capytaine#457]
I'm working with on a wave energy converter array optimizer and have been using Capytaine to calculate my hydro coefficients. The array is built of 4 WECs of all the same geometry. Most of the time when, Capytaine returns added mass and radiation daping matrices that are symmetric. This matches our understanding of what these matrices should be when all the WECs are the same geometry. However, occasionally (and problematically because one of these designs is what the optimizer converges to) we see Capytaine return added mass and radiation matrices that are not at all symmetric, despite the array still being composed of same geometry WECs. For example, when we run a design consisting of 4 WECs all vertical cylinders, see screen shot below:  

![image](https://github.com/capytaine/capytaine/assets/118622380/1de266c3-e936-4c08-8dbb-5a3426aa682c)

Important to note that the lack of symmetry seems frequency dependent, the frequency I was using to get these results is 1.047 rad/s.

Is my understanding of what these matrices should look like incorrect? I feel confident in the way I using Capytaine, since most of time the results make sense.

Any help or advice you can provide is appreciated!

**Comment by mancellin** [comment]
Yes, I believe that the added mass and radiation damping matrices should have some symmetry properties ([not only because your bodies are similar](https://wikiwaves.org/Linear_Wave-Body_Interaction#Symmetry-reciprocity_relations)).

Could this be because of an irregular frequency or a resonance frequency that could disturb the BEM solver?

**Comment by degoeden** [comment]
Perhaps, what I found interesting though and makes me think it might be something different is that removing the second of the third WEC from the list I provided makes returns fairly symmetric matrices. 

Removed 2nd WEC: 

![image](https://github.com/capytaine/capytaine/assets/118622380/f9ba798d-4878-43ad-ac01-e7e4571383c1)

Removed 3rd WEC: 

![image](https://github.com/capytaine/capytaine/assets/118622380/f5d101ba-9639-4145-bb1b-d077b2c353cb)

Also does not get much better if I change the frequency, this is it with 0.7 rad/s:

![image](https://github.com/capytaine/capytaine/assets/118622380/8a3d2e5d-a4e4-417c-89be-045c23dcb8d1)

Over all just seems much more dependent on the location of the WECs more than the frequency, which makes me think it's something other than irregular frequencies (but I could be misunderstanding).

**Comment by KapilKhanal** [comment]
To clarify, the optimizer choses random locations so its not array in array sense. So does that mean at some configuration it is highly resonant? What happens if you include a different geometry (but for same configuration), replace one with a cylinder maybe?

**Comment by mancellin** [comment]
Could you share a short self-contained script computing the added mass of such a problematic configuration, for me to investigate?

**Comment by degoeden** [comment]
Here is the gist: [https://gist.github.com/degoeden/8fc63208370c1dcdca50c95603302f0c](https://gist.github.com/degoeden/8fc63208370c1dcdca50c95603302f0c)

**Comment by mancellin** [comment]
Looks like an issue with the `HierarchicalMatrixEngine`. Disabling it make the matrix almost symmetrical.

**Comment by mancellin** [comment]
The source of the problem with the `HierarchicalMatrixEngine` might be the way the bodies are grouped together.

```python
wec_array = bodies[0]
for ii in range(len(bodies)-1):
    wec_array+=bodies[ii+1]

print(wec_array.mesh.tree_view())
```
```
cylinder_0+cylinder_6+cylinder_12+cylinder_18_mesh
 ├─cylinder_0+cylinder_6+cylinder_12_mesh
 │  ├─cylinder_0+cylinder_6_mesh
 │  │  ├─cylinder_0
 │  │  └─cylinder_6
 │  └─cylinder_12
 └─cylinder_18
```
Here I believe the solver will look for an approximation of the interaction between 
- cylinder_0 and cylinder_6
- cylinder_0+cylinder_6 and cylinder_12
- cylinder_0+cylinder_6+cylinder_12 and cylinder_18.

Depending on how the cylinders are located, it might not make sense (e.g. when cylinder_18 is in the middle of the three others).

---

Creating the array as follows leads to a flatter structure which gives better results since the solver only tries to approximate the interaction between individual buoys.
```python
wec_array = cpt.FloatingBody.join_bodies(*bodies)

print(wec_array.mesh.tree_view())
```
```
cylinder_0+cylinder_6+cylinder_12+cylinder_18_mesh
 ├─cylinder_0
 ├─cylinder_6
 ├─cylinder_12
 └─cylinder_18
```

**Comment by mancellin** [comment]
You might be interested in the `cluster_bodies` method by @marcogambarini in #436 that would group the bodies based on their position and maybe avoid this issue.

**Comment by degoeden** [comment]
Thank you, the alternative array structure you proposed seems to be doing a good enough job for our application.
