### ISSUE TITLE
Write animation output in VTK  format

### ISSUE THREAD

**Issue by sdillenburg** [capytaine/capytaine#462]
Dear all,

I would like to visualize capytaine's VTK output with Paraview. VTK probably has a proper writer for this. Any idea where to start?
Do I just need another VTK writer? I did some research but was not able to find the correct approach to achieve this...

Any hint is appreciated. If I manage to get this working, I would prepare a corresponding PR.

Best
Simon

**Comment by mancellin** [comment]
The related pieces of code in Capytaine are:

- the `write_VT?` methods, originally written for Meshmagick:
https://github.com/capytaine/capytaine/blob/51ce1cc13c30606e2b55c8d0a742d229bc482604/capytaine/io/mesh_writers.py#L225 https://github.com/capytaine/capytaine/blob/51ce1cc13c30606e2b55c8d0a742d229bc482604/capytaine/io/mesh_writers.py#L250 https://github.com/capytaine/capytaine/blob/51ce1cc13c30606e2b55c8d0a742d229bc482604/capytaine/io/mesh_writers.py#L277

- The `Animation` class: https://github.com/capytaine/capytaine/blob/51ce1cc13c30606e2b55c8d0a742d229bc482604/capytaine/ui/vtk/animation.py#L18

---

After doing a quick research, I found this: https://www.kitware.com/how-to-write-time-dependent-data-in-vtkhdf-files/
So it seems to be supported in recent versions of Paraview, but the Python implementation does not look straightforward.

Tangentially, this example uses dedicated VTK features for time-handling (`vtkGenerateTimeSteps()`, `vtkSpatioTemporalHarmonicsAttribute()`, ...) which might be more efficient than the custom Python loop I used in the `Animation` class of Capytaine.

**Comment by sdillenburg** [comment]
Thanks. I will have a closer look at this.
