### ISSUE TITLE
Wave Elevation from Pitch Radiation

### ISSUE THREAD

**Issue by oliviavitale35** [capytaine/capytaine#466]
Hi Matthieu,

I have been trying to simulate a few bodies that operate in the Pitch dof: RM5-style flap and Pelamis-style attenuator, see meshes and mesh generation code below. The issue is plotting the wave elevation due to pitch radiation. For both bodies, a flap and horizontal cylinders, the wave elevation due to pitch is far too high, up to 10-15 when it should only get up to around 2, see code and plots below mesh generation codes. I tested all the of DOFs, and they give reasonable results. It's only pitch where I have issues. Any insights?

#### Pelamis:
<img width="613" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/f0bd219b-696a-47f8-acce-19df11e21232">

```
# initializing parameters
r = 1.75     # radius [m]
l = 29
x = -50
y = 0
nr = 20         # number of panels along radius
ntheta = 20     # number of panels in theta direction
nz = 20         # number of panels in z-direction
z = 0
w = 1.047        # frequency [rad/s]
B = 0      # wave direction [rad]

# defining mesh
body = cpt.FloatingBody(mesh=cpt.mesh_horizontal_cylinder(length=l, radius=r,center=(x,y,z),resolution=(nr,ntheta,nz),name='cyl'))
body.keep_immersed_part()
body.center_of_mass=(0,0,-1)
dofs = body.add_all_rigid_body_dofs()
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()

# create array
array = body.assemble_regular_array(30,(4,1))
array.add_all_rigid_body_dofs()
array.keep_only_dofs(dofs=['0_0__Pitch','1_0__Pitch','2_0__Pitch','3_0__Pitch'])
```

#### RM5
<img width="526" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/19c840d2-33ce-426d-8eee-85d28c04d462">

```
# initializing parameters
wi = 25         # width of flap [m]
th = 1          # thickness of flap [m]
h = 19          # height of flap [m], draft = 16 m
x = 0
y = 0
draft = 16 # m
z = 0.5*h-draft # box center [m]
cog = -11.4     # center of gravity [m]
nw = 40         # number of panels along width (x)
nt = 10          # number of panels along thickness (y)
nh = 40         # number of panels along height (z)
w = 1.047        # frequency [rad/s]
B = 0        # wave direction [rad]

# defining mesh
body = cpt.FloatingBody(cpt.meshes.predefined.rectangles.mesh_parallelepiped(size=(th, wi, h), 
                                                                             resolution=(nt, nw, nh), 
                                                                             center=(x, y, z),
                                                                             name='rect'))
body.keep_immersed_part()
body.center_of_mass=(0,0,cog)
dofs = body.add_all_rigid_body_dofs()
body.inertia_matrix = body.compute_rigid_body_inertia()
body.hydrostatic_stiffness = body.compute_hydrostatic_stiffness()
```

#### Pelamis:

```
# solving hydrodynamics
solver = cpt.BEMSolver()
diff_prob = cpt.DiffractionProblem(body=array, wave_direction=B, water_depth=depth,omega=w)
diff_result = solver.solve(diff_prob,keep_details=(True))
rad_prob = [
    cpt.RadiationProblem(body=array, radiating_dof=dof, water_depth=depth,omega=w)
    for dof in array.dofs
    ]
rad_result = solver.solve_all(rad_prob,keep_details=(True))
dataset = cpt.assemble_dataset(rad_result + [diff_result])

# post-processing
# creating mesh of free surface
x1 = int(-2*lambda_wave)
x2 = int(2*lambda_wave)
nx = int(2*lambda_wave)
y1 = int(-2*lambda_wave)
y2 = int(2*lambda_wave)
ny = int(2*lambda_wave)
grid = np.meshgrid(np.linspace(x1, x2, nx), np.linspace(y1, y2, ny))
diffraction = solver.compute_free_surface_elevation(grid, diff_result)
radiation = sum(solver.compute_free_surface_elevation(grid, rad) for rad in rad_result[:4])
Z = np.real(radiation)
X = grid[0]
Y = grid[1]
plt.pcolormesh(X, Y, Z, cmap='inferno')
```

<img width="987" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/86d55541-8454-4ea4-800c-98573d52d52b">

#### RM5

(basically the same code as pelamis)

<img width="946" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/1a40a633-ccde-4a78-b1c3-ecd8311a7ce1">

the other interesting thing is that the surge solutions show the same wave pattern, but with proper magnitudes.

**Comment by mancellin** [comment]
(Edited your message for readability, hope you don't mind.)

The radiated wave amplitude you compute are for a unit motion of the body. By default, the unit translation is 1m of amplitude. For a rotation, it is more complicated since the motion of each panel is computed through a cross product with the axis of rotation, so for a very long body some panels may be moving far more than 1m during a unit oscillation.

```python
# Amplitude of motion of panel with largest motion
np.max(np.abs(body.dofs["Surge"]))
# 1.0
np.max(np.abs(body.dofs["Pitch"]))
# 11.23
```

**Comment by oliviavitale35** [comment]
hmmm... so what does this mean for my wave elevation? do i need to normalize it some how for rotational dofs? do i need to alter the way i am computing wave elevation in rotational radiation?

**Comment by mancellin** [comment]
The whole model is linear, so if you want the elevation of the waves radiated by a body moving at 1/10th of the unit body motion amplitude, you can take 1/10th of the wave elevation you computed.

**Comment by oliviavitale35** [comment]
ahhh okay i see. thank you!

**Comment by oliviavitale35** [comment]
Hi Matthieu,

I'm questioning this methodology again, as it relates to my other question about energy balance in issue #568 
In the Capytaine cookbook, when computing radiation elevation, you multiply the radiated wave field by RAO to get the radiation due to the actual body amplitude. This makes sense to me and is how I have been computing the radiated wave field since this discussion. However, I have few more questions.

1. I am curious about whether or not the RAO should remain complex in this computation (if the phase information is required, or if the RAO is just supposed to serve as a magnitude multiplier). It makes a big difference in my OSWEC simulations. Do you have a resource you can point me to as to how this process was derived?

2. For my point absorber heave RAOs, I am getting values that violate Budal's upper bound (as it is derived for body velocity in Falnes and Kurniawan (2020) Eq. (6.69).) for frequency values 0.7 through 1.1 rad/s. I guess that's more a theory question, but it is problematic for the radiated wave fields. (I do just apply the upper bound, but I fear it shouldn't be violated in the first place).

Let me know your thoughts when you get the chance. Thank you,
Olivia

**Comment by mancellin** [comment]
> Do you have a resource you can point me to as to how this process was derived?

It seems reasonable to me that if a dof is out of phase with respect to another dof, the waves it generates should be out of phase in the same way with respect to the wave generated by the other dof.
I don't remember right away an example of this formula in the literature. I don't have my copy of Falnes and Kurniawan book nearby, but that would be the first place I would have looked.
