### ISSUE TITLE
[RFC] Irregular frequencies removal user interface

### ISSUE THREAD

**Issue by mancellin** [capytaine/capytaine#479]
Drafting what the user interface for irregular frequencies removal might look like. You comments are welcome.

## Setting a lid

The `FloatingBody` object would have a new optional argument `lid_mesh`.
It stores a mesh object (like mesh), but the mesh will be used slightly differently in the Boundary Integral Equation.

An alternative would be to do as in Nemoh version 3, where the full mesh is passed to the solver and all the panels at $z=0$ are automatically treated as lid panels. I believe I prefer the explicit version proposed here.

### Lid is in a different mesh file
```python
hull_mesh = cpt.load_mesh(...)
lid_mesh = cpt.load_mesh(...)

body = cpt.FloatingBody(mesh=hull_mesh, lid_mesh=lid_mesh, dofs=cpt.rigid_body_dofs())
```

### Lid is in the same file
```python
full_mesh = cpt.load_mesh(...)
hull_mesh, lid_mesh = full_mesh.extract_lid()

body = cpt.FloatingBody(mesh=hull_mesh, lid_mesh=lid_mesh, dofs=cpt.rigid_body_dofs())
```

Example with more parameters:
```python
hull_mesh, lid_mesh = full_mesh.extract_lid(z_range=(-1e-2, 0.0))
```

### There is no lid yet
```python
hull_mesh = cpt.load_mesh(...)
lid_mesh = hull_mesh.generate_lid()  # or hull_mesh.create_internal_lid()

body = cpt.FloatingBody(mesh=hull_mesh, lid_mesh=lid_mesh, dofs=cpt.rigid_body_dofs())
```

This is underway in #477.

Example with more parameters:
```python
lid_mesh = hull_mesh.generate_lid(z=-1e-3, faces_max_radius=hull_mesh.faces_radius.mean())
```

## Solver

The user interface to the solver does not need to be changed.
If the `body` has a `lid_mesh`, irregular frequencies removal is on, otherwise it is off.
Arguably, `with_lid(...)` and `without_lid()` methods could be implemented to add or remove the lid of an existing body, that is to enable/disable irregular frequencies removal.

```python
body = cpt.FloatingBody(mesh=hull_mesh, lid_mesh=lid_mesh, dofs=cpt.rigid_body_dofs())
problem = cpt.RadiationProblem(body=body, wavelength=10.0, radiating_dof="Heave")
solver = cpt.BEMSolver()
result = solver.solve(problem)
```

**Comment by vanditya** [comment]
This is a good structure. I like it as well. I will further implement the irregular frequency removal according to this draft

**Comment by mancellin** [comment]
## Thoughts about internals

### Adding a lid to bodies

A lot of the methods of a `FloatingBody` will be unaffected by the lid (e.g. hydrostatics).
We'll need to handle the lid in some of them such as [join_bodies](https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bodies/bodies.py#L729), [mirror](https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bodies/bodies.py#L919), [translate](https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bodies/bodies.py#L931), [rotate](https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bodies/bodies.py#L939) and maybe [show](https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bodies/bodies.py#L1000).

### Boundary condition
Once `FloatingBody` has a `lid_mesh` parameter, we can update the boundary condition defined in problems at https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bem/problems_and_results.py#L340-L343 and https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bem/problems_and_results.py#L396

Either we could make `problem.boundary_condition` be of length $n_\text{hull} + n_\text{lid}$, or we add another array `problem.lid_boundary_condition`.
The boundary condition on the lid would be zero by default.

### Solver
Then we take into account the `lid` in the solver, that is use something like
```python
if problem.body.lid_mesh is not None:
    mesh = problem.body.mesh + problem.body.lid_mesh
else:
    mesh = problem.body.mesh
```
nearby https://github.com/capytaine/capytaine/blob/bee2afd2b50c22f7efe9ec4fd4332d420e4773e3/capytaine/bem/solver.py#L108-L112
and similarly for the boundary condition.

The pressure on the lid would need to be cut off before integration on the hull mesh.

**Comment by vanditya** [comment]
In my recent update I applied some of these suggestions: 

1. The lid generation is really the suggested style below:

```
hull_mesh = cpt.load_mesh(...)
lid_mesh = hull_mesh.generate_lid()  # or hull_mesh.create_internal_lid()

body = cpt.FloatingBody(mesh=hull_mesh, lid_mesh=lid_mesh, dofs=cpt.rigid_body_dofs())
```
 see: docs/user_manual/examples/creating_lid.py 

3. The generate_lid also applies automatic function which place the lid as function of omega_max until which the irregular frequency should be removed.  The location_of_lid is in capytaine/meshes/misc_internalLid.py

```
if z == 'auto':
    z = -location_of_lid(omega_max=omega_max,
                        length=length_waterline, 
                        breadth=breadth_waterline) 
```

4. While creating the lid, the body  combine the two meshes and record the number of lid panels to indicate at which panel the boundary condition is forced to be 0 later in the solver.  Furthermore, suggestion on saving like a boolean parameter is created in  self.internal_lid. This way later in the solver it automatically solves the irregular frequency removal.

```
  if lid_mesh is not None:
      self.nb_lid_internal    = lid_mesh.nb_faces
      mesh = mesh + lid_mesh

      self.mesh = mesh
      self.internal_lid = True
  else: 
      self.internal_lid = False
```

3. In the solver not many modification is needed except specification of boundary condition to be 0.Thanks to your suggestion we combine the lid and hull at mesh level rather than at body level. The user interface is kept similar to before the modification and no need to define problems.withoutlid because information of the location of boundary is already in nb_lid _internal.  Example of the solver application is in docs/user_manual/examples/irregular_frequency_removal.py

```
  if problem.body.internal_lid: 
      LOG.info("Solve with internal lid %s.")
      nb_hull = problem.body.mesh.nb_faces - problem.body.nb_lid_internal
      problem.boundary_condition[nb_hull:] = np.zeros(problem.body.nb_lid_internal,
                                                                   dtype=complex)
```
