### ISSUE TITLE
Division by zero in OWC calculation

### ISSUE THREAD

**Issue by izabala123** [capytaine/capytaine#50]
Dear Matthieu

I wanted to ask you advice to model an OWC. When modelling enclosed geometry this error message appears: 
Error: Impossible to compute the wave part of the Green function (division by zero).
I am using Capytaine loading nemoh.cal.

![image](https://user-images.githubusercontent.com/38589221/111211823-29be6480-85cf-11eb-9008-f7f5f784b083.png)

![image](https://user-images.githubusercontent.com/38589221/111211862-3642bd00-85cf-11eb-9c74-0770b96f8d08.png)

Thank you!

**Comment by mancellin** [comment]
The problem comes probably from horizontal panels on the free surface (there is a division by z = 0).
I have on my todo list to provide a more helpful error message in this case.

**Comment by izabala123** [comment]
I understand. Is there a way to solve it, maybe meshing differently?

**Comment by mancellin** [comment]
For now: removing the panels on the free surface (the clipper of `body.keep_immersed_part()` does it IIRC) or sinking a little bit the mesh (`body.translate_z(...)`).
In the long run, it might be possible to implement a better handling of this singularity in the code (probably related to the singularity mentioned by @YingyiLiu in https://github.com/mancellin/capytaine/issues/44#issuecomment-797211251 about irregular frequencies removal).

**Comment by izabala123** [comment]
Good idea. Thank you. 
I have tried it, but I get the next output:
```
INFO:   New floating body: .\mesh\oel.dat.
INFO:   New floating body: .\mesh\oel_lid.dat.
INFO:   New floating body: .\mesh\oel.dat+.\mesh\oel_lid.dat.
WARNING:        The mesh of the body .\mesh\oel.dat+.\mesh\oel_lid.dat is not inside the domain.
Check the position of the free_surface and the sea_bottom
or use body.keep_immersed_part() to clip the mesh.
```
After these messages, it appears:
```
WARNING:        No convergence of the GMRES. Error code: 23970
```

**Comment by mancellin** [comment]
What have you tried exactly? The error message says you have panels above the free surface (or below the sea bottom).

**Comment by izabala123** [comment]
Oh true, my fault!. Now fixed. Sorry.
Unfortunately, now the error is:
```
WARNING:        No convergence of the GMRES. Error code: 23970
```
The .tec files are empty.

**Comment by mancellin** [comment]
The mesh is probably still too close from the free surface: the 1/z coefficients are huge and the linear solver (GMRES) has troubles inverting the matrix...

**Comment by izabala123** [comment]
Sorry Matthieu, I don't understand your advice. Now there are no panels out of the water or crossing the water surface. All of them end at z=0.

**Comment by mancellin** [comment]
Sorry it wasn't clear.
I'm assuming you've translated down your mesh by some very small epsilon, is that right?
Then, the computer would be able to evaluate the 1/z singularity (where z is the depth of the cell center), but the resulting 1/epsilon coefficients might still be too big to be handled correctly by the solver.

**Comment by izabala123** [comment]
Hi Matthieu. What I did was to move up just a little the upper lip, cutting it, so the final mesh of the lip is like a bathtub.

**Comment by mancellin** [comment]
Oh, ok, that is not what I thought. Then, I don't know what is happening...

**Comment by izabala123** [comment]
Here I enclose you some views and a zip with the model. It would be great if you could check it. Thank you!

![image](https://user-images.githubusercontent.com/38589221/111660580-8491cf00-880e-11eb-8dbb-0e9d4f02a77a.png)
![image](https://user-images.githubusercontent.com/38589221/111661276-2f09f200-880f-11eb-9668-0df7a42c0cf2.png)
![image](https://user-images.githubusercontent.com/38589221/111661359-40eb9500-880f-11eb-8458-7201701a45a7.png)
[OELCapy.zip](https://github.com/mancellin/capytaine/files/6165617/OELCapy.zip)

**Comment by mancellin** [comment]
Just checking in to say that I did not have time yet, but I am planning to give it a try.

**Comment by mancellin** [comment]
Coming back to this problem (better late than never...).

The code is failing because the two bodies in your simulation have overlapping panels. Solving only one or the other seems to work fine. Shrinking the lid a little bit (see code below) also avoids the GMRES errors.
There might still be other issues: the slowness of the GMRES might be due to irregular frequencies as in https://github.com/mancellin/capytaine/issues/30#issuecomment-1103892112. I did not check the soundness of the output.

<details>
<summary>Code</summary>

```python
import numpy as np
import xarray as xr
import capytaine as cpt

owc = cpt.FloatingBody.from_file("mesh/oel.dat")

lid = cpt.FloatingBody.from_file("mesh/oel_lid.dat")

# Shrinking the lid a little bit
lid.mesh.vertices = np.array([0.95, 0.95, 1.0])*(lid.mesh.vertices - np.array([15.0, 0.0, 0.0])) + np.array([15.0, 0.0, 0.0])

both = owc + lid
both.add_all_rigid_body_dofs()

test_matrix = xr.Dataset(coords={'omega': np.linspace(0.1, 8.0, 10), 'radiating_dof': list(both.dofs)})
engine = cpt.BasicMatrixEngine(
        linear_solver='direct',
        # linear_solver='gmres',
        )
ds = cpt.BEMSolver(engine=engine).fill_dataset(test_matrix, [both])

```

</details>
