### ISSUE TITLE
[capytaine-standalone] Updated with Capytaine 2.1?

### ISSUE THREAD

**Issue by babiskir** [capytaine/capytaine#504]
Is it possible to get an update standalone for Capytaine 2.1?

Cheers!

**Comment by mancellin** [comment]
Thank you for letting me know about your interest for the standalone distribution.
It has been a bit neglected by me, but if there is a demand from users I'll put it higher on my todo list.

**Comment by mancellin** [comment]
Done with https://github.com/capytaine/capytaine-standalone/releases/tag/2024.04.18.
Testing of the standalone distribution is still a bit weak, so let me know if there is any issue.
