### ISSUE TITLE
Benchmarking compute time

### ISSUE THREAD

**Issue by rebeccamccabe** [capytaine/capytaine#532]
Are there any references you can point me to which benchmark the computation time of capytaine?

It is my understanding that the time should scale with nbodies * ndof * nomega * (A * npanels^2 + B * npanels^3), where the A term is running the green's function to create the elements of the matrix, and the B term is solving the matrix. Is this a correct understanding, and any estimates for A and B on a certain machine?

**Comment by mancellin** [comment]
Yes, this is mostly correct.

However, some of the matrices are reused for several problem (e.g. same frequencies but different radiating dof).
So a more accurate estimate might be:
```
n_matrices = n_frequencies * n_water_depth
n_right_hand_side = n_frequencies * (n_bodies * n_dofs_per_bodies + n_wave_direction)
total_time = n_matrices * (A * n_panels^2 + B * n_panels^3) + * n_right_hand_side * C * n_panels^2
```
where 
- `A` stands for the computation of the Green function (faster in infinite depth),
- `B` is the for the LU decomposition of the matrix (roughly comparable to `A`)
- and `C` is for solving the linear system with the known LU decomposition (usually smaller than `A` and `B`).

(This is not taking into account the new forward speed feature, nor the parallelization of the computation.)

`A`, `B` and `C` are dependent on the CPU and RAM of the machine, and I never really tried to document their values.

**Comment by mancellin** [comment]
Yes I included both diffraction and radiation. `n_dofs` comes from radiation and `n_wave_direction` comes from diffraction.

PS: fixed a small typo with `n_water_depth` in the above post.
