### ISSUE TITLE
Duplicate point in tabulation

### ISSUE THREAD

**Issue by mancellin** [capytaine/capytaine#538]
The default tabulation in 2.1 has twice the $r=1$ point:

```python
gf = cpt.Delhommeau()

print(gf.tabulated_r_range[75:85])

# array([0.31622787, 0.42169664, 0.56234151, 0.74989446, 1.00000033,
#        1.        , 1.16638655, 1.33277311, 1.49915966, 1.66554622])
```

Found this while investigating #534, but I don't really believe it's related.

@jnvn7

**Comment by jnvn7** [comment]
@mancellin I see. I'll take a look at this.

**Comment by mancellin** [comment]
![error_of_green_function_surrogate_model](https://github.com/user-attachments/assets/c5411c96-d5fd-48c8-86d6-b9873c43f9a7)

It messes up the accuracy of the Green function near $r=1$.

**Comment by mancellin** [comment]
Not sure if related, but the indexing of the tabulation in the r direction is wrong for non-default parameters :grimacing: 

```python
import capytaine.green_functions.libs.Delhommeau_float64 as fortran_core
# nr, rmax, grid_shape = (324, 100.0, fortran_core.constants.legacy_grid)
# nr, rmax, grid_shape = (676, 100.0, fortran_core.constants.scaled_nemoh3_grid)
nr, rmax, grid_shape = (1000, 120.0, fortran_core.constants.scaled_nemoh3_grid)

r_range = fortran_core.delhommeau_integrals.default_r_spacing(nr, rmax, grid_shape)
indices = np.array([fortran_core.delhommeau_integrals.nearest_r_index(r, r_range, grid_shape) for r in r_range])
print(indices - np.arange(nr))
```

Going from $i$ to $r_i$ then back to $i$ does not give the same index at all.
