### ISSUE TITLE
Internal Lid Questions

### ISSUE THREAD

**Issue by jtgrasb** [capytaine/capytaine#578]
I am working on testing out the new functionality of the internal lid for irregular frequency removal and I am running into a few issues and would like to know the best practices here. First, I am working with the WaveBot geometry. I've attached a script to generate and mesh this geometry. 

First, I started with a mesh size factor of 0.5 and I added as lid based on the `lowest_lid_position()` function. This led to the following results (focusing on added mass, but radiation damping peaks are in same spots):
No lid: <img src="https://github.com/user-attachments/assets/e6c8520d-eab3-46f3-946c-2ac0214cafb3" width="300"> Lid: <img src="https://github.com/user-attachments/assets/6411abd7-7aef-4981-b936-9853daab9175" width="300">

The lid moves the peaks to higher frequencies but not completely out of the range. As I move the lid further from the water's surface, the peaks seem to move to higher frequencies: 
Lid at -.05 m: <img src="https://github.com/user-attachments/assets/e99d5697-94ec-42ca-9652-a3ff83d8a186" width="300">

I can also reduce the mesh size factor to 0.2, and this helps with the peaks, but the lid still doesn't move them completely out of the frequency range that I'm using: 
No lid: <img src="https://github.com/user-attachments/assets/322626cb-e525-421b-bd6a-2596ccaaf1b5" width="300"> Lid: <img src="https://github.com/user-attachments/assets/3247f3a5-c522-4f44-a985-75ae09f1df5a" width="300">

Is this the expected behavior or should the peaks be completely removed when using the internal lid feature? And is there a recommended best practice to go about resolving the peaks? Should I always use the internal lid with the `lowest_lid_position` and run BEM with a progressively finer mesh until the peaks are fully removed?

[meshWB.zip](https://github.com/user-attachments/files/16289298/meshWB.zip)

**Comment by mancellin** [comment]
A lid below the free surface ($z<0$) moves irregular frequencies to higher frequencies.
The closer to the free surface, the higher the frequency of the irregular frequency. But also the closer to the free surface, the more singular the Green function integral that Capytaine have to compute.

`lowest_lid_position()` is an estimate of a compromise based on the formula for the first irregular frequency of a parallelepiped. It works okay-ish on other shapes but could probably be improved.
If it is not sufficient for you, try putting the lid closer to the free surface and refining the mesh.

The experimental support for panels _on_ the free surface gives often better results than I expected at cancelling all irregular frequencies. So try it also by setting a lid on $z=0$.

**Comment by jtgrasb** [comment]
This helped clear it up, thanks!
