### ISSUE TITLE
RAO calculation simple sample

### ISSUE THREAD

**Issue by izabala123** [capytaine/capytaine#586]
Good morning

Sorry for the simple question: I wanted to ask you how to calculate and store the RAO, inside this code.

Thank you in advance!
Iñaki

```
import numpy as np
import capytaine as cpt
from capytaine.io.xarray import problems_from_dataset
from capytaine.bem.airy_waves import airy_waves_pressure
import xarray as xr
import os

mesh_1 = cpt.load_mesh("./mesh/Body_1.dat", file_format="nemoh")
lid_mesh_1 = cpt.load_mesh("./mesh/Body_1_lid.dat", file_format="nemoh")

body_1 = cpt.FloatingBody(mesh=mesh_1,lid_mesh=lid_mesh_1,  dofs=cpt.rigid_body_dofs(rotation_center=(0.000000, 0.000000, 0.000000)), center_of_mass=(0.000000, 0.000000, 0.000000), name="Buoy")

body_1.inertia_matrix = body_1.compute_rigid_body_inertia()
body_1.hydrostatic_stiffness = body_1.compute_hydrostatic_stiffness()

list_of_bodies = [body_1]
all_bodies = cpt.FloatingBody.join_bodies(*list_of_bodies)
test_matrix = xr.Dataset(coords={
    "omega": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5],
    "wave_direction": [0, 0.785398163397448, 1.5707963267949],
    "radiating_dof": list(all_bodies.dofs),
    "water_depth": 200,
    "rho": 1025
})

solver = cpt.BEMSolver()
pbs = problems_from_dataset(test_matrix, all_bodies)
results = solver.solve_all(pbs, keep_details=True)
ds = cpt.assemble_dataset(results)

mesh = all_bodies.mesh

ds.coords["space_coordinate"] = ["x", "y", "z"]
ds["dof_definition"] = (["radiating_dof", "face", "space_coordinate"], np.array([all_bodies.dofs[dof] for dof in all_bodies.dofs]))

ds.coords["rigid_body_component"] = [body.name for body in list_of_bodies]
ds["rotation_center"] = (["rigid_body_component", "point_coordinates"], [body.rotation_center for body in list_of_bodies])
ds["center_of_mass"] = (["rigid_body_component", "point_coordinates"], [body.center_of_mass for body in list_of_bodies])

# Export to NetCDF file
from capytaine.io.xarray import separate_complex_values
separate_complex_values(ds).to_netcdf("HAMS_Test_Capy.nc",
                                          encoding={"radiating_dof": {"dtype": "U"},
                                                    "influenced_dof": {"dtype": "U"}})
```

**Comment by mancellin** [comment]
Something like the following (after `assemble_dataset`, but before `to_netcdf` to save it in file):
```python
from capytaine.post_pro.rao import rao
ds["rao"] = rao(ds)
```

Additional dissipation or stiffness matrices can also be provided:
```python
rao(ds, dissipation=..., stiffness=...)
```

**Comment by izabala123** [comment]
Great, thank you! I'll try it this weekend.

**Comment by izabala123** [comment]
Great, thank you! It works perfect.
Could you include an example of how to fill 'dissipation'?

**Comment by mancellin** [comment]
`dissipation` and `stiffness` require a matrix of the same form as `ds.radiation_damping` or `ds.hydrostatic_stiffness`.

For instance, if you want to cancel the radiation damping for some reason:
```python
ds["no_damping_RAO"] = rao(ds, dissipation=-ds.radiation_damping)
```

To add the required metadata to a raw matrix:
```python
my_dissipation = all_bodies.add_dofs_labels_to_matrix([
    [100.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 100.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 100.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    ])

ds["other_RAO"] = rao(ds, dissipation=my_dissipation)
```

**Comment by mancellin** [comment]
> is it possible to get the added mass at zero and at infinite frequency?

Only in infinite depth.
You can just provide `0.0` or `np.inf` in the list of frequencies you give to the solver.

```python
test_matrix = xr.Dataset(coords={
    "omega": [0.0, 1.0, np.inf],
    "radiating_dof": list(all_bodies.dofs),
    # "wave_direction": [0, 0.785398163397448, 1.5707963267949],
    "water_depth": np.inf,
    "rho": 1025
})
```
You currently need to remove the `wave_direction` or the solver will try to solve diffraction problems with 0- or infinite-frequency. This can probably be improved.

**Comment by izabala123** [comment]
> `dissipation` and `stiffness` require a matrix of the same form as `ds.radiation_damping` or `ds.hydrostatic_stiffness`.
> 
> For instance, if you want to cancel the radiation damping for some reason:
> 
> ```python
> ds["no_damping_RAO"] = rao(ds, dissipation=-ds.radiation_damping)
> ```
> 
> To add the required metadata to a raw matrix:
> 
> ```python
> my_dissipation = all_bodies.add_dofs_labels_to_matrix([
>     [100.0, 0.0, 0.0, 0.0, 0.0, 0.0],
>     [0.0, 100.0, 0.0, 0.0, 0.0, 0.0],
>     [0.0, 0.0, 100.0, 0.0, 0.0, 0.0],
>     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
>     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
>     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
>     ])
> 
> ds["other_RAO"] = rao(ds, dissipation=my_dissipation)
> ```

Thank you Matthieu

In case of a multi body case, the dimension of this matrix would be nb*6 x nb*6?
Sorry for asking such specific questions, but I don't want to be too clever and make inadvertent mistakes.

Best regards
Iñaki

**Comment by izabala123** [comment]
> ```python
> ave_directio
> ```

Thank you Matthieu

Could this be managed in python in some way to get, in the same .nc file, both the added masses at 0 and np.inf, and the results for the different headings? Could this work in case of getting results at mesh panel level?

Best regards
Iñaki

**Comment by mancellin** [comment]
> In case of a multi body case, the dimension of this matrix would be nb6 x nb6?

Yes

> Could this be managed in python in some way to get, in the same .nc file, both the added masses at 0 and np.inf, and the results for the different headings?

I'll try to fix that in the library.

> Could this work in case of getting results at mesh panel level?

In principle, it should work.

**Comment by mancellin** [comment]
> > Could this be managed in python in some way to get, in the same .nc file, both the added masses at 0 and np.inf, and the results for the different headings?
> 
> I'll try to fix that in the library.

#587

**Comment by izabala123** [comment]
Thank you!
