### ISSUE TITLE
`connected_components` is very expensive

### ISSUE THREAD

**Issue by ldouteau** [capytaine/capytaine#601]
Hi, thanks again for Capytaine!

Im trying to run a HDB (100 frequencies, 10 dofs) on a huge mesh (35k vertices, 33k faces), and the wavelength check is taking ages (7hours expected). I narrowed the issue to `solve_all` calling`_check_wavelength_and_irregular_frequencies` calling `connected_components`, which is very expensive.

https://github.com/capytaine/capytaine/blob/c5658dd430e42eb16fd7edb26f919ef28f321c14/capytaine/meshes/properties.py#L202-L233

From what i understand this function starts with a clustering step, to gather the faces that share at least 1 point. It's this step that seems to be the most expensive. E.g., from my test case:

```
clustering 22.139901876449585s
check 0.0s
face identifiction 0.11008667945861816s
face extraction 0.0314946174621582s
```

I've not had the time to investigate on this, i'll do eventually, but if someone wants to jump in feel free

**Comment by mancellin** [comment]
Ok I should have tested that on bigger meshes :grimacing:

This is only to provide a warning if you might encounter irregular frequencies, so if you know what you're doing, you can turn it off, for instance with something like that:
```python
from capytaine.io.xarray import problems_from_dataset
problems = problems_from_dataset(test_matrix, body)
solver = cpt.BEMSolver()
results = solver.solve_all(problems, keep_details=False, _check_wavelength=False)
dataset = cpt.assemble_dataset(results)
```

**Comment by mancellin** [comment]
The code is redoing the exact same clustering for each of the 100 freq×10 dofs problems...
That should be easy to improve.

**Comment by ldouteau** [comment]
I though about this over the weekend, with 2 main conclusions

* I wonder if the generation of connected vertices could be a cached property of the mesh instance ? I'm pretty sure it would work for my test case, but i dont know for others
* I've though about another algorithm that introduces some vectorization. I'll test that & open a pr if the results are promizing

**Comment by mancellin** [comment]
> I wonder if the generation of connected vertices could be a cached property of the mesh instance ? I'm pretty sure it would work for my test case, but i dont know for others

In #602, I'm caching the `body.first_irregular_frequency_estimate()`.
I guess we could also cache the `connected_components` of the `Mesh` (in the same way we cache the `faces_centers` or the `faces_areas` of the mesh), but at the moment I believe their only use in is `first_irregular_frequency_estimate()`.

> I've though about another algorithm that introduces some vectorization. I'll test that & open a pr if the results are promizing

Oh, that would be nice.
