### ISSUE TITLE
Are dipole solutions included?

### ISSUE THREAD

**Issue by daanscheltens** [capytaine/capytaine#604]
For a monopile (a vertical cylinder whidh is open at the bottom) I made a simple mesh using `mesh_vertical_cylinder` and then cutting away to top and bottom in order to calculation the diffraction results using dipoles.

In the manual it is stated that: " Two methods are implemented including 1) direct method (source-and-dipole formulation), and 2) indirect method (source formulation)"

My interpretation of this was that I can run the open cylinder mesh in capytaine using dipoles by selecting the solve mehtod="direct".
```python
cylinder_open = cpt.FloatingBody(mesh=mesh_open, center_of_mass=[0, 0, 0], name="mp_open")
cylinder_open.add_translation_dof(name="Surge")
problems = [cpt.RadiationProblem(body=cylinder_open, radiating_dof="Surge", omega=omega, water_depth=water_depth, rho=water_density)]
solver = cpt.BEMSolver()
results = solver.solve_all(problems, method="direct")
```

However, the resulting added mass is similar to a source solution and does not seem to be using dipoles. Is a dipole solution actually included? What do I need to update on the mesh or on the body to make the solver run it as dipoles?

Thanks.

**Comment by mancellin** [comment]
Dipoles for the modelling of thin plates are not implemented in Capytaine at the moment.

The direct Boundary Integral Equation has several names in the literature, such as "potential formulation" or "source-and-dipole formulation". But this last name is confusing and I shouldn't have included it in the documentation. (I got myself confused in https://github.com/capytaine/capytaine/issues/44#issuecomment-1123196275)

**Comment by daanscheltens** [comment]
Thanks for the clarification. 
Do you know if the dipole method for thin plates is available in Nemoh, and if there are plans to include this is capytaine? It is a realy nice option to have.

**Comment by mancellin** [comment]
Thin plates are not implemented in Nemoh, nor in any other open source BEM solver that I know.

It's on Capytaine long-term todo list, but there is no concrete plan nor funding to do that soon.
