### ISSUE TITLE
Error: operands could not be broadcast together with shapes (14124,3) (14112,3) 

### ISSUE THREAD

**Issue by dforbush2** [capytaine/capytaine#620]
It appears that this error occurs depending on mesh_size_factor.

I've attached the code in question. This error appears verbatim if mesh_size_factor = 0.07, and the error also appears for other values of mesh_size_factor, but everything works fine if mesh_size_factor = 0.14. I would appreciate some guidance on a robust way to select this value for things to work. 

"
Traceback (most recent call last):

  File ~\anaconda3\envs\capy_env\Lib\site-packages\spyder_kernels\customize\spyderpdb.py:900 in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File ~\anaconda3\envs\capy_env\Lib\bdb.py:600 in run
    exec(cmd, globals, locals)

  File c:\users\dforbus\teamermarson\capytaineforwecsim\capysetupspyder.py:122
    capyData = solver.fill_dataset(problems, [all_bodies], hydrostatics=False)

  File ~\anaconda3\envs\capy_env\Lib\site-packages\capytaine\bem\solver.py:280 in fill_dataset
    problems = problems_from_dataset(dataset, bodies)

  File ~\anaconda3\envs\capy_env\Lib\site-packages\capytaine\io\xarray.py:134 in problems_from_dataset
    RadiationProblem(body=body_range[body_name], **{freq_type: freq},

  File ~\anaconda3\envs\capy_env\Lib\site-packages\capytaine\bem\problems_and_results.py:410 in __init__
    self.boundary_condition = -1j * self.encounter_omega * np.sum(dof * self.body.mesh.faces_normals, axis=1)

ValueError: operands could not be broadcast together with shapes (14124,3) (14112,3) 
"
[CapySetupSpyder.txt](https://github.com/user-attachments/files/18002231/CapySetupSpyder.txt)

**Comment by dforbush2** [comment]
Some additional context and debug efforts:
1) Seems like this error came about in a recent version of Capytaine. We didn't used to see it very often.
2) it is unrelated to the "lid" functionality, as it seems to occur both with and without a lid specificied. 
3) Tried with some other basic shapes like cylinders, and was unable to run due to this error for all of the mesh_size_factor values attempted.

**Comment by mancellin** [comment]
Thanks for the report! I can reproduce the issue, it is related to #367.

Adding a `heal_mesh` between `keep_immersed_part` and `add_all_rigid_body_dofs` seems to fix the issue.
Basically, the mesh had not been healed when defining the dofs, and when the mesh is healed later the dofs becomes inconsistant.

I'm trying to update all the docs and examples to use the following declarative syntax which is a bit more robust to this kind of operation ordering bugs:
```python
        rect[nBod] = cpt.FloatingBody(
            mesh=meshObj.immersed_part(),
            lid_mesh=lidMesh,
            dofs=cpt.rigid_body_dofs(rotation_center=(bodyLocs[nBod], 0, 0)),
            center_of_mass=(bodyLocs[nBod], 0, 0),
            name="rect"+str(nBod),
        )
```

**Comment by dforbush2** [comment]
hi @mancellin 

Thank you for your speedy reply. This does indeed solve the above issue, however it does not appear that it results in the intended mesh. I have attempted various versions of heal_mesh,
* mesh.heal_mesh()
* mesh_include_lid.heal_mesh()
* Define mesh without the lid, mesh.heal_mesh(), then add the lid.

And I have used the code you have provided as well.

And in all of the above cases it does not appear that the lid is as intended:
![image](https://github.com/user-attachments/assets/017ada05-48a2-41dc-8b58-559e93a69c87)

where the lid mesh is blue.

I have also tried various mesh resolutions without the lid, and I am struggling to get nice looking results. I am open to any suggestions. Another question I have: is it possible to define the lid surface simply as another face of the geometry? Or are the lid panels handled differently by the calculation? Thank you!

**Comment by mancellin** [comment]
Do you have a full script to share? I can't reproduce your issue with the lid.

![mesh screenshot](https://github.com/user-attachments/assets/17a4529d-8c30-4944-b776-98e8fe2dcecb)

> is it possible to define the lid surface simply as another face of the geometry? Or are the lid panels handled differently by the calculation?

Lid panels are treated differently than the rest of the mesh (for instance, they are not taken into account in the pressure integration to compute the force). If you have a single mesh with lid panels generated with e.g. pygmsh, you'll need to extract the lid mesh. Something like this:

```python
with pygmsh.geo.Geometry() as geom:
    box = geom.add_box(0, -1, 0, -1, 0, -1, mesh_size=0.1)
    gmsh_mesh = geom.generate_mesh()
mesh = load_from_meshio(gmsh_mesh, name='full box')

hull_mesh, lid_mesh = mesh.extract_lid()

body = cpt.FloatingBody(
    mesh=hull_mesh.immersed_part(),
    lid_mesh=lid_mesh,
    dofs=cpt.rigid_body_dofs(rotation_center=mesh.center_of_buoyancy),
)
```
